### ISSUE TITLE
Missing dll for git on Windows

### ISSUE THREAD

**Issue by FlowerZY** [gprMax/gprMax#100]
I've successfully installed Miniconda. 
When I input the command "git clone https://github.com/gprMax/gprMax.git", it showed me that "Can not locate the program input point EVP-aes-128-ctr on the dynamic link library LIBEAY32.dll**".
Of course, I‘ve checked the LIBEAY32.dll, it does exsit in my computer.
Can you help me ?Thank you a lot!

**Comment by craig-warren** [comment]
Looks like your system is somehow missing the `libeay32.dll`. Try installing OpenSSL with conda which should install the DLL, e.g. `conda install openssl`

**Comment by FlowerZY** [comment]
I‘ve tried but failed.
As the DOCs said—— If you prefer to install Python and the required Python packages manually, i.e. without using Anaconda/Miniconda, look in the conda_env.yml file for a list of the requirements.

If I don't use Miniconda, what are the specific steps ？
Thank you again!

**Comment by craig-warren** [comment]
If you are not using Miniconda then I'm afraid it is assumed you are confident installing Python packages yourself. I would recommend you stick with the Miniconda route. What operating system are you using?

**Comment by FlowerZY** [comment]
Win7 x 64. 
I just remembered that I used to install Python and uninstalled  later. Does this matter to my problem?

And I used my roommate's computer to install gprMax. The same thing happened. But the DLL which she missed  differed from mine. 

I'm wondering weather reinstalling the system would help.

It‘s kind of you to answer my questions so patiently.Thank you!

**Comment by craig-warren** [comment]
No, already having Python installed should not affect things - the idea of using Miniconda is that it creates a completely separate environment for gprMax.

It is strange that you encounter missing dlls on two different machines. We haven't seen this issue before. Have you viewed the installation screencast - [http://docs.gprmax.com/en/latest/screencasts.html#installation](http://docs.gprmax.com/en/latest/screencasts.html#installation) - to make sure you are following all the steps correctly?

**Comment by FlowerZY** [comment]
Yes, I have viewed the screencast. I reinstalled my system yesterday and it works.  Maybe gprMax requires a 'clean' system.

**Comment by craig-warren** [comment]
It shouldn't require a clean system, but it sounds like there were some critical dlls missing.

Good to hear it is working now.
