### ISSUE TITLE
learning gprmax

### ISSUE THREAD

**Issue by Mohamed-Elsaid** [gprMax/gprMax#102]
I try to learn gprmax software but i don't know from where should I start the learning. is there any tutorials to help me? If possible someone told me how to start using gprmax?

thanks

**Comment by craig-warren** [comment]
This is not an issue with the code. Please ask general questions in our forum [(http://www.gprmax.com/forum.shtml).](http://www.gprmax.com/forum.shtml) There are also examples to get started with in the User Guide docs [(http://docs.gprmax.com/)](http://docs.gprmax.com/)
