### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by FlowerZY** [gprMax/gprMax#104]
The following is my code. When I try to run ,there is a Indexerror:List index out of range. Can you help me out of this problem?
#title：zy
#domain:2.0 0.5 0.01
#dx_dy_dz:0.01 0.01 0.01
#time_window:18e-9

#material:9 0.01 0 0 concrete

#waveform:ricker 1 1e9 zy_ricker
#hertzian_dipole:z 2.5 2 0 zy_ricker
#rx:2.5 2 0

#box:0 0 0 2 0.5 0.01 concrete

#geometry_view:0 0 0 2.0 0.5 0.01 0.01 0.01 0.01 zy n

**Comment by craig-warren** [comment]
@FlowerZY there are a number of problems with your input file. I suggest you have a closer look at the guidance and examples in the User Guide. 

* The initial reason for your code not running is that the character you have placed after `#title` is not a colon (compare it to the other genuine colons in your code)
* Also you should have a blank space between the command name and parameters, e.g. `#title: xy`
* Your source and receivers are not inside the domain
* Your `concrete` material cannot have a permeability of 0

Kind regards,

Craig

**Comment by FlowerZY** [comment]
Your answers are really helpful. There is only one thing that I don't understand. 

Why the material cannot have a permeability of 0? I have read some related thesis. The number are almost set to 1. I just don't know why.

Looking forward to your early reply.

**Comment by craig-warren** [comment]
Again this is not an issue with the code, but a general question about permeability. Please post it in the forum (Google Group).
