### ISSUE TITLE
Snapshot: what do the xs, ys, zs,xf,yf,zf,mean

### ISSUE THREAD

**Issue by FlowerZY** [gprMax/gprMax#105]
Can you tell me how to use Snapshot？I can't figure out what do the xs, ys, zs,xf,yf,zf,mean.

TIP:
You can take advantage of Python scripting to easily create a series of snapshots. For example, to create 30 snapshots starting at time 0.1ns until 3ns in intervals of 0.1ns, use the following code snippet in your input file. Replace xs, ys, zs, xf, yf, zf, dx, dy, dz accordingly.

#python:
from gprMax.input_cmd_funcs import *
for i in range(1, 31):
    snapshot(xs, ys, zs, xf, yf, zf, dx, dy, dz, (i/10)*1e-9, 'snapshot' + str(i))

Kind regards.

**Comment by craig-warren** [comment]
This is a general question for the forum (Google Group), and not an issue with the code. Please do not post general questions here.
