### ISSUE TITLE
How do the tests work?

### ISSUE THREAD

**Issue by fake-name** [gprMax/gprMax#109]
How does one run the tests? Normally, I'd assume they'd be run with something like [`nose`](http://nose.readthedocs.io/en/latest/) or the old fashioned [`unittest`](https://docs.python.org/3/library/unittest.html) framework, but it looks like that's not how the tests work at the moment.

How are the tests intended to be used?

**Comment by craig-warren** [comment]
So the tests are not in the vain of unit testing....yet. They are a series of basic and advanced models (input files) that are used to test a range of the different features and functionality of the code. The test models are run, and their output(s) compared against expected output (from previously validated code). There are also comparisons with analytical solutions (where it is possible to do) and other numerical codes (such as the Method of Moments). The tests are intended to be run with the script `test_models`, i.e. `python -m tests.test_models`. Within the script there is a list of models to run that can be edited as appropriate. The script calls  gprMax via the API.

**Comment by fake-name** [comment]
Yeah, I kind of wound up figuring that out.

FWIW, I'm in the process of writing relatively comprehensive tests for things I want to refactor, so I can be confident I didn't break anything. I think I should have a PR in the near future.

**Comment by fake-name** [comment]
FWIW, I'm still interested in doing the refactors I described, I've just been called off to a different project at work for the last month or so. When I have time, I do expect to actually produce some changes.

**Comment by craig-warren** [comment]
Great, I'll leave this open for now then.

**Comment by fake-name** [comment]
Hey, sorry it's taken me so long to get back to this.

Anyways, I've been working on a large-scale redesign of how the geometry system works, as an adjunct to adding tests, and I'd like to just run the design ideas by you folks before I go and spend a bunch of time on implementation.

Basically, right now, the geometry building process is basically one enormous 1000+ line function, with some helpers. This one line does *everything* for parsing input files.

This makes it basically uncomfortable. If you want to write a python script that does fancy parametric geometry, or anything, it's basically impossible, because everything is bundled into that one function, and therefore not independently accessible (this makes testing hard, too!).

The design I like is as follows:

 - Each geometry object type has it's own class (`#edge`, `#plate`, `#triangle`, etc..)
 - Each geometry class needs to expose two functions (with interface contracts enforced by abstract base classes): 
    - the default `__init__`, which receives the object parameters (location, material, etc...),  -
    - `install_into_world`, which takes the world-grid (usually `G`), and modifies the world grid as described in the stored parameters.  

This structure allows very easy programmatic use. You simply create the world objects, and iterate over each installing it into the world. This means you can easily construct geometry from a python file, rather then an `.in` file for more advanced analysis.  It also means testing is much easier, since you no longer need to generate a fake configuration script that then would get passed to `process_geometrycmds`.   

Lastly, it makes *documenting* how the geometry stuff works a lot easier, since geometry commands map directly to class constructor arguments. This means we can use existing python document generation facilities to generate documentation, and it will automatically stay up-to-date, since it's derived from the actual source.

I've started on the process described above, you can find my initial work [here](https://github.com/fake-name/gprMax/blob/rework/gprMax/geometry_classes.py) and [here](https://github.com/fake-name/gprMax/blob/rework/gprMax/input_cmds_geometry.py#L58).

**Comment by jasminium** [comment]
Hi @fake-name I like the look of the refactor. I especially like the idea of a point class - this will make translations and rotations much easier. Preserving the .in scripting interface is great too.

Regarding the points. I notice you initialise self.origin, self.end and any other vertices

`self.origin = util.to_3d_point(x_origin, y_origin, z_origin)`

and then in the build function

`self.origin = util.to_3d_point(util.round_value(self.origin.x / world_grid.dx),`

it might be nice to include another property or just a local variable for the discretised coordinate. Just to preserve the meaning of the point. I've run into this problem a few times in the code and it would be nice to iron it while we're here.

I would also like to see nestable objects. Rough idea. The abstract geometry class extends a node type. Nodes can be linked together in a tree or similar and represent the order in which they are to be added to the world grid. Additionally the whole tree can translated in space etc.. This would be really useful for complex objects and for sub-gridding.

I made a working version as a wrapper to the existing interface a while ago which i'm using. But it would be much more powerful combined with this new design.

Realise this is suggesting even more work! But i'd like to help out if there is interest!

https://github.com/gprMax/gprMax/blob/dev/gprMax/geometry_objects.py

**Comment by fake-name** [comment]
Keeping the original points around is definitely a good idea, I've actually wound up needing to do it in various locations manually when I can't figure out where a breaking line is coming from. 

I'm *trying* to move the build-functions to use the `def to_int_point(self, x_step, y_step, z_step):` function attached to the `PointType()` class, since that makes things a lot easier to read/follow. 

These comments goaded me into adding some more metadata to the point class, see https://github.com/fake-name/gprMax/commit/5ddd4c3bc9638cfa4aefd16683f2fc68666b5d9e
