### ISSUE TITLE
Error - Compile Cython extensions

### ISSUE THREAD

**Issue by neilwang0913** [gprMax/gprMax#11]
I have followed the instruction to install everything expect the MPI.

I go the "Comple Cython Extensions" Stage by running the : python3 setup.py build_ext --inplace
The error happen : 
Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    os.environ['CC'] = glob.glob('/usr/local/bin/gcc-[4-5]*')[0].split(os.sep)[-1]
IndexError: list index out of range

Could you let me how to fix this error,please?

Many thanks.

Fengzhou

**Comment by craig-warren** [comment]
Hi Fengzhou,

Can you tell me a bit more about what machine and OS you are using? From the error you are getting I'm guessing it is Mac OS X. On Mac OS X you need to have gcc installed which is easiest done via Homebrew (http://brew.sh). The error you are getting suggests Python can't find gcc which is used to compile the Cython extensions.

**Comment by neilwang0913** [comment]
Hello:

I am using the lastest Macbook Pro and Mac Mini as well with lastest apple
OS version: OS X El Capitan.

I did follow the instruction which guide me to Homebrew (http://brew.sh)
and by simply copy and paste the commend:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/mas
And it successful installed.

Is there way to check whether I have installed it in the properly way or
not.

Meanwhile, I did install Xcode in my Mac Mini but not in my Macbook Pro.
And it give me the same error.

Looking forward your reply.

Regards#

Fengzhou


ter/install)"

**Comment by craig-warren** [comment]
Hi Fengzhou,

Homebrew is just a package manager, you must use it to install gcc, e.g. brew install gcc

**Comment by neilwang0913** [comment]
Hello:

I have run brew install gcc and then run "python3 setup.py build_ext
--inplace"

But a serious error happen and I copy the last two line :

*/var/folders/_j/9q99q_6x7v765l86cy_v8y040000gp/T//ccZ4acjb.s:74636:13:
**error:
**register %rip is only available in 64-bit mode*

error: command 'gcc-5' failed with exit status 1

Is there any hit to fix this prolem?

Many thanks.

Fengzhou

**Comment by craig-warren** [comment]
Hi Fengzhou,

I can't tell what has gone wrong from those lines. Please attach or copy/paste more of the error messages from gcc.

**Comment by neilwang0913** [comment]
Hello:

I was try to copy the error but it seems so long and I cannot attached the
.txt file.
So I share a google fold shared link and please check with that.​
 GPRmax Installation
<https://docs.google.com/folderview?id=0B48AviLQL3OTYllhS1VnaTNkQnM&usp=drive_web>
​
Many thanks

Fengzhou

**Comment by craig-warren** [comment]
Can you check you are using Python 3. `python` usually points to Python 2.7 `python3` usually points to Python 3.

**Comment by neilwang0913** [comment]
Hello :

I am show the path and also the pip list.
I run the python for version 2.7 and python3 for version 3 as well.
It is given me the same error.

Kind regards.

Fengzhou

**Comment by craig-warren** [comment]
gprMax is only compatible with Python 3.x. The error you are seeing is happening at the point that gcc is being used to compile the C files that have been generated by Cython. Can you run `gcc-5 -v` and paste the output here please.

**Comment by neilwang0913** [comment]
Hello ,

After running the commend "gcc-5 -v ", the result is shown as:


Fengzhous-MacBook-Pro:~ fengzhouwang1$ gcc-5 -v

Using built-in specs.

COLLECT_GCC=gcc-5

COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/5.2.0/libexec/gcc/x86_64-apple-darwin15.0.0/5.2.0/lto-wrapper

Target: x86_64-apple-darwin15.0.0

Configured with: ../configure --build=x86_64-apple-darwin15.0.0
--prefix=/usr/local/Cellar/gcc/5.2.0
--libdir=/usr/local/Cellar/gcc/5.2.0/lib/gcc/5
--enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5
--with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr
--with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl
--with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking
--enable-checking=release --enable-lto --with-build-config=bootstrap-debug
--disable-werror --with-pkgversion='Homebrew gcc 5.2.0' --with-bugurl=
https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls
--enable-multilib

Thread model: posix

gcc version 5.2.0 (Homebrew gcc 5.2.0)


Kind regards.


Fengzhou

**Comment by craig-warren** [comment]
I suspect it could be a problem with gcc. Could you try `brew reinstall gcc --without-multilib`, which may take a while. Then try compiling the Cython extensions again using `python3 setup.py build_ext --inplace`

**Comment by jjohnhhartley** [comment]
Hi All,

We’ve resolved the issue now. Another Python binary install from their website.

Cheers
> On 25 Nov 2015, at 14:32, Craig Warren <notifications@github.com> wrote:
> 
> I suspect it could be a problem with gcc. Could you try brew reinstall gcc --without-multilib, which may take a while. Then try compiling the Cython extensions again using python3 setup.py build_ext --inplace
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/gprMax/gprMax/issues/11#issuecomment-159623960>.
> 


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by neilwang0913** [comment]
Thank you Craig Warren very much for your guiding.

Also many thanks John.

Regards.

Fengzhou
