### ISSUE TITLE
Error Code?

### ISSUE THREAD

**Issue by Astroblem** [gprMax/gprMax#110]
I'm wondering if there is an error code.  I'm trying to run a model and I get "IndexError list index out of range".

Thanks.

**Comment by agianno** [comment]
@Astroblem We will need more information to see if this is a bug or a problem with your input file. Maybe you want to try our Forum (http://www.gprmax.com/forum.shtml) to get some help if it is a problem with your input file.

**Comment by Astroblem** [comment]
Yes, there was a problem with my input.  Sorry for the confusion.
