### ISSUE TITLE
Slightly silly: `psutil.cpu_count(logical=False)` does not always return a value.

### ISSUE THREAD

**Issue by fake-name** [gprMax/gprMax#111]
Basically, I'm experimenting with some CPU testing on ARM, and it appears that there is a bug in how the CPU count is checked.

Right now, https://github.com/gprMax/gprMax/blob/master/gprMax/utilities.py#L282 does:

```
    try:
        # Get number of physical CPU cores, i.e. avoid hyperthreading with OpenMP
        hostinfo['physicalcores'] = psutil.cpu_count(logical=False)
    except ValueError:
        hostinfo['physicalcores'] = hostinfo['logicalcores']
```
However, `cpu_count` *can* return `None` if it cannot determine a value. On my ARM system (a Raspberry Pi 3), this occurs for all calls where `logical=False`.

This incorrect value then causes a failure later when the number of cores is used assuming it's an integer.

Ideally, this should *probably* be something like: 

```
    try:
        # Get number of physical CPU cores, i.e. avoid hyperthreading with OpenMP
        hostinfo['physicalcores'] = psutil.cpu_count(logical=False)
    except ValueError:
        hostinfo['physicalcores'] = hostinfo['logicalcores']
    if not hostinfo['physicalcores']:
        hostinfo['physicalcores'] = hostinfo['logicalcores']
```

Yes, running GPRMax on a pi is silly. That's not the issue here, and there are bigger ARM systems out there.

**Comment by craig-warren** [comment]
@fake-name Yes, we should be doing something to handle the case when `None` is returned. What you suggest seems sensible.

**Comment by craig-warren** [comment]
Fixed in commit https://github.com/gprMax/gprMax/commit/c2b91c062e8cb81d9cdc02bea91201f0acfc5a1d

**Comment by fake-name** [comment]
Sweet!
