### ISSUE TITLE
problem in using MALA antenna

### ISSUE THREAD

**Issue by Mohamed-Elsaid** [gprMax/gprMax#117]
when I try to use MALA antenna in the GPRMAX via the following code

#title: B-scan from a metal cylinder buried in a dielectric half-space
#domain: 0.240 0.210 0.210
#dx_dy_dz: 0.002 0.002 0.002
#time_window: 3e-9
#material: 6 0 1 0 half_space
#python:
from user_libs.antennas import antenna_like_MALA_1200
antenna_like_MALA_1200(0.10,0.09,0.03)
#end_python:
#box: 0 0 0 0.240 0.170 0.002 half_space
#cylinder: 0.120 0.080 0 0.120 0.080 0.002 0.010 pec

there's no results appear in the receiver after the simulation has finished.
I need ask if there's any mistakes in the code or there are conditions on the location of the antenna?

**Comment by craig-warren** [comment]
@Mohamed-Elsaid you should first check the geometry of your model. Your box and cylinder lie completely within the Perfectly Matched Layer (PML) boundaries of the model. Also the Mala antenna is partly in the PML. I recommend you familiarise yourself with the FDTD method and the example models.

For more general questions such as this please post in our Forum (Google group) - http://www.gprmax.com/forum.shtml

Kind regards,

Craig
