### ISSUE TITLE
winx64 user. gprmax.fields_updates build issue

### ISSUE THREAD

**Issue by makhamehchi** [gprMax/gprMax#118]
Hi, I followed the instructions and the field_updates build failed. I am not sure what part I am missing. I tried both dev and master branches with no luck. Please help!
Thanks.

**Comment by craig-warren** [comment]
@makhamehchi Can you post a screenshot or copy/paste of the error message please. Are you saying it failed at the stage you ran `python setup.py build`, or when you attempted to run a test model?
