### ISSUE TITLE
convert time to depth

### ISSUE THREAD

**Issue by mahmoodsafavi** [gprMax/gprMax#119]
hi 
how can change plot y axis from time to depth?
i know should be change in tools.plot_Bscan, but how?
i am new python.
best regard

**Comment by craig-warren** [comment]
@mahmoodsafavi You will need to know some basic Python to edit the plotting scripts. Lines 86 and 88 in the plot_Bscan.py script will allow you to change the y-axis. See the matplotlib documentation for further information - https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.imshow

Kind regards,

Craig

**Comment by mahmoodsafavi** [comment]
@craig-warren thanks for your reply.
