### ISSUE TITLE
Triangle with paraview

### ISSUE THREAD

**Issue by ELEGER** [gprMax/gprMax#12]
Hi Craig,
I'm wondering if paraview is able to display triangle geometry.
I'm trying to see "#triangle" using paraview but tend to not show it...

I just modified the A-scan example

 #title: A-scan from a metal cylinder buried in a dielectric half-space
#domain: 0.240 0.190 0.002
#dx_dy_dz: 0.002 0.002 0.002
#time_window: 3e-9
#time_step_limit_type: 2D
#pml_cells: 10 10 0 10 10 0

#material: 6 0 1 0 half_space

#waveform: ricker 1 1.5e9 my_ricker
#hertzian_dipole: z 0.100 0.170 0 my_ricker
#rx: 0.140 0.170 0

#box: 0 0 0 0.240 0.170 0.002 half_space
#triangle: 0.1 0.1 0.002 0.2 0.1 0.002 0.15 0.15 0.002 0 pec  

#geometry_view: 0 0 0 0.240 0.190 0.002 0.002 0.002 0.002 cylinder_half_space n

Any hints on that ?

cheers

emmanuel

**Comment by agianno** [comment]
Hi Emmanuel,

The triangle works OK in 2D and you can see it in Paraview. However, even in 3D the triangle is a 2D structure with some thickness. In a 2D model you must specify the invariance coordinate as zero and the thickness as your Dz. So, in your case the correct command will be:

#triangle: 0.1 0.1 0.0 0.2 0.1 0.0 0.15 0.15 0.0 0.002 pec

this works but the triangle is not as perfect ...

In 3D, the triangle could  be only the surface of a Yee Cell (i.e. zero thickness) However, in 2D this cannot be the case as the faces of the Yee Cell in the invariance direction are already set to PEC (i.e. zero). So, you can only have objects that space the thickness of the invariance direction (one cell ...)

Hope this makes some sense!

Best

Antonis
