### ISSUE TITLE
#material

### ISSUE THREAD

**Issue by mahmoodsafavi** [gprMax/gprMax#120]
hi 
i know should be set 4 parameters to create new material, but in many paper just give me 2 parameters.
for example :
aluminum: dielectric constant is 3.1 and conductivity is 2.3e7
or 
plastic: dielectric constant is 3.0 and conductivity is 0.01
i set this parameters but my result is very differente.
my question is this, how fine 2 other parameters.
thanks.

**Comment by craig-warren** [comment]
@mahmoodsafavi this is not an issue with the code. Please use our Google Group (Forum) - http://www.gprmax.com/forum.shtml - for this type of general question. In any case, see the User Guide - http://docs.gprmax.com/en/latest/input.html#material - which explains these parameters are the permeability and magnetic loss. You should have some understanding of these in the contexts of GPR and FDTD modelling.
