### ISSUE TITLE
#geometry_objects_read no dielectric smoothing option

### ISSUE THREAD

**Issue by fmwatson** [gprMax/gprMax#122]
According to the documentation, their should be an optional character to turn dielectric smoothing on/off for #gemometry_objects_read.  But input_cmds_multiuse.py just checks for if len(tmp) != 7 (line 764 in v3.1.1), so this option cannot be included.

**Comment by craig-warren** [comment]
@fmwatson Thanks for spotting this - it is an error in the docs, which I'm about to correct. Essentially that optional flag should not be there.

What I intended to describe in the docs was that if the geometry objects that are being read in (using #geometry_objects_read) were originally generated using gprMax, i.e. exported using #geometry_objects_write, then you can use dielectric smoothing as you like when you originally created the geometry. However, if the geometry objects that are being read in were generated by an external method then dielectric smoothing of those objects is not possible, i.e. they will be imported as is.
