### ISSUE TITLE
Conversion PNG to HDF5 problem 

### ISSUE THREAD

**Issue by Mohamed-Elsaid** [gprMax/gprMax#124]
Dear Craig,
I'm trying to convert more file from PNG to HDF5 file using the following command:- 
python -m tools.convert_png2h5 my_layers.png 0.002 0.002 0.002 -zcells 150
but there was error each time in the conversion. at first I fell under suspicion that the files which i used have some problems, so I tried to use the attached file which was found in the gprmax package which related to the PMA-1 landmine but I have obtained the same error. i sent the image file and the obtained syntax error in the attachment.

Regards 
Mohamed
![pma](https://user-images.githubusercontent.com/27287432/29730392-4adebcc6-89e0-11e7-87c8-68efa3aaf249.png)
![syntaxerror](https://user-images.githubusercontent.com/27287432/29730393-4ae2901c-89e0-11e7-96bc-99a7008da173.png)

**Comment by craig-warren** [comment]
Mohamed,

The example image you give is of a 3D object. The script is designed to create 2D geometry from a 2D image. The resulting geometry can be extended to 3D but the geometry will be invariant in the z-direction. Please test with a 2D image, and report back if you are still having problems.

Craig

**Comment by Mohamed-Elsaid** [comment]
Hi Craig,
I tried for the attached files (which are 2D images) but the same problem had been obtained.

![landmine](https://user-images.githubusercontent.com/27287432/29744892-64b50a28-8aae-11e7-8930-569fd99f2298.png)
![fc3](https://user-images.githubusercontent.com/27287432/29744893-64b8b650-8aae-11e7-9a9e-a8525f774508.png)

Thanks,
Mohamed

**Comment by craig-warren** [comment]
@Mohamed-Elsaid Looks like some sort of issue with your installation. I tested the first of the above files and it worked OK for me, i.e. `python -m tools.convert_png2h5 ~/Downloads/test.png 0.002 0.002 0.002 -zcells 150`
