### ISSUE TITLE
Dispersion analysis error with unreasonable sampling

### ISSUE THREAD

**Issue by wzhades** [gprMax/gprMax#126]
I ran the model, but it reported the error"IndexError: index 0 is out of bounds for axis  0  with size 0". I don't know where the error is . Can someone help me correct it? Following is my code.
#material: 6 0 1 0 my_soil
#material: 15 0 1 0 my_cylinder
--------------------------------------------
#domain: 1.5 1.0 0.7
#dx_dy_dz: 0.01 0.01 0.01
#time_window: 3e-9
--------------------------------------------
#box: 0.0 0.0 0.0 1.5 1.0 0.7 free_space
#box: 0.0 0.0 0.0 1.5 1.0 0.5 my_soil
#cylinder: 0.75 0.2 0.25 0.75 0.8 0.25 0.02 my_cylinder
--------------------------------------------
#waveform: ricker 1 20e9 my_ricker
#hertzian_dipole: x 0.4 0.5 0.52 my_ricker
#rx: 0.6 0.5 0.52
#src_steps: 0.02 0 0
#rx_steps: 0.02 0 0

**Comment by craig-warren** [comment]
@wzhades the reason for this error is due to numerical dispersion in your model. You are using a 20GHz ricker pulse, materials with a dielectric constant of up to 15, and a spatial discretisation of 0.01m. Take a look in the User Guide (http://docs.gprmax.com/en/latest/gprmodelling.html#spatial-discretisation) or a text on the FDTD method if you are not sure on what numerical dispersion is.

That said, the code should handle this error more elegantly/robustly, so I shall make some changes before the next release.

**Comment by wzhades** [comment]
@craig-warren Thank you very much for your kind help. I have corrected the error. Now I want to study the polarization information. I want to draw the fields in different polarization channels, such as xx, xy, yx and yy polarization. Then compare them. But I don't know how to add the polarization information to the source and how to draw the picture. Can you give me some advice on how to do? Thank you!
![polarization](https://user-images.githubusercontent.com/31717197/30240249-22481eb8-959f-11e7-96a3-1139640ba142.jpg)

**Comment by craig-warren** [comment]
@wzhades no problem, but please post your follow-up question in our Google Group (Forum) - http://www.gprmax.com/forum.shtml - which is intended for general questions about using the code and the FDTD method etc...

Craig

**Comment by wzhades** [comment]
@craig-warren Thank you and I will post my question in the forum.

**Comment by Nanas1** [comment]
How did you solve the problem about the Dispersion analysis error？
Could you explain it?

**Comment by craig-warren** [comment]
@Nanas1 see my answer above, and in the forum - http://www.gprmax.com/forum.shtml?place=msg%2Fgprmax%2Fv0r7DxiaZh4%2FLduPeiOGCQAJ

**Comment by craig-warren** [comment]
This now results in a warning that the waveform is most likely being undersampled and thus the numerical dispersion analysis cannot be carried out - https://github.com/gprMax/gprMax/commit/e486bb12be8e83de0bad69656229516e80a26df9
