### ISSUE TITLE
How to add the polarization to the model and how to draw the fields in different polarization models, such as xx,, xy, yx and yy

### ISSUE THREAD

**Issue by wzhades** [gprMax/gprMax#128]
I am studying the gpr, and  I want to study the polarization information. I want to draw the fields in different polarization models, such as xx, xy, yx and yy polarization. Then compare them. Just like what the picture shows. But I don't know how to add the polarization information to the source and how to draw the picture. Can someone give me some advice on how to do? 

![123](https://user-images.githubusercontent.com/31717197/30527702-1f8a93fc-9c5e-11e7-96ab-0c128ee0c170.jpg)

**Comment by craig-warren** [comment]
@wzhades This is not an issue with the code, but a question about using the software. Please post it in our Google Group (Forum) - http://www.gprmax.com/forum.shtml
