### ISSUE TITLE
How to set the wavy boundaries?

### ISSUE THREAD

**Issue by StruchkovAlex** [gprMax/gprMax#130]
How to set such a model? (see figure)
![simple1](https://user-images.githubusercontent.com/33108422/32039403-ea6a22ea-ba68-11e7-93f2-3d0af92b947e.png)

If I understand correctly, then the wavy boundaries of objects are specified using the hdf5 file and #geometry_objects_read command. Can you share a similar file? (I want to use it as a template.)

P.S. And one more question: where can I find a list of the relaxation times of popular materials?

**Comment by craig-warren** [comment]
@StruchkovAlex This is really a general question about using the software, and not an issue/bug with the code. Therefore, can you repost in our Google Group (Forum) which a more suitable place - http://www.gprmax.com/forum.shtml

Thanks.
