### ISSUE TITLE
Does parallel computing (GPU or CPUs) only accelerate the equation solver? 

### ISSUE THREAD

**Issue by zhoufeng617** [gprMax/gprMax#132]
I found that the geometry building always spends much time before the iterations. Even though I use GPU for gprMax running, the geometry building part will be time-consuming. I was wondering if the parallel computing is only for the solver while the rest parts adopt one-core computing. It seems that the models with more geometric units comsume much longer time even if they have the same simulation domain and cell sizes. For eample, my model contains multiphase fluid flow, which brings in hundreds of materials and geometric units due to the gradual transition of fluid saturation.

**Comment by agianno** [comment]
@zhoufeng617 GPU acceleration is only available for the FDTD solver. OpenMP multithreading is available for the FDTD solver. There are some Cythonised (C-based) functions used in model building to speed up the process but there is no real parallelisation in model-building yet and this is not really a priority at the moment. To speed up things in complex models try switching off the averaging process at material interfaces depending on your modelling scenario it might not be required as much.
