### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by arreyves** [gprMax/gprMax#136]
Hi,
I have been unable to open the output file from a test model. I keep on getting this error message below;
C:\Users\PhD_Student\Documents\GPR\bin\win32>write_dt1.exe modelD1.out
Reading GprMax2D #scan: file ...modelD1.out
ERROR: Input argument 'start_pos' is undefined.

Please advice how to read the output file either from console in windows 10 OS or MATLAB

**Comment by agianno** [comment]
@arreyves this is not a gprMax error. It is an error message from a conversion utility that we did not write and for the old version of the code that is not supported anymore. I will advise you to upgrade to the new gprMax version. In any case it appears that there are more arguments in your command that you are missing.
