### ISSUE TITLE
Problem when implement "$ conda env create -f conda_env.yml" in the Redhat 

### ISSUE THREAD

**Issue by zhoufeng617** [gprMax/gprMax#137]
I have met with this problems for times when I installed the gprMax packages in the redhat LINUX. The process is as:

Download and install Miniconda.                                   Successful.
$ conda update conda                                                   Successful.
$ conda install git                                                           Successful.
$ git clone https://github.com/gprMax/gprMax.git       Successful. 
$ cd gprMax                                                                   Successful.
$ conda env create -f conda_env.yml                             Broken as following

This phenomena occurs many time. I dont think the link is bad, but I was wondering if I can install the package manully. I can not understand the meaning of the script "conda_env.yml".  

 
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 
[cug520@localhost gprMax]$ conda env create -f conda_env.yml
Fetching package metadata ...........
Solving package specifications: .
intel-openmp-2 100% |################################| Time: 0:00:02 244.92 kB/s
libgfortran-ng 100% |################################| Time: 0:00:03 106.52 kB/s
gmp-6.1.2-h6c8 100% |################################| Time: 0:00:11  66.41 kB/s
icu-58.2-h9c2b 100% |################################| Time: 0:04:25  89.08 kB/s
jpeg-9b-h024ee 100% |################################| Time: 0:00:02 121.17 kB/s
libffi-3.2.1-h 100% |################################| Time: 0:00:00 122.78 kB/s
libsodium-1.0. 100% |################################| Time: 0:00:02 131.99 kB/s
libxcb-1.12-hc 100% |################################| Time: 0:00:03 144.23 kB/s
mkl-2018.0.1-h 100% |################################| Time: 0:27:15 118.38 kB/s
ncurses-6.0-h9 100% |################################| Time: 0:00:04 199.88 kB/s
pcre-8.41-hc27 100% |################################| Time: 0:00:01 170.04 kB/s
tk-8.6.7-hc745 100% |################################| Time: 0:00:13 253.45 kB/s
xz-5.2.3-h55aa 100% |################################| Time: 0:00:01 291.45 kB/s
zlib-1.2.11-ha 100% |################################| Time: 0:00:00 339.87 kB/s
glib-2.53.6-h5 100% |################################| Time: 0:00:50 174.30 kB/s
hdf5-1.10.1-h9 100% |################################| Time: 0:00:23 232.02 kB/s
libpng-1.6.32- 100% |################################| Time: 0:00:01 308.86 kB/s
libxml2-2.9.4- 100% |################################| Time: 0:00:10 199.94 kB/s
pandoc-1.19.2. 100% |################################| Time: 0:01:54 163.88 kB/s

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/main/linux-64/pandoc-1.19.2.1-hea2e7c5_1.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/main/linux-64/pandoc-1.19.2.1-hea2e7c5_1.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/main/linux-64/pandoc-1.19.2.1-hea2e7c5_1.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

[cug520@localhost gprMax]$ ^C
[cug520@localhost gprMax]$ ^C
[cug520@localhost gprMax]$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 26, in <module>**_

**Comment by craig-warren** [comment]
@zhoufeng617 you won't be able to proceed to build gprMax until you having a working Python environment with the correct packages. The `conda_env.yml` file specifies the Python packages that gprMax requires, and it works out all of the dependencies for each package. You shouldn't edit this file unless you understand what you are doing. The error you getting looks like some kind of connection issue when trying to retrieve some of the packages. Have you tried at different times/days? As it may be an intermittent issue. Otherwise you might try the suggestion in this thread - https://github.com/conda/conda/issues/4738 - which is to run `conda config --set ssl_verify no` before creating the environment.
