### ISSUE TITLE
If you're using `setuptools` in an unusual way (and you are), please make sure the normal use modes don't work.

### ISSUE THREAD

**Issue by fake-name** [gprMax/gprMax#14]
Basically, for 99.9% of the packages out there, `python3 setup.py install` is the appropriate procedure for installing a setuptools-based package.

However, for `gprMax`, this appears to result in a broken, partial install, and you instead have an unusual non-library based use-case built around `--inplace` and copying directories about into other projects.

That's fine, if odd, but if you're going to do that, it would be appropriate to make sure that `python3 setup.py install` does not work, or people used to normal python packages (like myself) will spend a fair bit of time wondering why they're getting weird import errors.

Ideally, `python3 setup.py install` should simply emit a "don't do that, use `--inplace`" error message, but frankly just crashing or throwing an error would be better then what there is now.

Alternatively, make `gprMax` a proper, installable library?

**Comment by craig-warren** [comment]
As gprMax uses Cython extensions, I am following the guidance in the Cython docs which recommends building the extensions in the same location as the source files using `python3 setup.py build_ext --inplace`

http://docs.cython.org/src/reference/compilation.html#compiling-with-distutils

No other (normal) `build` or `install` steps are required. 

I'll have a think if/how gprMax could be installed like a normal Python package.

**Comment by fake-name** [comment]
It doesn't necessarily need to be installable, just make it so the `python setup.py install` command doesn't produce a broken install. 

If that output a "you're doing it wrong, do `x` instead" message, it would be completely fine.

**Comment by craig-warren** [comment]
Modified `setup.py` to handle plain `build` or `install` command line options.

**Comment by fake-name** [comment]
Thanks!
