### ISSUE TITLE
Using "Geometry_objects_write" and "Geometry_objects_read" commands to build complicated gemetric models--an interesting experience 

### ISSUE THREAD

**Issue by zhoufeng617** [gprMax/gprMax#140]
**Project descriptions:**
My project is to establish a coupled EM and fluid model in a downhole environment with gprMax. To model the gradual fluid transition zone, I am using a serial of overlapped “cylinder” commands in gprMax input file. The expected geometry is as below: 
![1](https://user-images.githubusercontent.com/32971853/36902596-f16d78ee-1e22-11e8-936c-e397bb767bbd.png)

**Implementations:**
Considering the materials are homogeneous in the direction of well axis, I made a scheme to make a fast building of geometric structure in gprMax with “geometry_objects_write” and “geometry_objects_read” commands. The implementation procedure is as below:
(1) Establish a 2D gprMax model in cross section, including the command “#geometry_objects_write: 0 0 0 0.5100 0.1500 0.0010 Z1_t24h_Geo_Obj_2D”. Run the 2D model and export the 2D geometric model. 
(2) Establish 3 full 3D model with the commands below in the input file.  
“#python:
for i in range(1,700):
    print('#geometry_objects_read: 0 0 {} Z1_t24h_Geo_Obj_2D.h5 blank.txt'.format(i*0.0010))
#end_python: 
#geometry_objects_read: 0 0 0 Z1_t24h_Geo_Obj_2D.h5 Z1_t24h_Geo_Obj_2D_materials.txt” 
These commands are to import the 2D cross-section geometric model into each axial layer of the 3D model in a loop way. I expect this scheme can avoid plenty of cylinder buildings in the 3D model. 

**Results:**
A comparison of computing time between the above scheme and the conventional method, which uses a lot of “cylinder” commands in the input file, is shown as below:
 ![2](https://user-images.githubusercontent.com/32971853/36902597-f188cc52-1e22-11e8-9abe-b1bae28a744f.png)

**Conclusions:**
In a smoothing-on way, my scheme dos not show more advantages than the conventional method. However, in a smoothing-off running, my scheme is faster than conventional method. Actually, when running my method in a smoothing-on way, I observed a long time running in the phase of "Building main grid:", which should be the reason why it spends almost double time compared with the conventional method. 

**Problem and solution:**
Because I have a loop of importing the same 2D geometric slice into the 3D model, there is a conflict of the material definition---gprMax does not allow the materials to be defined repeatedly. However, you have to include the “_materials.txt” file in the “geometry_objects_read” commands. To avoid this problem, I used a blank txt file to take the place of the “_materials.txt” in the loop, while I place the complete “geometry_objects_read” command with substantial “_materials.txt” following the loop. Note the single “geometry_objects_read” with complete material file cannot work when it is placed in front of the loop. I do not know why, but it should be checked.

**Comment by craig-warren** [comment]
@zhoufeng617 interesting project. From reading through your tests I don't think there are any specific bugs, i.e. what you have observed is expected behaviour. I have a couple of comments though:

* The 'Building main grid' phase is where any dielectric smoothing will be carried out if it is turned on (which it is by default). Therefore I'm not surprised that a lot of time was spent here.
* The behaviour with material definitions and the '#geometry_objects_read' command is expected, and I think the method you used with a blank materials file is reasonable given how you are using the command.
* Can you explain further your comment 'the single “geometry_objects_read” with complete material file cannot work when it is placed in front of the loop. I do not know why, but it should be checked.'

Just to check, did you carry out these tests after I made changes to improve the speed of building cylinders that are aligned with an axis?

**Comment by zhoufeng617** [comment]
Firstly, I would like to test the running collapse caused by the location of the single “geometry_objects_read” command line with real material definitions. 
I use a simple model with only a few cylinders. The input script of 3D model is as below. This input script is specified to my project. For the general readers, please just focus on the red marked portions. 
*************************************************************************************************************************
#title: Borehole Radar Coupling Mud Invasion Simulations-2D 
#domain: 0.2710 0.1500 0.7000 
#dx_dy_dz: 0.0010 0.0010 0.0010 
#time_window: 2.000000e-08 
#geometry_view: 0 0 0 0.2710 0.1500 0.7000 0.0010 0.0010 0.0010 Mi_t12h n 
#material: 10.34 0.07 1.0 0 eps_10.34_sig_0.07 
#material: 5.76 0.29 1.0 0 eps_5.76_sig_0.29 
#material: 9.36 0.82 1.0 0 eps_9.36_sig_0.82 
#material: 57.50 1.44 1.0 0 eps_57.50_sig_1.44 
#material: 20.00 0.00 1.0 0 filler 
#waveform: ricker 1.0 1.000e+09 My_ricker 
#hertzian_dipole: z 0.1000 0.0750 0.5500 My_ricker 
#rx: 0.1000 0.0750 0.3500 
#rx: 0.2500 0.0750 0.5500 
#python:
for i in range(1,700):
    print('#geometry_objects_read: 0 0 {} Mi_t12h_Geo_Obj_2D.h5 blank.txt'.format(i*0.0010))
#end_python: 
#geometry_objects_read: 0 0 0 Mi_t12h_Geo_Obj_2D.h5 Mi_t12h_Geo_Obj_2D_materials.txt 
*** Drill collar 
#cylinder: 0.0000 0.0750 0.0000 0.0000 0.0750 0.7000 0.1000 pec 
*** Slots 
#cylindrical_sector: z 0.0000 0.0750 0.1250 0.1750 0.1000 331.0450 57.9100 filler n 
#box: 0.0000 0.0266 0.1250 0.0875 0.1234 0.1750 pec 
#cylindrical_sector: z 0.1000 0.0750 0.1250 0.1750 0.0500 104.4775 151.0450 filler n 
*** Slots 
#cylindrical_sector: z 0.0000 0.0750 0.3250 0.3750 0.1000 331.0450 57.9100 filler n 
#box: 0.0000 0.0266 0.3250 0.0875 0.1234 0.3750 pec 
#cylindrical_sector: z 0.1000 0.0750 0.3250 0.3750 0.0500 104.4775 151.0450 filler n 
*** Slots 
#cylindrical_sector: z 0.0000 0.0750 0.5250 0.5750 0.1000 331.0450 57.9100 filler n 
#box: 0.0000 0.0266 0.5250 0.0875 0.1234 0.5750 pec 
#cylindrical_sector: z 0.1000 0.0750 0.5250 0.5750 0.0500 104.4775 151.0450 filler n
************************************************************************************************************
I just use “geometry-only” for running. The simulation and geometry view are both fine. 

![2](https://user-images.githubusercontent.com/32971853/36986890-e83a1ee0-2092-11e8-83a6-e88d8fceafee.png)

Then, I place the #geometry_objects_read: 0 0 0 Mi_t12h_Geo_Obj_2D.h5 Mi_t12h_Geo_Obj_2D_materials.txt in front of the python loop. Please note, I only change the location of this command line, while do not change anything else. 
************************************************************************************* 
#title: Borehole Radar Coupling Mud Invasion Simulations-2D 
#domain: 0.2710 0.1500 0.7000 
#dx_dy_dz: 0.0010 0.0010 0.0010 
#time_window: 2.000000e-08 
#geometry_view: 0 0 0 0.2710 0.1500 0.7000 0.0010 0.0010 0.0010 Mi_t12h n 
#material: 10.34 0.07 1.0 0 eps_10.34_sig_0.07 
#material: 5.76 0.29 1.0 0 eps_5.76_sig_0.29 
#material: 9.36 0.82 1.0 0 eps_9.36_sig_0.82 
#material: 57.50 1.44 1.0 0 eps_57.50_sig_1.44 
#material: 20.00 0.00 1.0 0 filler 
#waveform: ricker 1.0 1.000e+09 My_ricker 
#hertzian_dipole: z 0.1000 0.0750 0.5500 My_ricker 
#rx: 0.1000 0.0750 0.3500 
#rx: 0.2500 0.0750 0.5500 
#geometry_objects_read: 0 0 0 Mi_t12h_Geo_Obj_2D.h5 Mi_t12h_Geo_Obj_2D_materials.txt 
#python:
for i in range(1,700):
    print('#geometry_objects_read: 0 0 {} Mi_t12h_Geo_Obj_2D.h5 blank.txt'.format(i*0.0010))
#end_python: 
*** Drill collar 
#cylinder: 0.0000 0.0750 0.0000 0.0000 0.0750 0.7000 0.1000 pec 
*** Slots 
#cylindrical_sector: z 0.0000 0.0750 0.1250 0.1750 0.1000 331.0450 57.9100 filler n 
#box: 0.0000 0.0266 0.1250 0.0875 0.1234 0.1750 pec 
#cylindrical_sector: z 0.1000 0.0750 0.1250 0.1750 0.0500 104.4775 151.0450 filler n 
*** Slots 
#cylindrical_sector: z 0.0000 0.0750 0.3250 0.3750 0.1000 331.0450 57.9100 filler n 
#box: 0.0000 0.0266 0.3250 0.0875 0.1234 0.3750 pec 
#cylindrical_sector: z 0.1000 0.0750 0.3250 0.3750 0.0500 104.4775 151.0450 filler n 
*** Slots 
#cylindrical_sector: z 0.0000 0.0750 0.5250 0.5750 0.1000 331.0450 57.9100 filler n 
#box: 0.0000 0.0266 0.5250 0.0875 0.1234 0.5750 pec 
#cylindrical_sector: z 0.1000 0.0750 0.5250 0.5750 0.0500 104.4775 151.0450 filler n
******************************************************************************************
I just use “geometry-only”. The running report shows the running is terminated, and the VIT file is not exported. Is it strange? 
 
![3](https://user-images.githubusercontent.com/32971853/36986904-f3859b94-2092-11e8-9fdb-d75444086f13.png)

By the way, I will say, with this method, the color in the exported geometry is different from the conventional method. It is because the material names imported from the “_material.txt” file are added with a postfix automatically, meaning they are different materials from the main input script, even though their EM properties are the same. gprMax colors the materials according to the order of the material definitions. However, it will not be a problem.

**Comment by craig-warren** [comment]
@zhoufeng617 I think what you are observing is expected behaviour. Let me explain why:

Each `#geometry_objects_read` command should have a data file (HDF5) and associated materials file that lists **all** of the materials contained in the data file. Internally, gprMax uses an integer (numeric ID) to identify each different material, which you can see in the printed table of materials. When you use the `#geometry_objects_read` command as intended each numeric ID in the data file is incremented by however many materials already exist in the model, i.e. already given `#material` commands.

You are circumventing this behaviour by using a blank materials file. This will work when you place another `#geometry_objects_read` command including your material definitions after your for loop, because there are no new materials defined inside the for loop - thus the number of existing materials stays the same. It will not work (as you have discovered) if your materials definition is before the for loop because you have changed the number of existing materials, and then you don't define materials inside the for loop that correspond to the data files.

**Comment by zhoufeng617** [comment]
Sorry, I still can not understand why I happen to succeed in using blank material file. 

In each h5 file, there are integral matrix. The position of each integer in the matrix stands for the material position in the simulation domain. The value of each integer represents the material EM property by corresponding to the order of the material definition in the .txt file. I suppose that gprMax implements commands in a sequential order. Then when "geometry_objects_read" command imports a blank materials.txt file, the integers in the h5 file do not know who it is. In other word, they can find their position but they do not their properties. 

I have suspected the material definitions out of the "geometry_objects_read", I refer to the material definitions in the front part of the input file, can support the success of the running, but I find it actually does not affect the running, after I increased the materials and removed the materials.

Supposing we have several "geometry_objects_read" commands with different materials, it could make sense that each "geometry_objects_read" implementation builds up a set of position distributions and materials corresponding. In every h5 file, the integer starts from zero, no matter whether the material file is changed or not. 

If the material ID corresponding is implemented after all the "geometry_objects_read" commands are completed, the scheme, in which no-blank material file is placed in front of the loop, seems more explainable. 

Sorry, I do not know if I have express myself clearly.

**Comment by craig-warren** [comment]
@zhoufeng617 you are partly correct in your understanding. 

In the data file (HDF5) for the `#geometry_objects_read` command there is a matrix which holds integers which are used to lookup material properties from a table. The position of the integers in the matrix define the geometry. The integers correspond to the order of materials in the given materials file. 

When the data and materials files are imported into the model, the software checks if there are already any existing materials, and increments all the integers in the data file by the number of existing materials. This ensures that when the new materials (from the materials file) are imported, and give numeric IDs after any existing materials, they correspond correctly to the integers in the data file. 

Hopefully this makes more sense. You can also see what is happening in the code by looking at the `input_cmds_geometry.py` module, lines 71-140.

**Comment by zhoufeng617** [comment]
I almost understand. 

I can explain it like this:

Although the "geo_obj_read" command imports the numeric values, starting from "0", from the h5 file and txt file, the numeric values are actually re-numbered in a global implementation, based on the existing material number. The integers from the h5 files（starting from 0）increase their values starting from the maximum of the number of the existing materials. In the same time, the material IDs have also increase in a global view. In this way, they form the one-to-one correspondence between the matrix positions and the material IDs. 

If I place the "geo_obj_read" with material txt prior to the "geo_obj_read" with blank, the IDs of the numeric values increase from the maximum value of the existing materials. However, when they want to match the correspondent IDs of the materials, they find nothing. 

If I place the "geo_obj_read" with material text behind the loop with blank txt, for the geo_read in each loop, the ID of the numeric values increments based on the material number existing before the loop. When implementing the geo_read with material txt, the material ID increases based on the existing material maximum (loop does do nothing actually). In this case, the IDs from h5 files can correspond to the materials. 

It is really difficult to clarify it in words, but I think I have understood.
