### ISSUE TITLE
Tests for the updated "Cylinder" command. 

### ISSUE THREAD

**Issue by zhoufeng617** [gprMax/gprMax#141]
The “cylinder” command has been updated for speeding up geometric model building. The following verifies the corrections and running time of this command in different axial directions. 

(A) alignments in X, Y and Z coordinate:
Input script:
**********************************
#title: Simulations-Cylinder
#domain: 0.3 0.4 0.5 
#dx_dy_dz: 0.003 0.003 0.003 
#time_window: 2.000000e-08 
#geometry_view: 0 0 0 0.3 0.4 0.5 0.003 0.003 0.003 ABC n 
#material: 10.34 0.07 1.0 0 a1
#material: 5.76 0.29 1.0 0 b1 
#material: 9.36 0.82 1.0 0 c1 
*Z alignment
#cylinder: 0.15 0.20 0.00 0.15 0.20 0.50 0.01 a1 n
*Y alignment 
#cylinder: 0.15 0.00 0.25 0.15 0.40 0.25 0.02 b1 n
*X alignment
#cylinder: 0.0 0.2 0.25 0.30 0.20 0.25 0.03 c1 n
*******************************************************
Geometry view shows that the command is correct in each orthogonal axis.

![1](https://user-images.githubusercontent.com/32971853/36999781-1dc3158c-20b9-11e8-9d81-f032fcf5b197.jpg)

(B) non-orthogonal cases
I set an inclined-cylinder model for testing. The input script is:
****************************************************************************
#title: Simulations-Cylinder
#domain: 0.3 0.4 0.5 
#dx_dy_dz: 0.003 0.003 0.003 
#time_window: 2.000000e-08 
#geometry_view: 0 0 0 0.3 0.4 0.5 0.003 0.003 0.003 ABC n 
#material: 10.34 0.07 1.0 0 a1
#material: 5.76 0.29 1.0 0 b1 
#material: 9.36 0.82 1.0 0 c1 
*non-orthogonal to Z 
#cylinder: 0.10 0.10 0.00 0.15 0.15 0.40 0.02 a1 n
*partially out of the domain with non-orthogonal to Y   
#cylinder: 0.00 0.00 0.00 0.05 0.4 0.15 0.04 b1 n
*observe the end face with non-orthogonal to X
#cylinder: 0.1 0.25 0.35 0.20 0.25 0.25 0.06 c1 n
******************************************************************************************
The geo-viewing of each part is as below, showing the corrections of updated command in any inclined angle and extension out of the domain.

![1 jpg](https://user-images.githubusercontent.com/32971853/36999914-900f0484-20b9-11e8-9d26-bab8bce85c63.png)

(C) testing the running time of the cylinder building in X, Y, and Z axes. The purpose is to see the parallelized speedup is valid in each orthogonal axis. To benchmark, we use a simulation domain of a cube with an equal length of 0.4 m in x, y, and z. The cylindrical radii are respectively 0.2, 0.18, 0.16, 0.14, 0.12, and 0.10 m with the cylindrical axis located in the center of the box face. I close the boundary condition settings. The basic input file is as below.  
*******************************************
#title: Simulations-Cylinder
#domain: 0.4 0.4 0.4 
#dx_dy_dz: 0.001 0.001 0.001 
#time_window: 2.000000e-08 
#geometry_view: 0 0 0 0.4 0.4 0.4 0.001 0.001 0.001 ABC n 
#pml_cells: 0
#material: 10 1 1 0 a
#material: 15 2 1 0 b 
#material: 19 2 1 0 c 
#material: 36 2 1 0 d 
#material: 29 2 4 0 e
#material: 16 2 1 0 f

*all cylinders in Z axis 
cylinder: 0.2 0.2 0 0.2 0.2 0.4 0.2 a n
cylinder: 0.2 0.2 0 0.2 0.2 0.4 0.18 b n
cylinder: 0.2 0.2 0 0.2 0.2 0.4 0.16 c n
cylinder: 0.2 0.2 0 0.2 0.2 0.4 0.14 d n
cylinder: 0.2 0.2 0 0.2 0.2 0.4 0.12 e n
cylinder: 0.2 0.2 0 0.2 0.2 0.4 0.10 f n

*all cylinders in Y axis
cylinder: 0.2 0.0 0.2 0.2 0.4 0.2 0.20 a n
cylinder: 0.2 0.0 0.2 0.2 0.4 0.2 0.18 b n
cylinder: 0.2 0.0 0.2 0.2 0.4 0.2 0.16 c n
cylinder: 0.2 0.0 0.2 0.2 0.4 0.2 0.14 d n
cylinder: 0.2 0.0 0.2 0.2 0.4 0.2 0.12 e n
cylinder: 0.2 0.0 0.2 0.2 0.4 0.2 0.10 f n

*all cylinders in X axis
cylinder: 0.0 0.2 0.2 0.4 0.2 0.2 0.20 a n
cylinder: 0.0 0.2 0.2 0.4 0.2 0.2 0.18 b n
cylinder: 0.0 0.2 0.2 0.4 0.2 0.2 0.16 c n
cylinder: 0.0 0.2 0.2 0.4 0.2 0.2 0.14 d n
cylinder: 0.0 0.2 0.2 0.4 0.2 0.2 0.12 e n
cylinder: 0.0 0.2 0.2 0.4 0.2 0.2 0.10 f n

*all cylinders in Z axis but inclined
#cylinder: 0.2 0.2 0 0.21 0.2 0.4 0.2 a n
#cylinder: 0.2 0.2 0 0.22 0.2 0.4 0.18 b n
#cylinder: 0.2 0.2 0 0.23 0.2 0.4 0.16 c n
#cylinder: 0.2 0.2 0 0.24 0.2 0.4 0.14 d n
#cylinder: 0.2 0.2 0 0.25 0.2 0.4 0.12 e n
#cylinder: 0.2 0.2 0 0.26 0.2 0.4 0.10 f n
*************************************************************
The recordings of the running time are:
Cylindrical axis in Z: 0:01:04
Cylindrical axis in Y: 0:01:15
Cylindrical axis in X: 0:01:42
The geometrical view is:

![1 jpg](https://user-images.githubusercontent.com/32971853/37000103-340d1396-20ba-11e8-9160-632ee8a04e79.png)

When I implement the inclined cylinder (as the last portion in the above input script), the running screen has a long-term pause (more than half an hour), as the screenshot below. After I decrease the cylindrical radii, it runs normally. I guess the inclined cylinder is not shared by the parallelization algorithm. 
 
![11](https://user-images.githubusercontent.com/32971853/37000176-77786428-20ba-11e8-8ce3-3680fb31224d.jpg)

Conclusions:
The updated “cylinder” command can implement correctly in each orthometric coordinate, as well as in inclined cylindrical axis. The improved code speeds up the cylindrical model building in each orthometric coordinate, while it seems invalid in an inclined cylinder. A larger cylinder will spend more building time.

**Comment by craig-warren** [comment]
@zhoufeng617 thanks for testing. This all sounds expected behaviour.
