### ISSUE TITLE
v2 input file syntax used with v.3.x

### ISSUE THREAD

**Issue by Mezgeenrasol** [gprMax/gprMax#143]
Hello Craig,

Hope you are doing well. I have the same problem of https://github.com/gprMax/gprMax/issues/115 ? when I run .in file it's not working giving the error the same as they had before, and I followed all the steps and trying to fix the problem but nothing change ( i am working with windows 10). Please help me in this issue, note that several days ago it was working properly but today I checked an example it's not running ( input file) by the way output file working properly;y and without any problems.

Thanks,
Mezgeen
![problem](https://user-images.githubusercontent.com/37024283/37259985-ac977fc0-2585-11e8-8511-c99f5461775e.PNG)

**Comment by craig-warren** [comment]
@Mezgeenrasol can you attach or copy the input file you are running to produce this error, and also tell us what the version number of gprMax is that you are running.

**Comment by Mezgeenrasol** [comment]
@craig-warren , actually I was using the same input file of GPRmaxV2 with V3 but I prefer to use GPRmaxV3 and here is the file. 
[sim_id_1.txt](https://github.com/gprMax/gprMax/files/1802579/sim_id_1.txt)

**Comment by craig-warren** [comment]
@Mezgeenrasol this file has the v.2 syntax, which has changed for v.3 so that is likely why it is not running. See the docs - http://docs.gprmax.com/en/latest/features.html#software-features

You can change the commands yourself, or use the helper tool - http://docs.gprmax.com/en/latest/utils.html#inputfile-old2new-py

**Comment by Mezgeenrasol** [comment]
@craig-warren Thank you Craig. This will solve after change syntax of V2 to V3, but why the original file of gprmax v3 (cylinder_Ascan_2D.in) is not running but the cylinder_Ascan_2D.out is running okay? 

could you help me to solve this problem? 

Regards 
Mezgeen

**Comment by craig-warren** [comment]
@Mezgeenrasol you are not running the original `cylinder_Ascan_2D.in` file, I guess you have modified it. I can see that from the screenshot of the error message as the spatial resolution is shown as 0.002m x 0.022m x 0.022m. It should be 0.002m x 0.002m x 0.002m. Download the original file, and it will work.

**Comment by craig-warren** [comment]
@Mezgeenrasol I would advise working through the examples in the documentation and doing some background reading on the FDTD method.

Kind regards,
Craig
