### ISSUE TITLE
Is it possible to use gprMax for micro-metre objects and micro-metre wavelength EM wave?

### ISSUE THREAD

**Issue by Tagussan** [gprMax/gprMax#144]
Hi.

I'm a student studying silicon photonics. I found gprMax project when looking for Open source FDTD simulator which can utilize GPU power. In my research field, objects are micrometre-sized and the wavelength of EM wave is also micrometre-sized. However, examples in the document of gprMax are metre-sized. Is it possible to use gprMax for this kind of micrometre-sized simulation?

Thank you

**Comment by agianno** [comment]
Hi

There is no limitation on size of cells. So, you can use gprMax in photonics by adjusting the cell size as you please. We do not work in photonics and that is the reason we do not  have relevant examples. gprMax is basically an FDTD solver. We have a users Google group if you want to post questions as this is for bug tracking.
