### ISSUE TITLE
GPRmaxV2: I would like to change synatx of input file 2D to 3D ? 

### ISSUE THREAD

**Issue by Mezgeenrasol** [gprMax/gprMax#145]
In this step, I understood how to work with gprmaxV2 for 2D. I tried with considering manual ? to change the syntax of the 2D to 3D as attached both input files. Therefore, the 2D file working but for 3D I have something wrong could you let me know what is wrong? I tried changing many things and didn't get the right one. 
![2d](https://user-images.githubusercontent.com/37024283/37363220-452ced32-26ef-11e8-805f-ded3a0e95f5c.PNG)
![3d](https://user-images.githubusercontent.com/37024283/37363221-45503346-26ef-11e8-8893-2dd1d13b6c0a.PNG)

**Comment by craig-warren** [comment]
@Mezgeenrasol this issue tracker is for reporting potential bugs and problems with the software. For general questions, such as yours, please use our Google Group (Forum) - http://www.gprmax.com/forum.shtml
