### ISSUE TITLE
Serious noise in the borehole radar model

### ISSUE THREAD

**Issue by borehole-question** [gprMax/gprMax#152]
Thanks for your contributions to GPR simulation.
I have built many borehole radar models with the gprMax, but all the results are contaminated by the serious noise. I don't think it is right. I don't know whether something wrong with my inputs or the gprMax is not suitable for the borehole radar model. I really can't find the reasons. The next is my input file and two trace of time wave. May be you can help me. Thank you very much.

#python:
from gprMax.input_cmd_funcs import *
#command('title', 'a long crack arround the borehole')
B_scan = True
#--------------domain & pml_cells
D_x = 4.0
D_y = 9.0
z_dim = 0.005
D_pml = 0.5
domain = domain(D_x + 2 * D_pml, D_y + 2 * D_pml, z_dim)
#pml_cells(20,20,0,20,20,0)
command('pml_cells',20,20,0,20,20,0)
#--------------resolution & time_window
resolution = 0.005
tsim = 128e-9
dx = dx_dy_dz(resolution, resolution, z_dim)
time_window(tsim)
#--------------material
material(permittivity=9, conductivity=1e-5,
         permeability=1, magconductivity=0,name='Limestone')
#--------------waveform
identifier = waveform('gaussiandot', amplitude=1, 
                      frequency=200e6,
                      identifier='my_gaussiandot')
#--------------transmitters & receivers & steps
if B_scan:
    y_ant = 0.5
else:
    y_ant = domain.y/2 # in the middle of the x-axis

tx = hertzian_dipole('y',
                     1.4, y_ant, 0, # minus 4 cm in y-direction
                     identifier)

command('rx_array', tx.x, y_ant, tx.z, tx.x, domain.y-0.4, tx.z, 0, 0.1, 0) # 10 cm step
if B_scan:
    src_steps(dx = 0, dy = 0.1, dz = 0)
#--------------Model
box(0, 0, 0,
    domain.x, domain.y, domain.z, 'Limestone')
borehole_dia = 0.2
b0, b1 = box(1.3, 0, 0,
             1.3+borehole_dia, domain.y, z_dim, 'free_space')
#crack
import math
import numpy
mig = 2.7   #Migration Value
thick = 20   #Crack width.grids 10cm
for j in numpy.arange(2.5,5.5,resolution ):
    com = 0.3*math.sin(2.5*j)
    rou = com/resolution
    bot_num = math.floor(rou) 
    box(bot_num * resolution + mig, j, 0, 
        bot_num * resolution + thick * resolution + mig,
        j + resolution, z_dim, 'free_space')

#--------------Outputs, geometry and snapshots
if current_model_run == 45:
    geometry_view(0, 0, 0,
                  domain.x, domain.y, domain.z,
                  dx.x, dx.y, dx.z,
                  'Borehole_5cmcrack200m', 'n')

N = 50
if current_model_run == 45:
    for i in range(1, N+1):
        snapshot(0, 0, 0,
                 domain.x, domain.y, domain.z,
                 dx.x, dx.y, dx.z, i*(tsim/N), 'snapshot' + str(i))
#end_python:
![image](https://user-images.githubusercontent.com/38339913/38716038-fa941250-3f21-11e8-9678-6095a178890e.png)

**Comment by craig-warren** [comment]
@borehole-question this is more of a general question about usage, and not a specific bug with the code. Can you please re-post your question in our Forum (Google Group) - http://www.gprmax.com/forum.shtml -, which is intended for discussing these more general issues.

Thanks.
