### ISSUE TITLE
Subgridding support?

### ISSUE THREAD

**Issue by mmjang** [gprMax/gprMax#153]
In this [article](ieeexplore.ieee.org/document/7996050/)[1], the authors mentioned that:

> Although this hypothesis cannot be validated at present due to limitations in computational resources, it is known that future releases of gprMax will incorporate the ability to define variable cell size within the same simulation [16]. This will allow for more accurate models to be created whilst reducing the burden on computational resources.

Is subgridding support for gprMax still on schedule? This will enable us to run simulations with precise antenna models in reasonably large geometry domain.

[1] J. Wilkinson and N. Davidson, "Comparing the measured and modelled response of bespoke antennas using gprMax," 2017 9th International Workshop on Advanced Ground Penetrating Radar (IWAGPR), Edinburgh, 2017, pp. 1-6.

**Comment by craig-warren** [comment]
@mmjang please read my recent response about sub-gridding in our Forum (Google Group) - http://www.gprmax.com/forum.shtml?place=msg%2Fgprmax%2FxSID_GtU3kg%2F-XQygzARAQAJ

**Comment by mmjang** [comment]
@craig-warren that's very exciting news, thanks for your information.
