### ISSUE TITLE
Axis-aligned cylinders appear to be too big

### ISSUE THREAD

**Issue by vvvverre** [gprMax/gprMax#154]
Thank you all for the work you have done on this project - it is a very useful simulator!

I believe I have found a bug in recent versions of gprMax. The bug appears when you try to create a cylinder which is aligned with an axis, in which case the cylinders appear to be bigger than requested. 
I think the code is adding additional length equal to the radius to the top and bottom of the cylinders. 

I have attached a minimum working example demonstrating this issue below. I would expect this snippet of code code to generate a wide but thin disk. Instead it generates a wide and tall cylinder with the code currently in the master branch. I was also getting this problem with version 3.1.3.
I have attached two images that illustrate the problem. 

**MWE:**
> #title: Minimum working example to cause a bug in generating an axis-aligned cylinder
> #domain: 0.500 0.500 0.250
> #dx_dy_dz: 0.002 0.002 0.002
> #time_window: 6e-9
> 
> #cylinder: 0.250 0.250 0.070 0.250 0.250 0.080 0.200 pec
>
>#geometry_view: 0 0 0 0.500 0.500 0.250 0.002 0.002 0.002 cylinder_mwe n

**Output from gprMax:**
![withbug](https://user-images.githubusercontent.com/5421677/38868030-a48f6444-423d-11e8-9373-bb548797d8f7.PNG)

**Expected output:**
![withoutbug](https://user-images.githubusercontent.com/5421677/38868031-a4a6eae2-423d-11e8-96a3-1608aad0454e.PNG)

I think the issue is caused by the function **build_cylinder** in [geometry_primitives_ext.py](https://github.com/gprMax/gprMax/blob/master/gprMax/geometry_primitives_ext.pyx#L754).
The bounding box calculation always adds a margin equal to the radius to the given coordinates, which means that the bounding box is too big along the axis of cylinder, if the cylinder is axis aligned. And in the case of axis-aligned cylinders the bounding box is reused to determine which cells should be filled along the cylinder's axis, making the cylinder too long. 

I have temporary fix in my fork: vvvverre/gprMax@68080cd, but there is probably a better fix for this issue.

**Comment by craig-warren** [comment]
@vvvverre thanks, that is an oversight when I implemented faster methods for creating axis aligned cylinders.
The specific problem is with the limits that are used along the cylinder axis. When a cylinder is aligned to an axis they should not have additional length applied (after the if statements). This is necessary when building the non-aligned versions. I'll get a fix out later this afternoon.

**Comment by craig-warren** [comment]
@vvvverre this should now be fixed in the master branch.
