### ISSUE TITLE
fatal error cannot open source file "gprmax/fields_updates_ext.c"

### ISSUE THREAD

**Issue by zackszack** [gprMax/gprMax#159]
Dear Sir:
Thanks for this excellect software! But when I using the command "python setup.py build(install)",it seems that the progress is not successful and will says" fatal error C1083: Cannot open source file: 'gprMax\fields_updates_ext.c': No such file or directory",however,I can find this file in the folder.
Thus,if I run the .in file in the user_models ,I will be told “ModuleNotFoundError: No module named 'gprMax.fields_updates_ext'”.
So,how can I solve this problem?I hope that you can tell me. Thank you very much.

**Comment by craig-warren** [comment]
@zackszack that is something we have not seen before. Can you firstly confirm that you followed the installation procedure exactly? For example, `python setup.py build`? Also can you confirm what machine and operating system you are using.

Kind regards,

Craig

**Comment by zackszack** [comment]
@craig-warren Thanks for your  kind advice! Though I don't know which step was wrong, I chose to reinstall the system with the help of the seller and then reinstall the program again. And this time all things seem good.
Thank you very much!

**Comment by rizkiac30** [comment]
I still have this problem, running Windows 10 x64 and I have followed the installation procedure exactly
Thank you!

**Comment by craig-warren** [comment]
@rizkiac30 please describe exactly the error you receive and the machine spec you are using.

Kind regards,

Craig

**Comment by rizkiac30** [comment]
here's the error log, including all of the installed packages in the environment
[gprmax error log.txt](https://github.com/gprMax/gprMax/files/4234855/gprmax.error.log.txt)

I'm using Windows 10 x64, i5-7200u, 8gigs of RAM, and NVIDIA 940MX for the graphics card

**Comment by craig-warren** [comment]
@rizkiac30 I just went through the installation procedure on a clean install of Windows 10 on VirtualBox with no issues. The only small difference I see from your error messages is that you have installed Anaconda for all users rather than Miniconda installed for a specific user (which is what we usually do). I don't know if this makes a difference, but it is all I can suggest at the moment.
