### ISSUE TITLE
vti

### ISSUE THREAD

**Issue by ELEGER** [gprMax/gprMax#16]
Good evening,
I've a question concerning the generation of vti files during B scans.
My input file contains a "#geometry_view:" command with a basename, let us say "basename".
While running B scan (let's say 10 traces) I'll have the generation of basename_1 to basename_10.
Which are all the same.
Is there a way to tell gprMax to not generate multiple ? 
Thanks a lot,
Best

e

**Comment by craig-warren** [comment]
Each A-scan (trace) that is part of the B-scan is considered a separate model. Thats why you get a geometry file for each trace. You can easily add some Python script to your input file so that only the first trace produces a geometry file, e.g.
```
#python:
if current_model_run == 1:
    print('#geometry_view: ...')
#end_python:
```

**Comment by ELEGER** [comment]
mmmm Clever!
Does not seem to do the trick though...
Thanks

e

**Comment by craig-warren** [comment]
It certainly worked when I tested it. Are you sure the other geometry files are not remaining from a previous simulation?

**Comment by ELEGER** [comment]
Yes I am,
I'll figure it out, must be my installation, it is not a big deal. The in file is in the number of boxes issue, if you want to have a look.
Best

e
