### ISSUE TITLE
Slow writing snapshots

### ISSUE THREAD

**Issue by denck007** [gprMax/gprMax#160]
I am running into major slowdowns then saving snapshots, like taking 10-100x longer to write the snapshot then to solve the iteration! Looking at the code we loop over the x,y,z values of the electic and magnetic values millions of times for a 0.2x0.2x0.2 box. Is there a reason this is not vectorized? I think I can get it to work and it should significantly speed up the process by vectorizing the code and only doing 1 write of the data. Is there any opposition to me submitting a change with this?

**Comment by craig-warren** [comment]
@denck007 Your timing is good! I am, at the moment, finalising code to speed up snapshot writing for CPU (similar to how we write the geometry views/files) as well as add snapshot writing for GPU. It is close to being ready, but needs some further testing. I am quite busy at the moment, so it will likely be a few weeks before it can be released.

**Comment by denck007** [comment]
See pull request #161

**Comment by craig-warren** [comment]
Should be improved in v.3.1.4 (https://github.com/gprMax/gprMax/tree/v.3.1.4)
