### ISSUE TITLE
pycuda/CUDA installation on Windows 10

### ISSUE THREAD

**Issue by craig-warren** [gprMax/gprMax#162]
Here is a set of instructions for getting CUDA and pycuda installed and running on Windows 10. It would be great to get feedback from other users (particularly from issue #115 ) so we can more formally publish the process in our docs.

1. Install Build Tools 2015

2. Install VS 2015 (community edition)

3. VS integration in CUDA installation: workaround (from nvidia devtalk forum):
    Step 1: Install the standard VGA driver:
        1. Bring up the Windows Device Manager. You can do that my right-clicking on the Start button and then select Device Manager.
        2. Expand the "Display Adapter" list, right-click on the GeForce card and then select "Update Driver Software".
        3. Click "Browse my computer for driver software".
        4. Then click the "Let me pick from a list of device drivers on my computer".
        5. Uncheck the "Show compatible hardware" option.
        6. Under the "Manufacture" scroll to the top and select the "(Standard display type)" and then click "Next". If you are running multiple GPUs then repeat steps 2 - 6 for each GPU.
        7. Restart Windows. This will basically load the standard VGA driver.

    Step 2: Delete all Cuda reference:
        1. In Windows Services, stop all nvidia services
        2. Delete all nvidia files from C:\ProgramData, C:\Program Files, C:\Program Files(x86). 
  
4. Run CUDA installation (worked for version 9.1)

5. Update graphics card driver via GeForce Experience.

6. Add environment variables to Windows, as follows

    6.1 run gprMax
    6.2 cd into gprMax main directory
    6.3 install pycuda: (gprmax) pip install pycuda
    6.4 cd into Program Files(x86)\Microsoft Visual Studio 14.0\Common7\Tools
    6.5 execute VsDevCmd, VsMSBuildCmd, vsvars32  (executing commands without .bat!)

**Comment by craig-warren** [comment]
The above instructions are courtesy of @Angelisd. @Meropi-Manataki I know you have also succeeded in getting pycuda/CUDA running on Windows 10, so if you have time to take a look and provide any comments that would be great.

**Comment by Meropi-Manataki** [comment]
Thank you for sharing this! I was completely unaware about steps 3 and 6. I will go through a new installation to see how it works on my pc (Windows 10x64, Nvidia gtx 970, Cuda 10, MVS community 2015) and let you know how it went, as it seems more robust compare to what I did. 

The installation steps I followed are pretty much the ones suggested in the gprMax documentation. I manage to make it work but there are still some issues. That includes:
1. Installation of Visual Studio Community 2015 with update 3 and Installation of Tools and Windows 10 SDK (through custom installation)
2. Installation of CUDA (version 10)
3. Restart system
4. Installation of PyCuda through command prompt or anaconda prompt (depends on choices made regarding adding Anaconda to path, during miniconda installation)
```
activate gprMax
pip install pycuda
```
5. To run a model using `-gpu` and without getting the PyCUDA error is to run the following commands 
```
cd C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
vcvarsall x86
```
and proceed with activating gprMax and run the model with `-gpu`. 

This is something I need to repeat every-time I am about to perform a simulation on a command prompt (or anaconda prompt) window. 

Fingers crossed, the proposed installation steps by you will resolve this.

**Comment by craig-warren** [comment]
https://blogs.msdn.microsoft.com/vcblog/2018/10/01/cuda-10-is-now-available-with-support-for-the-latest-visual-studio-2017-versions/

**Comment by craig-warren** [comment]
We have tested a simplified set of instructions for installing gprMax with GPU support - start with the standard installation instructions in the readme file and then proceed to the section on extra steps for GPU

* http://docs.gprmax.com/en/latest/include_readme.html#installation
* http://docs.gprmax.com/en/latest/gpu.html
