### ISSUE TITLE
distributed memory usage on a cluster

### ISSUE THREAD

**Issue by teselor** [gprMax/gprMax#164]
Hi, I am trying to run a 3d gprMax through-wall radar imaging simulation with an EM human model standing certain distance from the concrete wall. The estimated memory usage is about 395GB for this model. I tried to run this model on a cluster with 12 nodes using Slurm, in which each nodes have 128GB memory. However, I never ran through it. 

I learned from the following thread that the present available gprMax version don't allow combing memories from several nodes. 
https://groups.google.com/forum/#!topic/gprmax/kCevtSc7Was

But, in this Master thesis I found online, Distributed Memory Ground Penetrating Radar Simulations, https://static.epcc.ed.ac.uk/dissertations/hpc-msc/2016-2017/Callum_Fenna-Roberts-gprThesis_callum_fenna-roberts.pdf

It seems to be that sharing memory is possible. As appendix A illustrated, the only thing one need to do is to overwrite the following files with the distributed memory copies:
gprMax/model_build_run.py
gprMax/gprMax.py

Here is my question:
1. Which threads should I follow? Is distributed memory possible on a cluster?
2. If it is possible. Could I get a distributed memory copies of two specific files to test run my model?
Thank you very much.

**Comment by craig-warren** [comment]
@teselor the short answer is that it is not yet possible to run gprMax with distributed memory. 

A MPI-based domain decomposition is something we have been considering but have not had the resources to dedicate to yet. The masters thesis you found was from a University of Edinburgh student who started the process of creating a MPI version of gprMax. However, you'll see there were some issues, and some of the key features of the software were turned off, i.e. the PMLs. So you cannot simply replace the modules you mentioned.

There is a PhD student (@jasminium ) from the University of Edinburgh who is working on sub-gridding as part of his research. This allows you to have certain areas of the FDTD grid at a fine spatial resolution (for modelling fine details or high dielectrics) and the remainder of the grid at a course resolution. This may help you to reduce the memory footprint of your model. However, this code won't be released into the public version of gprMax until the thesis is completed.

Kind regards,

Craig

**Comment by teselor** [comment]
Thank you for your detailed response. I do appreciate it a lot and I will follow @jasminium's  work.

Actually, I think I have some progress on this distributed memory thing but still with some confusion.

I tried to use cluster to run the same model with reduced size during the past weekend.

I increased the discretization step to 0.002, which comes with an estimated memory of about 198GB.
#domain: 3.00 3.00 2.50
#dx_dy_dz: 0.002 0.002 0.002

Then,  I tried to run the simulation on the same cluster using 10 nodes with the main batch file scripts as shown below
#SBATCH --time=72:00:00                    
#SBATCH --nodes=10                            
#SBATCH --ntasks-per-node=16          
#SBATCH --mem=50G     

### run gprMax
python3 -m gprMax 9Ts_16Rs_Curvilinear.in -n 9 -mpi 10

in which, the input file is a 3d through-wall radar imaging model with 9-transmitters and 16-receivers MIMO array spanning a 2d topology. I use python scripting (accompanied with current_model_run command) to switch between different transmitters in difference B scans.

The model is running now on the cluster, which, in my opinion, distributed memory is realized in this way.

However,  If I don't use MPI and B scan, the cluster yields out-of-memory error information.
 ### run gprMax
python3 -m gprMax 9T_16Rs_Curvilinear.in

where the input file just has 1-transmitter and 16-receivers. Enumerating among 9 transmitters to gather scattered field in this approach.

I am now kind of confused with those two approaches. Could you please help to figure out where the problem is? Thank you very much.

Best regards,
Qiang An

**Comment by craig-warren** [comment]
@teselor our current MPI is for task farming models only, bottom line **there is no distributed memory currently possible**. So both of the approaches you tried require the same amount of memory - I suspect the memory estimate is over conservative, so probably the required memory is very close to the limit per node on your cluster. Certainly using the `-n` or `-mpi` should make no difference to the memory requirement.

**Comment by teselor** [comment]
Thanks for your quick response. You're right. The memory is not distributed. I just checked the job status and found it was stuck at the head node. The only explanation for this is out-of-memory. 
By the way, I just wonder do you have any plan to implement a distributed memory version of gprMax and what's the main difficulty in implementing one?
In my opinion, it would not only make the simulation of large complex GPR/TWRI simulation models possible but also speed up the simulation process using distributed cpu resources.

**Comment by craig-warren** [comment]
@teselor it is certainly on our wish list of things to do, and is not technically too difficult, but as with many things we need time and resource. This generally means we need a project that we could do the MPI decomposition as a part of. It would certainly enable larger simulations that require more memory, but you are still limited to the CPU resources per node that are solving that part of the model.
