### ISSUE TITLE
Trouble with setup.py build

### ISSUE THREAD

**Issue by mr-perry** [gprMax/gprMax#165]
Hello,
  I've been trying to install gprMax, but keep running into the following error.

FATAL:/opt/local/bin/../libexec/as/x86_64/as: I don't understand 'm' flag!
error: command 'gcc-8' failed with exit status 1

I am running macOS High Sierra 10.13.6. Please let me know if you need additional information.

Thank you.

**Comment by craig-warren** [comment]
@mr-perry so you are running `python setup.py build` and getting that error?

**Comment by mr-perry** [comment]
Yes.

**Comment by craig-warren** [comment]
Is the gprMax environment definitely active, when you run this command?

**Comment by mr-perry** [comment]
It is definitely active.
Cerberus-3:gprMax mperry$ source activate gprMax
(gprMax) Cerberus-3:gprMax mperry$ python setup.py build
Running 'build_ext --inplace'
running build_ext
building 'gprMax.pml_updates_ext' extension
gcc-8 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/mperry/miniconda3/envs/gprMax/include -arch x86_64 -I/Users/mperry/miniconda3/envs/gprMax/include -arch x86_64 -I/Users/mperry/miniconda3/envs/gprMax/lib/python3.6/site-packages/numpy/core/include -I/Users/mperry/miniconda3/envs/gprMax/lib/python3.6/site-packages/numpy/core/include -I/Users/mperry/miniconda3/envs/gprMax/include/python3.6m -c gprMax/pml_updates_ext.c -o build/temp.macosx-10.7-x86_64-3.6/gprMax/pml_updates_ext.o -O3 -w -fopenmp -march=native
FATAL:/opt/local/bin/../libexec/as/x86_64/as: I don't understand 'm' flag!
error: command 'gcc-8' failed with exit status 1

**Comment by craig-warren** [comment]
I think on your machine the path to the assembler `as` is not correct. It should be in `/usr/bin`. You can check by running `which as`. If it is not from `/usr/bin` then I think you need to add it to your path.

**Comment by mr-perry** [comment]
That worked! Thank you!
