### ISSUE TITLE
set_rigid_E, set_rigid_H

### ISSUE THREAD

**Issue by jasminium** [gprMax/gprMax#166]
Hello,

We use set_rigid_E and set_rigid_H to prevent material averaging for dielectrics in commands like build_box. In build_box the setters only set the i, j, k E and H components.

```python
for i in range(xs, xf):
    for j in range(ys, yf):
        for k in range(zs, zf):
            solid[i, j, k] = numID
            set_rigid_E(i, j, k, rigidE)
            set_rigid_H(i, j, k, rigidH)
```

Do we also need to set for instance Hx at xf + 1, j, k to rigid to prevent smoothing on the far yz face of the box? Is this handled by the solid array or am I missing something?

Cheers

**Comment by craig-warren** [comment]
Hey @jasminium I had a check through this and I think we are setting the rigid array correctly in the case of preventing dielectric smoothing. 

When `set_rigid_E(i, j, k, rigidE)` is called it sets (to `True`) all 12 vertices of the Yee cell. So even although the loop only runs up to e.g. `xf - 1`, the final face is being set in the rigid array.

Hope this makes sense.
