### ISSUE TITLE
Limitation on the number of boxes?

### ISSUE THREAD

**Issue by ELEGER** [gprMax/gprMax#17]
Hi again,
I'm trying to model boxes with a sinusoidale interface.
So I just wrote a script where I assign each cells a values, it gives about 60K boxes ( I tried with plates as well).
However I don't see any reflection on my surface. could you help me to understand why ?

An extract of the .in file:

"
#material: 10.000000 0.0 1.0 0.0 orga
#material: 5.000000 0.0 1.0 0.0 sand
#material: 20.000000 0.0 1.0 0.0 gravel
#material: 3.000000 0.0 1.0 0.0 ice

#waveform: ricker 1 5.000000e+08 my_ricker
#hertzian_dipole: z 0.250000 2.000000 0 my_ricker
#rx: 0.250000 2.000000 0
#src_steps: 1.000000 0.000000 0
#rx_steps: 1.000000 0.000000 0

#box: 0.000000 0.000000 0 3.000000 2.000000 0.005000 sand
#plate:0.000000 0.995000 0.005000 0.005000 1.000000 0.005000 orga
#plate:0.000000 1.000000 0.005000 0.005000 1.005000 0.005000 orga
#plate:0.000000 1.005000 0.005000 0.005000 1.010000 0.005000 orga
"

Thanks

best

e

**Comment by craig-warren** [comment]
Would need to see a more complete input file to understand exactly what is going on. It looks like you are using a 2D simulation, so you can't use a plate, you have to use boxes. The 2D is like a single cell slice of the 3D.

**Comment by agianno** [comment]
You should check the geometry of what you have generated as a first check. Then check that your source and receiver is at a place that makes sense and that the time window is adequately long for capturing all reflected waves.

**Comment by ELEGER** [comment]
@ both of you,
Thanks, fine I'll use box, but the problem seems to be still here.
I do not even see my funny boxes on the .vti file, through paraview.

@antonis, I'm ok with the Time window and the depth of the stuff.
@Craig, Even with boxes, it doesn't seem to like it. I tried to add the file, but seems too heavy:

"
#domain: 3.000000 3.000000 0.005000
#dx_dy_dz: 0.005000 0.005000 0.005000
#time_window: 0.000000030
#time_step_limit_type: 2D
#pml_cells: 10 10 0 10 10 0
#python:if current_model_run == 1:
print('#geometry_view: 0 0 0 3.000000 3.000000 0.005000 0.005000 0.005000 0.005000 fractal n') 
#end_python:

#num_threads: 4
#material: 10.000000 0.0 1.0 0.0 orga
#material: 5.000000 0.0 1.0 0.0 sand
#material: 20.000000 0.0 1.0 0.0 gravel
#material: 3.000000 0.0 1.0 0.0 ice

#waveform: ricker 1 5.000000e+08 my_ricker
#hertzian_dipole: z 0.250000 2.000000 0 my_ricker
#rx: 0.250000 2.000000 0
#src_steps: 1.000000 0.000000 0
#rx_steps: 1.000000 0.000000 0

#box: 0.000000 0.000000 0 3.000000 2.000000 0.005000 sand
#box:0.000000 0.995000 0.000000 0.005000 1.000000 0.005000 orga
#box:0.000000 1.000000 0.000000 0.005000 1.005000 0.005000 orga
#box:0.000000 1.005000 0.000000 0.005000 1.010000 0.005000 orga
#box:0.000000 1.010000 0.000000 0.005000 1.015000 0.005000 orga
#box:0.000000 1.015000 0.000000 0.005000 1.020000 0.005000 orga
#box:0.000000 1.020000 0.000000 0.005000 1.025000 0.005000 orga
#box:0.000000 1.025000 0.000000 0.005000 1.030000 0.005000 orga
#box:0.000000 1.030000 0.000000 0.005000 1.035000 0.005000 orga
#box:0.000000 1.035000 0.000000 0.005000 1.040000 0.005000 orga
[....]
"

Sorry if do not see where I'm wrong

**Comment by ELEGER** [comment]
Let it dropped,
Found it. Antonis were right... as usual. My fault.
Everything works right by the way even the vti dysplays very well (after my graphical card was able to display)
My bad.


e

**Comment by agianno** [comment]
Good to know that it works ;-)
