### ISSUE TITLE
Source: excitation_file/Built-in waveforms

### ISSUE THREAD

**Issue by AlinaYLN** [gprMax/gprMax#170]
I would like to ask if I can specify the excitation source using my own functions , just like the built-in waveforms,  instead of specifying an ASCII file that contains columns of amplitude values. If possible, where should I write code to create my own excitation source. Thank you for reading and guiding.

**Comment by craig-warren** [comment]
@AlinaYLN what type of waveform are you considering? Any specific reasons for not using the excitation file option? Our built-in waveforms are defined in the `waveforms.py` module within the gprMax package.

**Comment by AlinaYLN** [comment]
Thank you very much for reading and replying. Here I need a wide coded pulse, a linear frequency modulation signal with an envelope.

**Comment by springliu** [comment]
![image](https://user-images.githubusercontent.com/9677588/45292278-4e7d8100-b527-11e8-9a0a-762273930dc5.png)

**Comment by craig-warren** [comment]
@springliu the error you are receiving is as described `ValueError: A value in x_new is below the interpolation range`, i.e. the value for your waveform at the time step required by the model is outside the interpolation range. 

You can provide optional arguments to the excitation file command to specify the kind and fill_value to be passed to the interpolation function (https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html), e.g. `#excitation_file: GeiLei_Waves4.txt linear extrapolate`. This should resolve you problem, but I advise plotting the results of the extrapolation to check.

**Comment by springliu** [comment]
@craig-warren thanks for your attention and the advises. using the linear extrapolate can solve the problem, however the result of the waveform is wrong.
![image](https://user-images.githubusercontent.com/9677588/45403432-d92bc080-b68c-11e8-85ff-193c5b36025f.png)
the result of the gprMax  is shown in up. and it should be like this: 
![image](https://user-images.githubusercontent.com/9677588/45403501-4d666400-b68d-11e8-8283-a67aa32c1650.png)

**Comment by AlinaYLN** [comment]
@springliu. Maybe you can try other interpolation kind in addition to linear to find the best one. And I think it is almost impossible to get the perfect result you have shown if you don't implement your own built-in waveform within the waveform.py package. After all, in my understanding，there is a certain error in using interpolation to get a waveform.

**Comment by springliu** [comment]
@AlinaYLN   I think you are right. I also think there are some errors in the #excitation_file. I have try to not use time vector, the extra amplitude values, the less amplitude values, as you can see, I didn't get the right result.

**Comment by craig-warren** [comment]
@springliu can you explain what response you are expecting? I don't think you are having issues with the excitation file. You are propagating your waveform which you show above in blue (from the GeiLei_Waves4.txt file with name GeiLeiA) via a Hertzian dipole source in free-space. This is the input file:

```
#domain: 2.6 5 3
#dx_dy_dz: 0.008 0.008 0.008
#time_window: 45e-9
#excitation_file: GeiLei_Waves4.txt
#hertzian_dipole: x 1.3 1.6 1.5 GeiLeiA
#rx: 1.44 1.6 1.5
#cylinder: 1.37 4.1 0.1 1.37 4.1 1.75 0.15 pec
#geometry_view: 0 0 0 2.6 5 3 0.008 0.008 0.008 NoWall_Effect_1 n
```

Some further questions/observations:

* You have a x-polarised Hertzian dipole but your cylinder is orientated with long axis in the z-direction. Is this intended?
* Your waveform does not start or end smoothly and contains a sharp change of direction (after ~900 iterations). This will potentially create unwanted high-frequencies in the FDTD simulation.
* The time step in your waveform is different from the simulation: 3.33e-12 seconds versus 1.54e-11 seconds
* You have less samples in your waveform than the simulation: 1200 versus 2922

I suspect you need to resolve these issues.

Kind regards,

Craig

**Comment by springliu** [comment]
@craig-warren I am very guilty for that I acn response to your comment until this moment. Thank you very much for your attention.  I need a ultra-wide band waveforms: pseudo-random coded signal, like the blue line below.
![image](https://user-images.githubusercontent.com/9677588/45657925-fa722e00-bb1e-11e8-9216-6c8fcf2fdd2a.png)
- The cylinder orientated in z-direction is my requirment. What's more, I comment out it for testting the signal generation.
- The waveform is sure contain much high-frequecies, but it is exactly what I need. 
- In the userguide of gprMax, it show that: 

> If there are less amplitude values than the number of iterations that are going to be performed, the end of the sequence of amplitude values will be padded with zero values up to the number of iterations. If extra amplitude values are specified than needed then they are ignored.
In actually, I have test the different length of the waveform: less, more, or equal. I don't have the right waveforms what I want.

- Another thing I want to know is that whether the step of my waveform must be equal to the simulation.

**Comment by springliu** [comment]
@craig-warren I am very guilty for that I acn response to your comment until this moment. Thank you very much for your attention.  I need a ultra-wide band waveforms: pseudo-random coded signal, like the blue line below.
![image](https://user-images.githubusercontent.com/9677588/45657925-fa722e00-bb1e-11e8-9216-6c8fcf2fdd2a.png)
- The cylinder orientated in z-direction is my requirment. What's more, I comment out it for testting the signal generation.
- The waveform is sure contain much high-frequecies, but it is exactly what I need. 
- In the userguide of gprMax, it show that: 

> If there are less amplitude values than the number of iterations that are going to be performed, the end of the sequence of amplitude values will be padded with zero values up to the number of iterations. If extra amplitude values are specified than needed then they are ignored.
In actually, I have test the different length of the waveform: less, more, or equal. I don't have the right waveforms what I want.

- Another thing I want to know is that whether the step of my waveform must be equal to the simulation.

**Comment by springliu** [comment]
`#title: Test_GeiLeiCode
#domain: 1.0 0.5 0.5
#dx_dy_dz: 0.002 0.002 0.002
#time_window: 45e-9
#waveform: sine 7 1e9 my_sine
#hertzian_dipole: x 0.5 0.25 0.25 my_sine
#rx: 0.7 0.25 0.25`

![image](https://user-images.githubusercontent.com/9677588/45664034-58f9d500-bb3c-11e8-8b8f-a3f5e5b0ef04.png)

**Comment by springliu** [comment]
In the last picture show, the waveform is the build-in sine wave and free domin. There are no objects in the domin. why the received signal is not the standard sine signal? Do you mean that the sine wave build-in is also not start and end smoothly, and therefore it introduce the high-frequencies?
