### ISSUE TITLE
Windows cl.exe error with "python setup.py build"

### ISSUE THREAD

**Issue by SyedFaisalGardezi** [gprMax/gprMax#174]
i am unable to run cl.exe even i have added it to path manually as well. Can anyone help me to solve this issue.
[error logs gprmax.txt](https://github.com/gprMax/gprMax/files/2534419/error.logs.gprmax.txt)

**Comment by craig-warren** [comment]
@Meropi-Manataki @Angelisd any thoughts?

**Comment by Meropi-Manataki** [comment]
Hi there,

I had the same problem as you @SyedFaisalGardezi regarding adding the cl.exe on path. I only have a workaround to suggest, since I have not found a "proper" solution yet. You can found the corresponding thread and the related comment here: https://github.com/gprMax/gprMax/issues/115#issuecomment-334289867

So I recommend you to try this: open a command prompt window and ran vcvarsall.bat while you have your path on VC root installation folder. On my system is:
```
cd C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
vcvarsall x86
```
Then proceed with activate gprMax environment. If the missing cl.exe from path is your problem this should fix it for you. If not, please report back here to look at it more thoroughly. I will help any way i can.

@craig-warren and @Angelisd if you have any update or a proper fix on that issue I'm very interesting to hear!

Kind regards to all,
Meropi

**Comment by Angelisd** [comment]
I 've never experienced any problems with the cl.exe. Adding the paths manually (see below) worked every time for me.

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe

**Comment by SyedFaisalGardezi** [comment]
![image](https://user-images.githubusercontent.com/43716662/47894128-0a11c000-de9c-11e8-993d-76661de478cb.png)
facing same error. even i have tried to run cl.exe directly from the location still its showing same error.

**Comment by craig-warren** [comment]
@SyedFaisalGardezi it looks like a specific issue with your installation of Microsoft Visual C++ 2015 Build Tools, rather than a gprMax specific problem. I would recommend you try to remove and reinstall and then follow the above advice again.

**Comment by SyedFaisalGardezi** [comment]
![image](https://user-images.githubusercontent.com/43716662/47959876-d5337380-e029-11e8-809f-48bf6457639c.png)
thanks guys for your support but still facing the issue. 
i have uninstalled VS and miniconda as well and started from zero again but its showing error. i am using 64 bit windows 8.1.

**Comment by SyedFaisalGardezi** [comment]
@Meropi-Manataki i am using MVS 2015. previously i was default options for its installation. now i did custom installaion as well and included windows 8.1 SDK as i am using windows 8.1 but facing same error.

**Comment by Meropi-Manataki** [comment]
Hi,

I'm trying to understand what might be the cause of your problem. So I have a few questions. 

What version of MVS are you using? Did you use the installation's default settings? 

In windows 10 and with MVS 2015 community I was receiving the error below during gprMax installation, and while executing the `python setup.py build `command as well.
```
building 'gprMax.fields_updates_ext' extension
error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Windows Kits\\10\\lib'
```
It was resolved when I installed the package Tool and Windows 10 SDK, that can be found under the custom installation options of MVS community 2015. Maybe is something similar for windows 8.1?

Kind regards

**Comment by SyedFaisalGardezi** [comment]
still facing the same issue

**Comment by Meropi-Manataki** [comment]
I'm sorry to hear that. I believe your issue is related with MVS installation, but for the moment I do not any other suggestion to propose. I Will look further through it and hopefully I will return with something to suggest soon. 

Good luck in the meantime!

**Comment by SyedFaisalGardezi** [comment]
thanks. I am also trying to do one more time from zero.

**Comment by SyedFaisalGardezi** [comment]
Just FYI... I had tried with windows 7 and its working now.:-)
