### ISSUE TITLE
plot_Bscan.m

### ISSUE THREAD

**Issue by efferre99** [gprMax/gprMax#178]
Hi! I would like to modify the script plot_Bscan.m in orden to obtain an homogeneous curve. In order to do that, I would replace the function pcolor in place of imagesc. The problem is that the variables have different sizes:
- field: 2121x40
- traces: 1x41
- time: 2121x1
So, I can't resize the above variables. Do you know any other methods to do that?

**Comment by jasminium** [comment]
Hi @efferre99 The issue tracker is reserved for problems that users experience with the code as it is provided and to suggest changes which improve the code in general.

For specific changes such as plotting scripts etc... please go to http://www.gprmax.com/forum.shtml
