### ISSUE TITLE
How can I use SFCW signal in the simulation?

### ISSUE THREAD

**Issue by freezerdragon** [gprMax/gprMax#180]
I am creating my SFCW signal as follow in MATLAB:

```
c = 3e8;
delf = 80;% MHz
f  = 1e6*(800:delf:1600);
dr = c/(2*range(f))
R  = dr*5 % range
t_delay = 2*R/c % delay

PRI = 1.0*t_delay;

t_dwell = PRI
N  = length(f) % # of frequency steps
fs = 10*max(f) % sampling frequency
dt = 1/fs % sampling time
Ns = floor((t_dwell/dt)+1) % number of sample per frequency
t1 = linspace(0,t_dwell*N,N);

L = N*Ns % length of arrays

Rmax = dr*N
r = 0:dr:dr*(N-1);
rend = r(end)



%%
ff = [];
for i = 1:N
   ff = [ff f(i)*ones(1,int32(Ns))];
end
t2 = linspace(0,t_dwell*N,N*Ns);

% 
Tx = 1*exp(-j*2*pi*ff.*t2);
figure
plot(t2,real(Tx))
```

Whose zoomed-in output is like this one;

![zoomed_sig](https://user-images.githubusercontent.com/5116292/49328806-5e858980-f587-11e8-9504-96d8594cd75c.JPG)

And the result I get from the input file of:

```
#python:
from gprMax.input_cmd_funcs import *
command('title', 'Simple Source Sink')

z_dim = 2e-3
resolution = 2e-3
tsim = 1.3e-07
B_scan = False

#commands
domain = domain(x=64e-2, y=30e-2, z=z_dim)
dx = dx_dy_dz(resolution, resolution, z_dim)
time_window(tsim)

material(permittivity=6, conductivity=0, permeability=1, magconductivity=0, name='half_space')

excitation_file('exitfile.txt')

if B_scan:
    x_ant = 8e-2
else:
    x_ant = domain.x/2 - 1e-2 # in the middle of the x-axis


tx = hertzian_dipole('z', x_ant, domain.y - 4e-2, 0, 'sfcw')
rx(tx.x, tx.y - 10e-2, tx.z)

if B_scan:
    src_steps(dx=0.8e-2/4)
    rx_steps(dx=0.8e-2/4)

geometry_view(0,0,0,domain.x,domain.y,domain.z, dx.x,dx.y,dx.z,'simple','n')

#end_python:
```
Output:
![sig_out](https://user-images.githubusercontent.com/5116292/49328840-ea97b100-f587-11e8-97b2-5b0d6fa5d9b8.JPG)

Zoomed:
![zoomed_sig_out](https://user-images.githubusercontent.com/5116292/49328845-f4b9af80-f587-11e8-9b78-9a18fd366f16.JPG)

I don't know how can I get the signal shape smooth and as close as I desired. It seems it is kind of noisy and some peaks in some parts.

**Comment by agianno** [comment]
@freezerdragon We have a google group for discussing issues, like this one, concerning the use of gprMax (https://groups.google.com/d/forum/gprmax) What you get is not a bug. FDTD excitations need to be smooth (e.g. if they are CW need to be slowly ramped) as otherwise, they introduce high frequency noise in the simulation. There are ways to do what you want more efficiently but this is not the right forum to discuss the process.

**Comment by freezerdragon** [comment]
Thanks. I wasn't aware that forum difference. Will post the further questions.
