### ISSUE TITLE
Can gprMax opperate on the pycharm?

### ISSUE THREAD

**Issue by zzzhxb** [gprMax/gprMax#181]
I have install the gprMax on the anaconda prompt, but I would like run the code in the Pycharm. Is there anybody who have succeeded on the Pycharm?

**Comment by craig-warren** [comment]
@zzzhxb this issue tracker is for reporting specific bugs/problems with the code. Please post your question in our Forum (Google Group) - http://www.gprmax.com/forum.shtml
