### ISSUE TITLE
Is there some relations between traces (after ’n‘) and dx or rx?

### ISSUE THREAD

**Issue by zzzhxb** [gprMax/gprMax#183]
Hi Craig,

When I run a model, I find the trace can not te enlaged sometimes, e.g. python -m gprMax user_models/XXXXX.in -n **100**. But when I replace 100 by 150, it says "run out of range..."
Is there some relations between taces and rx or dx?

regards,
Xuebing

**Comment by craig-warren** [comment]
@zzzhxb please read the documentation and examples - http://docs.gprmax.com/en/latest/examples_simple_2D.html#b-scan-from-a-metal-cylinder

The '-n' argument specifies how many times the model will be run. If using the #src_steps and/or #rx_steps command(s) then your simple sources and receivers will move 'n' multiplied by the step size in whatever direction. You must ensure your domain is large enough to allow this. If it is not you will get the error message you receive.

**Comment by zzzhxb** [comment]
> @zzzhxb please read the documentation and examples - http://docs.gprmax.com/en/latest/examples_simple_2D.html#b-scan-from-a-metal-cylinder
> 
> The `-n` argument specifies how many times the model will be run. If using the `#src_steps` and/or `#rx_steps` command(s) then your simple sources and receivers will move `n` multiplied by the step size in whatever direction. You must ensure your domain is large enough to allow this. If it is not you will get the error message you receive.

Uring converting the format between .out and .RAD, we are required to provide the 'source-receiver distance' and 'trace step'. 
I guess the 'trace step' can be seen as  `#rx_steps`, am I right? and what is the 'source-receiver distance' ?

**Comment by craig-warren** [comment]
Source-receiver distance is simply what is says, i.e. the offset or distance between the source element of the antenna and the receiver element. These maybe between theoretical source and receiver if no physical antenna model is used in the simulation. The trace step would be the step used with the `#src_steps` and `#rx_steps` commands, assuming a common offset survey.
