### ISSUE TITLE
Why the gprMax code always made my computer restart?

### ISSUE THREAD

**Issue by borehole-question** [gprMax/gprMax#184]
Hi friend,

I have used gprMax for a long time and it i is very good. But a new gprMax code always made my computer restart when it runs to about half window time. When I change the y-length of 12 m to 8 m, the program works well. It really confused me. The machine uses Windows 10, and  the RAM of 256 GB. Both prompt information and codes are attached. Because the 'remote control' is used , the error reported in gprMax or a screenshot of the command prompt when the problem occurs is not avalable.
![information](https://user-images.githubusercontent.com/38339913/50191592-42049200-037a-11e9-9881-fc092a64fdce.png)

[trans.zip](https://github.com/gprMax/gprMax/files/2692804/trans.zip)
Thanks very much!
 
HJJ

**Comment by craig-warren** [comment]
@borehole-question I really need to see the error reported by gprMax to help you solve this issue. The estimated memory required for the model  is ~15GB. I tested your input file and the model started to run OK. Please try to find a way of getting a log of the error.
