### ISSUE TITLE
paraview snapshort

### ISSUE THREAD

**Issue by ELEGER** [gprMax/gprMax#19]
Hi,
I'm facing an issue with seeing snapshot with paraview:
ERROR: In /build/buildd/paraview-4.0.1/VTK/IO/XML/vtkXMLStructuredDataReader.cxx, line 348
vtkXMLImageDataReader (0x3338e40): Error reading extent 0 300 0 300 0 0 from piece 0

[4]  + segmentation fault (core dumped)  paraview snapshot1.vti

Enclose is the input file, I don't get what do I do wrong...Stupid of me as usual
Thanks for you help!
[2couchesperm.txt](https://github.com/gprMax/gprMax/files/75144/2couchesperm.txt)

**Comment by ELEGER** [comment]
As a complement, this is when I click the apply button that paraview chrashes.

and I tried with multiples snapshots a well.

Cheers

**Comment by craig-warren** [comment]
Your snapshot has no cells (extent) in the z-direction. You have a spacing of 0.01m but the domain is only 0.005m in the z-direction.

**Comment by ELEGER** [comment]
Thank you Craig. My bad...
Wish you an happy new year.
