### ISSUE TITLE
To fix an issue causing an OS to exceed number of allowed open files

### ISSUE THREAD

**Issue by advocateddrummer** [gprMax/gprMax#190]
This is a minor issue, but I have a user who has run up against this on a HPC cluster. His cases would crash as they number of open files would exceed the number allowed by the OS. There seems to be an easy and quick fix outlined below with a patch:

> [root@os-hn gprMax]# git diff -p tools/outputfiles_merge.py
> diff --git a/tools/outputfiles_merge.py b/tools/outputfiles_merge.py
> index 84d91ac..807d8c9 100644
> --- a/tools/outputfiles_merge.py
> +++ b/tools/outputfiles_merge.py
> @@ -58,6 +58,8 @@ def get_output_data(filename, rxnumber, rxcomponent):
>      outputdata = f[path + '/' + rxcomponent]
>      outputdata = np.array(outputdata)
>  
> +    f.close()
> +
>      return outputdata, dt

I have implemented the trivial patch above and his jobs would run to completion. I assume that the f.close() should be included but I'll let you decide!

**Comment by craig-warren** [comment]
@advocateddrummer thanks for noticing this. I was relying on Python closing the file(s) at the appropriate point, but that clearly doesn't work for all cases. As you suggested I have added explicit `f.close()` calls.
