### ISSUE TITLE
B-Scan visualization

### ISSUE THREAD

**Issue by SyedFaisalGardezi** [gprMax/gprMax#191]
Hello,
 Can anyone help me, How can I visualize my B-Scan output file (eg cylinder_BScan.out) which is generated through comand "**_python -m gprMax user_models/cylinder_Bscan_2D.in -n 60_**". I have tried different techniques from google but it's not working. I want to see the output like in the image below. Thanks
![gpr b scan](https://user-images.githubusercontent.com/43716662/53395945-2521b600-39de-11e9-8f70-1ab957c48cd8.png)

**Comment by craig-warren** [comment]
@SyedFaisalGardezi this is not a bug or issue with the code, please post these type of questions in our forum (Google Group) - http://www.gprmax.com/forum.shtml

For your information look at the example in the docs for how to merge and plot B-scans - http://docs.gprmax.com/en/latest/examples_simple_2D.html#b-scan-from-a-metal-cylinder
