### ISSUE TITLE
ResolvePackageNotFound:   - blas[build=openblas]

### ISSUE THREAD

**Issue by zirlman** [gprMax/gprMax#192]
Steps I've done:
- [X] conda update conda
- [X] conda install git
- [X] git clone https://github.com/gprMax/gprMax.git
- [x] cd gprMax
- [ ] conda env create -f conda_env.yml 

When trying to apply the last command I get this output:
```
Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound:
  - blas[build=openblas]
```
And the _conda_env.yml_ file looks like this:

```
name: gprMax
dependencies:
- python>3.6
- blas=*=openblas
- colorama
- cython
- h5py
- jupyter
- matplotlib
- numpy
- psutil
- scipy

- pip:
 # - mpi4py
 # - pycuda
  - terminaltables
  - tqdm

```

**Comment by craig-warren** [comment]
@zirlman, yes it would seem OpenBLAS is not available for Windows through conda. Am looking into see if there is an easy way round this.

**Comment by craig-warren** [comment]
I have updated the conda environment file to remove the OpenBLAS dependency. This works on Windows and Linux. However, macOS currently requires a different conda environment file because it does need OpenBLAS as the standard MKL library causes an instability on macOS.

**Comment by zirlman** [comment]
@craig-warren Thank you. Now I'm finally able to use gprMax. But isn't openblas necessary for gprMax to work properly? I've managed to test gprMax with the example from the installation, but I'm not sure how it will work on my own models?

**Comment by craig-warren** [comment]
@zirlman OpenBLAS is not specifically required, using the default MKL is fine. As said, I specified it as a dependency recently because on macOS it is currently required to avoid issues. No such requirement for Linux and Windows.

**Comment by craig-warren** [comment]
macOS specific issue with MKL filed - https://github.com/gprMax/gprMax/issues/195
