### ISSUE TITLE
B-scan plotting with rxarray - indexerror

### ISSUE THREAD

**Issue by rjdelf** [gprMax/gprMax#193]
I'm running an exploding reflector-type model with an rx_array along the surface, which outputs all receivers to one .out file, so I'd like to be able to plot this rx_array as a B-scan. 
Running
`python -m tools.plot_Bscan exploding_reflector_test.out Ez`
returns error
`IndexError: tuple index out of range` 

Error comes from imshow on line 47 of plot_Bscan.

I think this is because the B-scan from an rx_array hasn't been generated in the same way as the outputmerge_files. Using outputfiles_merge returns 1 receiver with an nt x nrx array but rx_array returns nrx receivers each with a 1d output array length nt.

A workaround I've thought of is below to test how many receivers there are. If nrx=1, assume the file is generated from outputfiles_merge and plot as before. If nrx>1 (as the output from rx_array), append together and plot the resultant array.  Might need to add some errors. May well be a better way to do it.

Tested with a merged dataset and an rx_array output seems to work no problem.

From line 72 of plot_Bscan.py:
```
if __name__ == "__main__":

    # Parse command line arguments
    parser = argparse.ArgumentParser(description='Plots a B-scan image.', usage='cd gprMax; python -m tools.plot_Bscan outputfile output')
    parser.add_argument('outputfile', help='name of output file including path')
    parser.add_argument('rx_component', help='name of output component to be plotted', choices=['Ex', 'Ey', 'Ez', 'Hx', 'Hy', 'Hz', 'Ix', 'Iy', 'Iz'])
    args = parser.parse_args()

    # Open output file and read number of outputs (receivers)
    f = h5py.File(args.outputfile, 'r')
    nrx = f.attrs['nrx']
    f.close()

    # Check there are any receivers
    if nrx == 0:
        raise CmdInputError('No receivers found in {}'.format(args.outputfile))

    #if only one receiver, assume it's from outputfiles_merge
    elif nrx == 1:
        rx=1
        outputdata, dt = get_output_data(args.outputfile, rx, args.rx_component)
        if outputdata.ndim==2:
            plthandle = mpl_plot(args.outputfile, outputdata, dt, rx, args.rx_component)
        else:
            print('Throw an error')

    elif nrx > 1:
        bscan=[]
        for rx in np.arange(1,nrx,1):
            outputdata, dt = get_output_data(args.outputfile, rx, args.rx_component)
            bscan.append(outputdata)
        bscan=np.asarray(bscan).T
        plthandle = mpl_plot(args.outputfile, bscan, dt, rx, args.rx_component)

```

**Comment by craig-warren** [comment]
Thanks @rjdelf and for your related pull request - https://github.com/gprMax/gprMax/pull/194

Let me think if this is best way to approach this issue, given how we would like our output files to be structured. My initial thought was to create another merge type function for receiver data, to merge it into a new file, but I don't know if this is the best approach either....

**Comment by craig-warren** [comment]
@rjdelf had some thoughts on this. I want to check I understand correctly, you are essentially talking about combining the multiple figure windows you get when you run plot_Ascan on an input file with multiple receivers in it? If so, I think it might be better to offer this as an option with the `plot_Ascan.py` tool or maybe a create a separate tool. I think this if equivalent to a seismic shot record?

**Comment by craig-warren** [comment]
Plotting a B-scan with multi-receivers in a single model now added to plot_Bscan in devel branch.
