### ISSUE TITLE
Why does it show "No module named 'terminaltables'" when I start my project?

### ISSUE THREAD

**Issue by hhrm** [gprMax/gprMax#197]

**Comment by craig-warren** [comment]
@hhrm looks like your conda environment didn't install correctly. Make sure you have pulled the latest version of gprMax, then update the environment `conda env update -f conda_env.yml`. Alternately just add the two packages that are installed with pip manually, i.e. `conda install terminaltables tqdm`

**Comment by namanchikara** [comment]
Try first activating the virtual environment by running the command `activate gprMax`, and then install required modules `pip install terminaltables` and `pip install `tqdm`

**Comment by hhrm** [comment]
Thank u so much, I'd solved this problem.
