### ISSUE TITLE
Cannot import relative imports

### ISSUE THREAD

**Issue by iliTheFallen** [gprMax/gprMax#2]
Hi Professor,

I downloaded the software on Ubuntu 14.04 platform. When i run it using python3 it gives me : 
"SystemError: Parent module '' not loaded, cannot perform relative import". I think, python3 cannot recognize those dots typed in front of import paths. Can you produce the same error?

Kind Regards,
Ilker

**Comment by craig-warren** [comment]
Hi IIker, It sounds like you are either:

- not running gprMax from the top-level directory, i.e the directory with setup.py, README.rst etc..

- or are not running gprMax as a module, i.e with the '- m' flag.

'python3 -m gprMax inputfile'

Can you check you are doing these things.

**Comment by iliTheFallen** [comment]
Hello Professor;

Thank you for your help. I have fixed the problem; but now whenever I want to display B scan; it throws another exception though I do not have any problem when i display A scan. It seems the index into an array is out of array' s bound :  

  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mesut/Documents/gprMax/tools/plot_hdf5_Bscan.py", line 41, in <module>
    plt.imshow(data, extent=[0, data.shape[1], data.shape[0]*f.attrs['dt'], 0], interpolation='nearest', aspect='auto', cmap='seismic', vmin=-np.amax(np.abs(data)), vmax=np.amax(np.abs(data)))
IndexError: tuple index out of range

Kind Regards,
Ilker

**Comment by craig-warren** [comment]
Hi IIker, Glad you fixed the original problem. Can you start a new issue for your B scan problem and attach or paste the input file and command you are using the run the model. I'm closing this issue.
