### ISSUE TITLE
GPU solver and --geometry-fixed argument

### ISSUE THREAD

**Issue by craig-warren** [gprMax/gprMax#200]
When the GPU-based solver is used along with the `--geometry-fixed` argument, the simulation crashes with the attached CUDA error. It think this has to do with re-using the `G` structure which perhaps contains some GPU memory references that are not getting cleaned up properly.
![geom_fixed_GPU_error](https://user-images.githubusercontent.com/11279495/55484194-fa9bcc00-561f-11e9-9e8b-1865847f6729.png)

**Comment by spaceVStab** [comment]
For test simulation, running with `user_models/cylinder_Bscan_2D.in` doesn't crashes. 
`$ python -m gprMax user_models/cylinder_Bscan_2D.in -n 5 -gpu`
Can you please share your `.in` file.

**Comment by craig-warren** [comment]
@spaceVStab the error occurs when you include the `--geometry-fixed` argument, e.g. `$ python -m gprMax user_models/cylinder_Bscan_2D.in -n 5 -gpu --geometry-fixed`

When you try this, do you get the same error?

**Comment by spaceVStab** [comment]
My mistake I had added `--geometry-fixed` but forgot to mention.
There is were no error though.

**Comment by craig-warren** [comment]
@spaceVStab I suspect in your case you did not get the same error because the size of the model is not close to the memory capacity of your GPU?

**Comment by spaceVStab** [comment]
Yes, that might be the case. 
Adding the memory check function for else logic can give some insights on memory usage.
https://github.com/gprMax/gprMax/blob/31aaa9474743ae3a2ed7629c0ed18f00c6270662/gprMax/model_build_run.py#L294
Can you let me know of any available user_models that occupy around ~3 / ~3.2 GB GPU memory. I can test such model for my PC setup.

**Comment by craig-warren** [comment]
@spaceVStab for the purposes of testing you can just increase the domain size of the model (`cylinder_Bscan_2D.in`) until it just fits on the GPU memory.

**Comment by craig-warren** [comment]
Closed as stale.
