### ISSUE TITLE
Using geometry_objects_read with GSSI antenna modells

### ISSUE THREAD

**Issue by nallroggen** [gprMax/gprMax#204]
Hi Craig,

I have been playing with the GSSI antenna models (400 MHz and 1500MHz) and came across an issue when using them with an external models. In file pml.py the code iterates through the given materials. However, it crashes (stops iterating) at line 381:

material = next(x for x in G.materials if x.numID == numID)

my guess is that it cannot find the additional materials for the antenna in G.materials. Doing a brief search I could not find where they are missed, maybe you have an idea?

Best
Niklas

**Comment by craig-warren** [comment]
Hi Niklas,

Can you provide an example input file that causes the problem so I can check. It doesn't have to be the actual one you are using for your research, just a sample that shows the issue.

Kind regards,

Craig

**Comment by nallroggen** [comment]
Hi Craig,
thank you for your quick response! I will prepare a "working" version of
the model I am currently working on, and send you an owncloud share
later today.
When we subtract 5 (number of antenna materials?) from the numID in file
pml.py Line 381 and 396 probably also line 412, and change it to:
numID = G.solid[i, pml.ys, k]-5

the model runs but we probably have false materials IDs in the PML
layers. Not sure if this matters much??

Best
Niklas

**Comment by nallroggen** [comment]
Hi Craig,

you are right... The problem, was the input file containing too large int values.. Its probably me coming from Matlab and thinking arrays start at 1... I owe you a beer! Thanks a lot! Think we can close this issue...
