### ISSUE TITLE
installation of GPRMAX on windows 10

### ISSUE THREAD

**Issue by chaslie** [gprMax/gprMax#206]
I had a successful installation and then along came windows and corrupted. I have tried reinstalling gprmax and now get the following errors during setup.py build phase:

envs\gprmax\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
error: command 'd:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\cl.exe' failed with exit status 2

This at first appears to be an mpi issue, until I check the conda_env.yml and realise that the mpi is hashed out. 

any ideas (I have removed visual studio 14 and re installed several times, deleted the environment and reinstalled from scratch following the process in the getting started)

**Comment by craig-warren** [comment]
@chaslie stating the obvious, but it looks like a MSVS problem. I can only really recommend uninstalling MSVS, as well as Anaconda (conda) in case it somehow is linked to your older install, and starting the install from scratch.

**Comment by craig-warren** [comment]
and make sure the Windows 10 SDK is installed when you install Microsoft Visual C++ 2015 Build Tools.

**Comment by chaslie** [comment]
Hi Craig,

Thanks for the response, silly question should I install MS visual studio before or after anaconda? 

Windows 10 SDK is installed when I reinstalled Visual studio.

**Comment by craig-warren** [comment]
Not a silly question: I have usually installed conda first, but I am not sure if there is a difference on Windows - it is not my regular machine, I use either my iMac or a Linux box.

**Comment by chaslie** [comment]
Hi Craig,

apologies for not getting back earlier. I have tried removing anaconda and visual studio and then rebuilding from scratch, and I get the same error. I think its time to dual boot with ubuntu, is there a preferred version? 

charlie

Ps the version of windows I am having trouble with is 1809 build 17763.475 in case anyone else is having similar issues...
