### ISSUE TITLE
First example output display error 

### ISSUE THREAD

**Issue by neilwang0913** [gprMax/gprMax#21]
Hello:

I was successfully run this example and get the right output. However, I see the error when i run follow
 running command : python3 -m tools.plot_Ascan user_models/cylinder_Ascan_2D.out
error : /usr/local/opt/python3/bin/python3.5: No module named tools.plot_Ascan
Could you guide me how to fix this problem.

Kind regards.

Fengzhou

**Comment by craig-warren** [comment]
Hmmm...that is a strange error. Firstly, are you sure you executed the command as you have typed it here? i.e. `python3 -m tools.plot_Ascan user_models/cylinder_Ascan_2D.out`; and secondly have you downloaded the most recent version of gprMax? as some of the names of the tools have changed in the betas.

**Comment by neilwang0913** [comment]
Hello:

Yes, I did not use the latest version to do the simulation and plot out.
The simulation seems work but the output could not plot properly.
Now it works.

I have a general question: How could I find out that error causing by the
tool's name change? Is there any way to avoid this kind error happens since
we finally need to update these tool to the latest version?

Many thanks.

Fengzhou

**Comment by craig-warren** [comment]
Python is usually pretty good at identifying the error, i.e. `error : /usr/local/opt/python3/bin/python3.5: No module named tools.plot_Ascan` 

You can view a list of all the gprMax releases by clicking on the releases tab from GitHub.
