### ISSUE TITLE
FloatingPointError: divide by zero encountered in true_divide

### ISSUE THREAD

**Issue by zhoudapeng1234** [gprMax/gprMax#212]
When I run the model "antenna_wire_dipole_fs.in" in my computer, I found that if  I run the command "python -m tools.plot_antenna_params user_models/antenna_wire_dipole_fs.out", there will be an error "FloatingPointError: divide by zero encountered in true_divide " in line 104. I know it means denominator can not be zero, but why the example given is right. My computer is win10.

![QQ截图20190625233551](https://user-images.githubusercontent.com/17759040/60113057-919d9d80-97a3-11e9-8d4e-5c53f25b4655.png)

**Comment by craig-warren** [comment]
A divide by zero error suggests your model output contains errors. Have you checked it using the A-scan plotting tools?
