### ISSUE TITLE
Python 3.7?

### ISSUE THREAD

**Issue by ghentr** [gprMax/gprMax#213]
Hi; I'm new to gprMax, and installed it on one computer (Mac OS X, Yosemite) running Python 3.6, and all is well.  I've now tried to install it on another computer( Mac OS X, Mojave), and have just installed a new copy of Anaconda, and Python 3.7; and I get all zero values for the first example (user_models/cylinder_Ascan) -- see screenshot attached.  I notice that Python 3.6 is listed in the conda_env.yml file, yet Python 3.7 is being installed.  I've tried adding python=3.6 to the environment creation command, but Python 3.7 is still installed as part of the environment.  Is this the reason I'm getting erroneous values?  Or is there some other package problem, etc?

Thanks.

![Screen Shot 2019-07-02 at 2 34 12 PM](https://user-images.githubusercontent.com/30534879/60538442-a795eb80-9cd8-11e9-8fb6-d2b5e0d44a46.png)

**Comment by craig-warren** [comment]
@ghentr see #195 you need to use the `conda_env_macOS.yml` environment file.
