### ISSUE TITLE
Build error on macOS Mojave with OpenCL CPU

### ISSUE THREAD

**Issue by craig-warren** [gprMax/gprMax#217]
This seems to be an issue with the opencl implementation in 10.14 - https://github.com/inducer/pyopencl/issues/276

Setting the environment variable `PYOPENCL_NO_CACHE=1` fixes the issue for now.

**Comment by PawBud** [comment]
@craig-warren, I am currently using MacOS Ventura (V 13.2.1 (22D68)). How do I recreate the aforementioned issue, to test the same?

**Comment by craig-warren** [comment]
macOS Ventura and Sonoma not showing this issue.
