### ISSUE TITLE
2D binary grating consists of a cylinder 

### ISSUE THREAD

**Issue by BrandonHanx** [gprMax/gprMax#221]
Thanks for the excellent work. 
I am a new on metasurface. I wanna define a meta-atom consists of a cylinder with a glass substrate, which is a periodic unit of a 2D binary grating, and I wanna get the transmittance of the plane wave with different frequencies. [Here]( https://box.zjuqsc.com/-48402925 ) is the model I made in Lumerical FDTD solutions. 
Is there any example that is similar to this task that I can refer to?

**Comment by craig-warren** [comment]
Thanks for the question. We like to keep the issue tracker for code-specific problems/bugs. For more general modelling questions such as yours, please use our Forum (Google Group) - http://www.gprmax.com/forum.shtml
