### ISSUE TITLE
Define dipole source wavelength bandwidth

### ISSUE THREAD

**Issue by shuren007** [gprMax/gprMax#222]
Hi,

I didn't fine how to define a dipole source band width. The tutorial seems only have the command to define center frequency. How should I specify the width of the source frequency?

### here is from gprMax doc: 

#waveform: str1 f1 f2 str2

f1 is the scaling of the maximum amplitude of the waveform (for a #hertzian_dipole the units will be Amps, for a #voltage_source or #transmission_line the units will be Volts).
f2 is the centre frequency of the waveform (Hertz). In the case of the Gaussian waveform it is related to the pulse width.
str2 is an identifier for the waveform used to assign it to a source.

Thanks. 
Shuren

**Comment by craig-warren** [comment]
Thanks for the question. We like to keep the issue tracker for code-specific problems/bugs. For more general modelling questions such as yours, please use our Forum (Google Group) - http://www.gprmax.com/forum.shtml
