### ISSUE TITLE
#pml_cells has too many cells for the domain size??

### ISSUE THREAD

**Issue by hhrm** [gprMax/gprMax#230]
Why does it show " #pml_cells has too many cells for the domain size" ?
And here is my doc :
#domain: 0.24 0.20 0.03
#dx_dy_dz: 0.002 0.002 0.002
#time_window: 5e-9
#material: 4 0 1 0 half_space
#material: 1 0 1 0 air_space
#waveform: ricker 1 1.5e9 MySource
#hertzian_dipole: z 0.02 0.19 0.014 MySource
#rx: 0.025 0.19 0.014
#src_steps: 0.002 0 0
#rx_steps: 0.002 0 0
#box: 0 0 0 0.24 0.17 0.03 half_space
#box: 0.10 0.08 0 0.14 0.12 0.03 pec

**Comment by craig-warren** [comment]
@hhrm please keep questions on how to use the software for our Forum (Google Group) - http://www.gprmax.com/forum.shtml

In this case your domain is too small to accommodate the PML boundaries, which by default are 10 cells thick on each side of the domain.

Craig

**Comment by hhrm** [comment]
But I cant post a message on http://www.gprmax.com/forum.shtml.
