### ISSUE TITLE
#add_grass command gives ValueError with gpu

### ISSUE THREAD

**Issue by eyyupT** [gprMax/gprMax#234]
#add_grass command gives 
ValueError: index 32000 is out of bounds for array with size 32000.

I have tried different sizes but every time i got this error. 
Operating system : Ubuntu 16.04
gprMax version : v3.1.5
@craig-warren 
![ValueError](https://user-images.githubusercontent.com/26031250/70939742-f0a8e480-2059-11ea-8333-2d1a8cc6c894.png)

**Comment by eyyupT** [comment]
@craig-warren

**Comment by craig-warren** [comment]
@eyyupT can you supply the input file you are using, or a simple example that exhibits the behaviour.

**Comment by eyyupT** [comment]
#title: gpr_11202
#domain: 1.0 0.12 0.4
#dx_dy_dz: 0.001 0.001 0.001
#time_window: 2500

#num_threads: 6

#material: 3.0 0.01 1.0 0.0 plastic   

#soil_peplinski: 0.5 0.5 2.0 2.66 0.001 0.25 heterogeneous_soil
#fractal_box: 0 0 0 1.0 0.12 0.3 1.5 1 1 1 50 heterogeneous_soil my_fractal_box
**#add_grass: 0 0 0.3 1.0 0.12 0.3 1.5 0.28 0.32 100000 my_fractal_box**

#cylinder: 0.5 0.06 0.24 0.5 0.06 0.28 0.028 plastic

#python:
from user_libs.antennas import antenna_like_GSSI_1500
antenna_like_GSSI_1500(0.1 + current_model_run * 0.01, 0.06, 0.35, 0.001)
#end_python:

this input file gives following error
/home/eyyup/gprMax/notlar/11201_hata.png

I guess the number 120000 is the product of dimension in x and y coordinate (1000x120) 

I tried above input file with below code to reduce grass area and to get rid of error 
#add_grass: 0.1 0.04 0.3 0.9 0.08 0.3 1.5 0.28 0.32 10000 my_fractal_box

and the i got error with the number 32000 (grass area =800x400).
I run the simulation 80 times. Error is arrised randomly not a specific simulation. Thus i need to sun simulation 80 times to get same error. 

Thank you so much.

Best Regards

**Comment by eyyupT** [comment]
@craig-warren any improvement ?

**Comment by craig-warren** [comment]
@eyyupT can you provide a basic example of this behaviour that consistently gives the error. When I tested your examples the model ran without any error. What are the differences in your 80 A-scans?

**Comment by eyyupT** [comment]
@craig-warren antenna moves 0.1 cm in each simulation.

**Comment by craig-warren** [comment]
@eyyupT thanks, but can you provide a basic example (input file) that exhibits this behaviour consistently?
