### ISSUE TITLE
Resampling of external source extremely slow.

### ISSUE THREAD

**Issue by GaleonAD** [gprMax/gprMax#239]
I tried simulate source given in external file with time window 1e-4, when in file time step=1e-11 while simulation choose time step = 1,47e-12. Preparation of source is extremely slow, I waited half an hour on my laptop before I decided to cancel. Everything works fine with time window 1e-7.

**Comment by GaleonAD** [comment]
I just modified example with 2D Ascan of cylinder

**Comment by craig-warren** [comment]
@GaleonAD can you provide the input file and external source file you are using?

**Comment by GaleonAD** [comment]
Sure, enclosing as zip. External source file is pretty big so i send you python script that generates it. I see now, considering size of input, that maybe my expectations are too big, but i think that issue may be connected with interpolation method however Im not familiar with implementation.

[smp.zip](https://github.com/gprMax/gprMax/files/4231199/smp.zip)

**Comment by craig-warren** [comment]
@GaleonAD you have ~11e6 samples in your source waveform. I don't think there is any issue with the code here, so I'm closing this issue. If you want to discuss custom waveforms further why not start a post on our Google Group (Forum) - http://www.gprmax.com/forum.shtml For example think about why you need so many samples? Usually you'd want one sample per time step of your simulation. What kind of model are you running?
