### ISSUE TITLE
Question for snapshot : read files of vti

### ISSUE THREAD

**Issue by yohanncsy** [gprMax/gprMax#245]
Question for snapshot : I can create many files of images, whose format is .vti, and they will give me a 'video' in paraview. But how can I read the data in every filename.vti ? I want to use matlab code to read it.

Best wishes,,

Siyuan

**Comment by craig-warren** [comment]
@yohanncsy this is not a bug or issue with gprMax so please post your question in our Google Group (Forum) - http://www.gprmax.com/forum.shtml
