### ISSUE TITLE
plot_Ascan fails: no module named wx

### ISSUE THREAD

**Issue by LeftyAce** [gprMax/gprMax#246]
I'm new to gprMax, and I've followed the installation instructions here: http://docs.gprmax.com/en/latest/include_readme.html 

I'm running Arch Linux, and installed conda through my package manager. 
I ran the cylinder A scan example (and it finishes successfully), but when I try to view it, I get the following error:

`(gprMax)$ python -m tools.plot_Ascan user_models/cylinder_Ascan_2D.out`

> Traceback (most recent call last):
> 
>   File "/home/lefty/.conda/envs/gprMax/lib/python3.8/runpy.py", line 193, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/lefty/.conda/envs/gprMax/lib/python3.8/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/lefty/gprMax/tools/plot_Ascan.py", line 25, in <module>
>     import matplotlib.pyplot as plt
>   File "/home/lefty/.conda/envs/gprMax/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2356, in <module>
>     switch_backend(rcParams["backend"])
>   File "/home/lefty/.conda/envs/gprMax/lib/python3.8/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
>     backend_mod = importlib.import_module(backend_name)
>   File "/home/lefty/.conda/envs/gprMax/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/home/lefty/.conda/envs/gprMax/lib/python3.8/site-packages/matplotlib/backends/backend_wxagg.py", line 1, in <module>
>     import wx
> ModuleNotFoundError: No module named 'wx'`

Any idea why wx didn't get installed? How should I add it within conda? I don't think I want to install it just using pip, because I'm trying to keep my gprMax environment separate from my "regular" python environment.

**Comment by craig-warren** [comment]
@LeftyAce haven't seen this before. Looks like an issue with matplotlib and when it tries to use the wx backend. With the gprMax conda environment active, you can try using pip to install wx. This will still keep within the gprMax environment, and separate from everything else. Let me know if this resolves it.

**Comment by LeftyAce** [comment]
@craig-warren , thanks for the suggestion. I was able to resolve the issue by adding this line to the conda_env.yml file, in the "dependencies: " section (below psutil and scipy).

`- wxPython`

It looks like that forced it to be installed, and everything's working. I'm guessing my distro doesn't have wxPython as a dependency for one of the other packages that gprMax installs (matplotlib, probably). Should the wxPython requirement be added to the standard gprMax conda_env.yml file?

**Comment by craig-warren** [comment]
@LeftyAce glad it is working this _seems_ to be just required for Arch Linux. I don't want to add it to the `conda_env.yml` file but I've put a note in our [README.rst](https://github.com/gprMax/gprMax/blob/master/README.rst).
