### ISSUE TITLE
Paraview macro TypeError

### ISSUE THREAD

**Issue by LeftyAce** [gprMax/gprMax#247]
Thanks for a great tool! 

I've encountered an error trying to use the Paraview macro that ships with gprMax (gprMax_info.py). It occurs with both Paraview 5.7 and 5.8, Windows and Linux.

`Traceback (most recent call last):
  File "<string>", line 43, in <module>
TypeError: startswith first arg must be bytes or a tuple of bytes, not str`

A little googling indicates that the problem is that the script has read the file in byte mode ('rb'), but the startswith() function is being fed a string, so it's trying to compare a string with a byte array. I was able to fix the problem by changing the startswith() statements like this:

`if line.startswith(b'<Material'): `

to cast the string comparison to bytes to match the type of 'line.'

Am I fixing this right, or is this a symptom of another problem? If this is the correct fix, what's the best way to submit my version of gprMax_info.py? I haven't dealt with pull requests on GitHub before.

**Comment by craig-warren** [comment]
@LeftyAce thanks for pointing this out. I've updated the macro, so if you could update your gprMax and try it that would be great.

**Comment by LeftyAce** [comment]
@craig-warren, I'm still getting errors. It looks like the line.rstrip('\n') lines also need to be modified to line.rstrip(b'\n'). (Changing those fixed the problem on my end).

**Comment by craig-warren** [comment]
@LeftyAce thanks updated that too.

**Comment by LeftyAce** [comment]
@craig-warren Thanks for fixing this, it's now working for me.
