### ISSUE TITLE
Build error on macOS Catalina

### ISSUE THREAD

**Issue by Giorgella** [gprMax/gprMax#248]
Hi everyone,

I can't wait to try the software, but I am stuck at 'Running gprMax'!
I followed all the instructions on "https://github.com/gprmax/gprMax" but this is what happens as soon as I try to build setup.py:

**ld: library not found for -liomp5
collect2: error: ld returned 1 exit status
error: command 'gcc-9' failed with exit status 1**

Did someone already come across this error?

Thanks!!!

**Comment by craig-warren** [comment]
@Giorgella I haven't seen this before. I have macOS Catalina on my laptop, so I'll take a look when I get a chance, but it might be a few days. Can you provide version numbers for the following on your machine:

macOS Catalina
Xcode
gcc

**Comment by Giorgella** [comment]
Hi @craig-warren, thanks for your reply!
These are the info:

macOS Catalina - version 10.15.4
Xcode - version 11.4.1

and this is what appears when I type: $ gcc --version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(base) Giorgias-MacBook-Pro:~ giorgella$

**Comment by craig-warren** [comment]
@Giorgella are you still experiencing this issue? I finally got some time to test on my macOS Catalina install and could not replicate the issue. My config is not exactly the same:

macOS: 10.15.3
Xcode: 11.5
gcc-9:  9.3.0

All I can suggest is making sure macOS is up-to-date (I think 10.5.5 is the most recent update) and updating gcc through Homebrew `brew update` then `brew upgrade`
