### ISSUE TITLE
Landmines user library sub-package not found

### ISSUE THREAD

**Issue by snailfury** [gprMax/gprMax#249]
Hello! I am new to gprMax and attempting to use the landmines sub-package referenced in the user guide documentation (user_libs_landmines.rst), but am unable to find the sub-package in /user_libs. Is there another repo that contains this library? Thank you very much for your time.

**Comment by craig-warren** [comment]
@snailfury the landmines sub-package has not yet been released. There is some unlinked info on it in the docs (which I think you found), but we haven't made a decision yet about if/when to release it.

**Comment by snailfury** [comment]
Thank you for your response!
