### ISSUE TITLE
Matlab error while reading file

### ISSUE THREAD

**Issue by rajathkumarmp** [gprMax/gprMax#25]
The same error is encountered in both A-Scan and B-Scan

```
Error using hdf5lib2
The HDF5 library encountered an error and produced the following stack trace information:

    H5O_attr_open_by_name    can't locate attribute
    H5A_open_by_name         unable to load attribute info from object header
    H5Aopen_name             can't open attribute

Error in H5A.open_name (line 16)
attr_id = H5ML.hdf5lib2('H5Aopen_name', loc_id,name);

Error in h5readatt (line 48)
attr_id = H5A.open_name(obj_id,options.Attname);

Error in plot_Bscan (line 13)
    iterations = double(h5readatt(filename, '/', 'Iterations')); 
```

**Comment by craig-warren** [comment]
Again thanks for the spot. This is because some of the names of the attributes had changed. It should be fixed now.

The MATLAB scripts are there for help only, and do not contain all the functionality of the Python tools modules.

**Comment by rajathkumarmp** [comment]
@craig-warren 
even plot_Bscan.m does not work properly and outputs the same error as above.

I understand Matlab is for representation purpose only but it does help in porting data to Matlab which proves to be very helpful in my case :)

**Comment by craig-warren** [comment]
I can't reproduce this error. I think this is linked to the problems you are having with the Python module `plot_Bscan`. Perhaps your Bscan output file is corrupt?

**Comment by rajathkumarmp** [comment]
Yes correct. Working fine now.
