### ISSUE TITLE
Missing comma at plot_antenna_params

### ISSUE THREAD

**Issue by GaleonAD** [gprMax/gprMax#250]
Missing comma between two last parameters at line 343 and 358 (and other but they are commented) in file tools/plot_antenna_params.py

`    markerline, stemlines, baseline = ax.stem(freqs[pltrange], zin[pltrange].real, '-.' use_line_collection=True)
`

should be

`    markerline, stemlines, baseline = ax.stem(freqs[pltrange], zin[pltrange].real, '-.', use_line_collection=True)
`

**Comment by craig-warren** [comment]
@GaleonAD thanks, this should be fixed now.
