### ISSUE TITLE
Issue runnning single-threaded gprMax in parallel with gprMax 3.1.5

### ISSUE THREAD

**Issue by asaintenoy** [gprMax/gprMax#254]
Dear Craig,

For a computation of mine, I run many computations in parallel
processes on a multicore machine, with each computation involving a
call to gprMax at some point. Since the calling code is already
parallel, gprMax is run with parallelism disabled. However, with the
latest version of gprMax, it seems that several gprMax processes that
run in parallel are forced to all share the same core.

Here is a toy example. The following shell command runs five copies of
gprMax in parallel on five *.in input files (see the attached zip file).

        for i in 1 2 3 4 5; do (cd test$i && python -m gprMax radargram_1.in > /dev/null) & done

`#num_threads: 1` set in each of the *.in input files

I did some testing on three different computers (which I'll call A,B,C
here) running different versions of Python and gprMax. A and B have 2
threads per core. C has 1 thread per core.

Here are outcomes of my tests:

- gprMax-3.1.3-py3.6-linux-x86_64, computer A: the five computations
  run as expected on five different CPU, using each 100% of CPU.

- gprMax-3.1.5-py3.8-linux-x86_64, computer A&B: the five computations
  are run on 2 CPUs only, using each about 40% of CPU.

- gprMax-3.1.5-py3.7-linux-x86_64, computer C: the five computations
  run on a single CPU, using each about 20% of CPU.

The test matrix is not complete yet, but suggest the above claim.

Do you have an idea of what is happening and how I could resolve this
issue? For now, I'll try downgrading everywhere to gprMax 3.1.3.

Let me know if some additional testing here would be relevant.
Best regards,

Albane Saintenoy

[test.zip](https://github.com/gprMax/gprMax/files/4676512/test.zip)

**Comment by asaintenoy** [comment]
For the record I edited the text above for adding clarifications.

**Comment by asaintenoy** [comment]
One more test point: 
- gprMax-3.1.3-py3.6-linux-x86_64, computer B : the five computations
are run on 2 CPUs only, using each about 40% of CPU.

So the problem might come from some dependency of gprMax...

**Comment by craig-warren** [comment]
Hi @asaintenoy hope you are well  in these slightly crazy times!

This won't be a quick question for me to answer, I will need to give it some thought and do a few tests. A couple of initial questions/observations:

1. I don't think anything has changed in the gprMax that would have effected your issue between 3.1.3 and 3.1.5. Therefore it maybe something in the Python version or a package dependency.
2. Which specific CPUs and threads/cores are used is usually controlled by the operating system (OS) scheduler. There are some environment variables for OpenMP which we set that can have an influence on this - https://github.com/gprMax/gprMax/blob/5530b3488487797d1c219265e0b6b434a57a4b0d/gprMax/input_cmds_singleuse.py#L77
3. Are the 2 threads per core with hyperthreading?

Kind regards,

Craig

**Comment by asaintenoy** [comment]
Hello, 

I set up in gprMax/gprMax/Input_cmds_singleuse.py

    os.environ['OMP_PLACES'] = 'sockets'
    os.environ['OMP_PROC_BIND'] = 'FALSE'

and the five calculations are spread on five CPU, on computer B with the following characteristics:

Dell Inc. Precision Tower 5810 | 1 x Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (6 cores, 12 cores with Hyper-Threading) | 62.8GiB RAM | Linux-4.15.0-101-generic-x86_64-with-glibc2.10

Thank you very much for indicating these environment variables.

**Comment by craig-warren** [comment]
@asaintenoy, great, glad that helped!
