### ISSUE TITLE
Loading MALA X3M dataset in gprMax and visualizing it

### ISSUE THREAD

**Issue by tgautam03** [gprMax/gprMax#256]
Hi
I am just starting out a project in GPR imaging and looking for some opensource software to work with the dataset. I've downloaded [MALA X3M dataset](http://www.nsgg.org.uk/2018/geophysics-test-sites/) and will be eventually working with numpy so I was looking for something written in python. Right now, I want to understand the dataset but later I will be using gprMax for forward modeling on some synthetic models.
Thanks

**Comment by craig-warren** [comment]
@tgautam03 are you looking for open source software to process and visualise real Mala data? If so, thats not gprMax, it is for forward modelling and some basic plotting/display. In any case this is not really an issue with the code, you'd be better off re-posting in our Google Group (Forum) - http://www.gprmax.com/forum.shtml
