### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required.

### ISSUE THREAD

**Issue by timaou2020** [gprMax/gprMax#257]
Dears,

I tried to install gprMax. Everything went smooth until "python setup.py install". After execution it says:
building 'gprMax.fields_updates_ext' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
This happens although I have successfully installed Microsoft Build Tools 2015.

Thanks in advance for your kind assistance. 

Mohamed

**Comment by craig-warren** [comment]
@timaou2020 just to clarify, are you saying the build step (`python setup.py build`) completed OK? But this error came at the install stage (`python setup.py install`)? If so can you attached the complete traceback please.
