### ISSUE TITLE
Coordinate systems for 2D and 3D models

### ISSUE THREAD

**Issue by iod-ine** [gprMax/gprMax#258]
Isn't there a bit of a mismatch between coordinate systems for 2D and 3D? The way that the 3D coordinate system is oriented suggests that Z axis corresponds to depth, but 2D models use Y axis for depth instead.

I understand that it doesn't really makes a difference as far as simple models go, but the way I stumbled upon this thought is by trying to use realistic antennas with models created using `convert_png2h5` tool. It provides an option to extend the model in the Z direction, which becomes depth when using 3D models. I was hoping it would allow me to use a PNG as a X-Z plane cross-section and extend it in Y direction.

**Comment by agianno** [comment]
@iod-ine gprMax uses a right hand Cartesian coordinate system and has no preconception of any axis being denoted as a "depth" one. This allows the solver to be used as a general FDTD EM simulator. It is easy to arrange depth in any way you want.

**Comment by iod-ine** [comment]
@agianno thanks! I understand that gprMax itself does not depend on the concept of "depth". I should have worded my problem differently.

I was trying to create a 3D model using `convert_png2h5` and a GSSI antenna, and the problem is that the antenna is oriented assuming that Z axis is depth, while the result of `convert_png2h5 -zcells 100` is invariant along the Z axis. I need to either rotate the medium or the antenna about the X axis for them to align. Is there a way of doing that maybe?

**Comment by craig-warren** [comment]
@iod-ine I'd suggest you look at editing the `convert_png2h5` script. It was really designed as a rough and ready solution to get people started, and certainly not fully featured.

**Comment by agianno** [comment]
@iod-ine  To answer your question in more detail: Historically I used "z" as the invariance direction for 2D modelling and hence for no good reason we have stuck with this as any axis would have been an equivalent choice. Obviously this is not a choice that everyone needs to follow.  Some of the rough and ready tools as @craig-warren pointed out were developed to help some modelling challenges have followed this axis choice as well. It is easy to translate coordinates but I agree that in this case the user needs some ability to script or modify scripts. The short answer is that the PNG tool was meant only for 2D models and the full antenna model works in the 3D code only. Using the 2D PNG model creation tool with an extended invariance direction with a view to a 3D modelling problem might create responses in such a model that are not what expected and not natural. It is OK to try as far as the limitations are understood and are clear. The final answer is that there is no easy way to do so without translating coordinates via a script of either the antenna model or in the PNG based 2D model generator.

**Comment by iod-ine** [comment]
@agianno @craig-warren thank you very much!
