### ISSUE TITLE
Number of processors to run on - Error in German OpenSuse Linux

### ISSUE THREAD

**Issue by mark471182** [gprMax/gprMax#26]
Hi Craig,
When I run gprMax on a Linux server with a german version of openSUSE, I get the following Error message:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/loewer/gprMax/gprMax/__main__.py", line 4, in <module>
    main()
  File "/home/loewer/gprMax/gprMax/gprMax.py", line 130, in main
    run_model(args, modelrun, numbermodelruns, inputfile, inputdirectory)
  File "/home/loewer/gprMax/gprMax/gprMax.py", line 163, in run_model
    process_singlecmds(singlecmds, multicmds, G)
  File "/home/loewer/gprMax/gprMax/input_cmds_singleuse.py", line 86, in process_singlecmds
    corespersocket = int(corespersocket[0].split(':')[1].strip())
IndexError: list index out of range

In the python script 'input_cmds_singleuse.py' the number of cores per socket is calculated by searching for the string 'Core(s) per socket'. In my openSUSE version all entries in 'lscpu' are in german ('Kerne pro Sockel'), so the english string 'Core(s) per socket' is never found and an error above is dropped.

My interim solution was to run in the 'else' procedure by changing the name 'linux' to sth random.

Cheers
Markus

**Comment by craig-warren** [comment]
Hi Markus,

I think I corrected this 5 days ago in the beta 15 release. Give it a try and let me know.

**Comment by mark471182** [comment]
Hi Craig,
Sorry, my mistake. The new release solved the problem!
Thank you!

**Comment by craig-warren** [comment]
Don't worry the code is getting updated on an almost daily basis at the moment so it is hard to keep up!
