### ISSUE TITLE
First use of gprMax on CentOS7.8 : failure on user_models/cylinder_Ascan_2D.in

### ISSUE THREAD

**Issue by cessenat** [gprMax/gprMax#261]
Kaliméra, Hello ;
I just installed gprMax on CentOS7.8 using Miniconda for Python3.
gprMax build and setup went smoothly.
But, when testing the first example, I get an error and no output file user_models/cylinder_Ascan_2D.out produced:
python -m gprMax user_models/cylinder_Ascan_2D.in
<<
=== Electromagnetic modelling software based on the Finite-Difference Time-Domain (FDTD) method =====================

    www.gprmax.com   __  __
     __ _ _ __  _ __|  \/  | __ ___  __
    / _` | '_ \| '__| |\/| |/ _` \ \/ /
   | (_| | |_) | |  | |  | | (_| |>  <
    \__, | .__/|_|  |_|  |_|\__,_/_/\_\
    |___/|_|
                     v3.1.5 (Big Smoke)

 Copyright (C) 2015-2019: The University of Edinburgh
 Authors: Craig Warren and Antonis Giannopoulos

 gprMax is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
  version.
 gprMax is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
  details.
 You should have received a copy of the GNU General Public License along with gprMax.  If not, see
  www.gnu.org/licenses.
Traceback (most recent call last):
  File "/home/iliana/miniconda3/envs/gprMax/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/iliana/miniconda3/envs/gprMax/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/iliana/Softs/gprMax-v.3.1.5/gprMax/__main__.py", line 6, in <module>
    gprMax.gprMax.main()
  File "/home/iliana/Softs/gprMax-v.3.1.5/gprMax/gprMax.py", line 67, in main
    run_main(args)
  File "/home/iliana/Softs/gprMax-v.3.1.5/gprMax/gprMax.py", line 123, in run_main
    hostinfo = get_host_info()
  File "/home/iliana/Softs/gprMax-v.3.1.5/gprMax/utilities.py", line 317, in get_host_info
    osversion = 'Linux (' + osrelease + ', ' + platform.linux_distribution()[0] + ')'
AttributeError: module 'platform' has no attribute 'linux_distribution'
>>
Some info about my system:
(gprMax) [iliana@centos7 gprMax-v.3.1.5]$ uname -a
Linux centos7 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Thank you if you can help me ; your software seems so great, I would be very glad to test it and then use it.
Olivier Cessenat

**Comment by craig-warren** [comment]
@cessenat if you update gprMax the issue should resolve. I fixed it about 4 months ago as newer versions of Python don't have the `linux_distribution` function in the `platform` package any more.
