### ISSUE TITLE
setup.py build error

### ISSUE THREAD

**Issue by zhangxiaowei-c** [gprMax/gprMax#263]
the mainly problem is 
`can not open include file:'limit.h':no such file or directory`

**Comment by craig-warren** [comment]
@zhangxiaowei-c suggests a problem with your compiler. What platform are you using? What compiler are you using?

**Comment by zhangxiaowei-c** [comment]
The platform I using is windows  \system32,and the compiler is vc that I downlaoded from this github website. There might be something wrong?

**Comment by craig-warren** [comment]
@zhangxiaowei-c If you followed the instructions carefully step-by-step you shouldn't have a problem. We have a lot of Windows users who have successfully installed, and are using, gprMax. A screenshot of the full error message may help us diagnose the issue.

**Comment by zhangxiaowei-c** [comment]
I install again today, and find a new mistake like the screenshot. Please have a look and help me find a good way to install all of this. Thanks!
![error](https://user-images.githubusercontent.com/67144851/85246402-1dacd880-b47d-11ea-9aba-308ba0c37df6.png)

**Comment by zhangxiaowei-c** [comment]
![2](https://user-images.githubusercontent.com/67144851/85253029-d67c1300-b48f-11ea-90e3-77dcfc2959ee.png)
and then if I continue installing,there are also mistakes.

**Comment by zhangxiaowei-c** [comment]
and then if I continue installing, there are also mistakes.
![2](https://user-images.githubusercontent.com/67144851/85253203-396daa00-b490-11ea-9f6b-cbfe4cc6c745.png)

**Comment by zhangxiaowei-c** [comment]
and then if I continue installing, there are also mistakes.
![2](https://user-images.githubusercontent.com/67144851/85253438-bd279680-b490-11ea-8555-77f61a4b84fb.png)

**Comment by craig-warren** [comment]
@zhangxiaowei-c neither of these errors is directly to do with gprMax. The first one has to do with creating your Anaconda (miniconda) Python environment and the QT package. The second error looks like you have not installed [Microsoft Visual C++ 2015 Build Tools](http://download.microsoft.com/download/5/F/7/5F7ACAEB-8363-451F-9425-68A90F98B238/visualcppbuildtools_full.exe) correctly, in particular the **Use the custom installation option and deselect everything apart from the Windows SDK for your version of Windows**, i.e. if you are using Windows 10 you must install the Windows 10 SDK.

**Comment by zhangxiaowei-c** [comment]
QT package? I don't have the step. How to install it? Besides I followed the instructions to install all of those. And what I use is windows 7, and I don't chose the custom installation.

**Comment by craig-warren** [comment]
@zhangxiaowei-c the QT package is a dependency that will be automatically installed with the conda environment. I don't have a Windows 7 machine to test with, but I would choose the custom installation and de-select everything to ensure you are not installing a SDK for another version of Windows.

**Comment by zhangxiaowei-c** [comment]
chose the custom installation? and de-select things? I have both windows 7 and windows 10, does this have a impact on this?

**Comment by craig-warren** [comment]
@zhangxiaowei-c you only need the SDK for the version of Window you have. Don't install anything else as it will likely complicate the issue.

**Comment by zhangxiaowei-c** [comment]
ok, I will have a try. Thanks!

**Comment by whimian** [comment]
> ok, I will have a try. Thanks

You should keep "win8.1 SDK" checked even when you are installing on Windows 7 system.
