### ISSUE TITLE
Unable to use gprMax for gpu

### ISSUE THREAD

**Issue by LKOH016** [gprMax/gprMax#265]
Hi All

I have problems using my gpu for gprMax i am currently using a nvdia GTX 1050. I have downloaded cuda version 11 and pycuda. and set all the environmental variables for CUDA and the the C++ compiler. After which i get an error something like this.
![image](https://user-images.githubusercontent.com/55086560/95287482-930bb000-0898-11eb-8a06-789f197b62e1.png)
I then downgraded cuda verison 10 and reinstall everything else the same and added the enviromnetal variables. I then got this issue
![image](https://user-images.githubusercontent.com/55086560/95287653-07deea00-0899-11eb-86fc-b69b22639a7a.png)
Below i have attahed my user enviromental variables
![image](https://user-images.githubusercontent.com/55086560/95287716-35c42e80-0899-11eb-8f89-3dcc2efe6797.png)
Do i need cudNN installed as well?

**Comment by craig-warren** [comment]
Issue solved (I believe) through forum post - https://groups.google.com/g/gprmax/c/x5rdS0rvAPs/m/Oa0YQ_hODAAJ
