### ISSUE TITLE
Error in H_z in Hertzian dipole in free space

### ISSUE THREAD

**Issue by asemam** [gprMax/gprMax#267]
I followed the Analytical comparisons for Hertzian dipole in free space as described in 
http://docs.gprmax.com/en/latest/comparisons_analytical.html

But I got a large error in the Hz. The error was around 10^5.  
I used plot_Ascan.m to plot the output. 
![rx1x](https://user-images.githubusercontent.com/43624381/96628838-9d31a380-12c7-11eb-8f16-9f42a18ebbf3.png)

The error only in Hz; the other components match the analytical solution. The Hz values should be zero.

**Comment by jasminium** [comment]
The analytical solution should be 0 in the Hy component. However, this is a numerical calculation and as such, there is an error due to the precision of the numbers stored during the calculation. If you compare your error ~10^5 with the Ez ~10^11 Things are not so bad.
