### ISSUE TITLE
miniconda install

### ISSUE THREAD

**Issue by ELEGER** [gprMax/gprMax#27]
Hi,
first of all great job for the miniconda install it is much easier,
However, after building it, I'm facing:
python -m gprMax user_models/cylinder_Ascan_2D.in
Traceback (most recent call last):
  File "/global/home/users/eleger/miniconda3/envs/gprMax/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/global/home/users/eleger/miniconda3/envs/gprMax/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/global/home/users/eleger/bin/gprMax-master/gprMax/__main__.py", line 3, in <module>
    from .gprMax import main
  File "/global/home/users/eleger/bin/gprMax-master/gprMax/gprMax.py", line 35, in <module>
    from gprMax.fields_update import *
ImportError: No module named 'gprMax.fields_update'

miniconda and gprmax installs runned very fine and smooth, nothing to declare.

Thanks!

e

**Comment by craig-warren** [comment]
Glad you like it! We are slowly working towards a smoother install process.

Can you remind me what platform you are on? Presumably you are following the developer route so have compiled the Cython extensions? or have you downloaded the pre-built extensions for your platform?

**Comment by ELEGER** [comment]
Hey,

I just get the last gprmax-master.zip,  conda env create -f conda_env.yml it and activate it.
Trying to get it build on a cluster, ubuntu64bits

cheers

e

**Comment by craig-warren** [comment]
OK, so follow step 4 to build the Cython extensions and you should be good to go. The gcc (the C compiler with OpenMP support) should already be installed on Ubuntu.

**Comment by ELEGER** [comment]
yeah, but still not:

#
# To activate this environment, use:
# $ source activate gprMax
#
# To deactivate this environment, use:
# $ source deactivate
#
[eleger@n0001 gprMax-master]$ source activate gprMax
discarding /global/home/users/eleger/miniconda3/bin from PATH
prepending /global/home/users/eleger/miniconda3/envs/gprMax/bin to PATH
(gprMax)[eleger@n0001 gprMax-master]$ python -m gprMax user_models/cylinder_Ascan_2D.in
Traceback (most recent call last):
  File "/global/home/users/eleger/miniconda3/envs/gprMax/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/global/home/users/eleger/miniconda3/envs/gprMax/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/global/home/users/eleger/bin/gprMax-master/gprMax/__main__.py", line 3, in <module>
    from .gprMax import main
  File "/global/home/users/eleger/bin/gprMax-master/gprMax/gprMax.py", line 35, in <module>
    from gprMax.fields_update import *
ImportError: No module named 'gprMax.fields_update'


I'd say this is because I'm loading python3.2 (not 3.5) on the cluster could it be because of that ?

cheers

e

**Comment by craig-warren** [comment]
From the traceback you have Python 3.5. Did you follow step 4, i.e. compile the Cython extensions?

**Comment by ELEGER** [comment]
No, since I was building the endusers version.
Trying to compile the cython yields:
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    open(os.path.join(packagename, 'gprMax.py')).read(),
  File "/global/home/users/eleger/miniconda3/envs/gprMax/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 8733: ordinal not in range(128)


Thanks

e

**Comment by NishanthBhonsle** [comment]
Hello,
Facing a similar issue.
PFA screenshot of the error.
miniconda and gprMax installs were absolutely fine. But not able to simulate the sample Ascan.
![screenshot 29](https://cloud.githubusercontent.com/assets/11775797/12454645/6e1d2e2c-bfbe-11e5-9c13-9675da38d778.png)
Thank You

**Comment by craig-warren** [comment]
Hi NishanthBhonsle,

I think your issue is different. Can you confirm a few facts:

- What version of Windows are you using? Is it 32- or 64-bit?
- Have you copied the compiled Python extensions into the gprMax-v.3.0.0b18/gprMax directory? This was part of step 1. Get the code
- Can you post a listing of the gprMax-v.3.0.0b18/gprMax directory?

**Comment by NishanthBhonsle** [comment]
- I am using windows 8.1 64-bit version.
- Yes i have copied the extensions into the gprMax-v.3.0.0b18/gprMax directory.
PFA Screenshot of the directory.
![screenshot 30](https://cloud.githubusercontent.com/assets/11775797/12457420/5cd164ba-bfca-11e5-91b5-12bfa2be82a0.png)

In addition to these there are the following files
- yee_cell_build.pyx
- yee_cell_setget_rigid.cp35-win_amd64.pyd
- yee_cell_setget_rigid.pxd
- yee_cell_setget_rigid.pyx

Thank You.

**Comment by craig-warren** [comment]
@NishanthBhonsle I think Windows users may still have to install the Microsoft Visual Studio 2015 C++ Redistributable (``vc_redist.x64.exe`` for 64-bit) from https://www.microsoft.com/en-us/download/details.aspx?id=48145. Can you give that a try and let me know if that solves it.

@ELEGER I think I've fixed the issue you were having. It was to do with reading the version number. The fix is in the master branch, and I'll make a new release tomorrow.

**Comment by ELEGER** [comment]
Good job Craig,
Pulled the latest dev version and everything worked smoothly.
Thanks for you help (quick, efficient and clever), and I'm glad I could help to find a small bug.

e

**Comment by craig-warren** [comment]
@NishanthBhonsle Did installing the Microsoft Visual Studio 2015 C++ Redistributable solve the problem for you?

**Comment by NishanthBhonsle** [comment]
@craig-warren Was unable to download Microsoft Visual Studio 2015 C++ Redistributable due to various reasons.
So using GprMax on linux platform and it is working perfectly.
Thanks a lot and will update you if I am able to get Visual Studio on windows.

**Comment by craig-warren** [comment]
OK, thanks. From my testing it should work with the Redistributable installed on Windows. I'll close this issue for now, but if you come back to Windows and can't get it working then please open this issue up again.
