### ISSUE TITLE
Problem creating a context with pycuda on certain GPUs

### ISSUE THREAD

**Issue by Jooliee** [gprMax/gprMax#270]
I have installed gprMax on Windows 10 and it runs well on CPU. Then CUDA toolkit box and pycuda package were installed, and the path 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin' was also added into environment variable. But when running with GPU (Geforce RTX 2070 MQ), it fails to initiate the simulation,  just stop and exit the running. I have also tried reinstalling CUDA and gprMax but got the same problem. Any suggestions would be appreciated. Thanks.
![image](https://user-images.githubusercontent.com/53849688/98910920-c7f5cd00-24fe-11eb-89d0-e49003005e11.png)

**Comment by craig-warren** [comment]
@Jooliee can you do/check the following:

1. Can you take a screenshot of the 'Host:...' and 'GPU(s) detected:...' lines printed when gprMax runs please.
2. Can you check that you can use `nvcc` on your path
3. Can you post what is printed when you run `conda list`

The result of these should help us begin to diagnose your issues.

**Comment by Jooliee** [comment]
Thanks, Dr. Warren. I have checked as you suggested.

1. Here is the screenshot: 
![image](https://user-images.githubusercontent.com/53849688/99066729-6019b200-25e4-11eb-9106-0d0622dc62fc.png)

2. Yes, it has been added to environment variables, and here is the feedback when I run `echo %nvcc%`:
![image](https://user-images.githubusercontent.com/53849688/99067573-eb477780-25e5-11eb-8db6-0e43ed489099.png)

3. Here are all items shwon when I run `conda list`:
![image](https://user-images.githubusercontent.com/53849688/99066938-c7cffd00-25e4-11eb-9e4c-ddb23a6d8375.png)
![image](https://user-images.githubusercontent.com/53849688/99067224-4b89e980-25e5-11eb-8390-efbe0ec5498b.png)

**Comment by craig-warren** [comment]
@Jooliee that all looks OK. Can you try running some of the samples that come with CUDA. This should confirm that your GPU is working OK with CUDA outside of gprMax. They should be located at `C:\ProgramData\NVIDIA Corporation\CUDA Samples` More info is available at - https://docs.nvidia.com/cuda/cuda-samples/index.html#getting-started-with-cuda-samples

**Comment by Taoistyi** [comment]
@craig-warren  
Hi, Dr.Warren.
I am actually having the exactly same problem.
I also tried CUDA samples as you suggested,
but there is no problem with CUDA samples.
Best regards.

**Comment by craig-warren** [comment]
@Jooliee @Taoistyi can I check you are both using CUDA 11 on Windows 10 with a NVIDIA Geforce RTX 2070 MQ?

**Comment by Jooliee** [comment]
I am.

> @Jooliee @Taoistyi can I check you are both using CUDA 11 on Windows 10 with a NVIDIA Geforce RTX 2070 MQ?

I am.

**Comment by craig-warren** [comment]
@Jooliee @Jooliee can you activate the gprMax conda environment, launch Python and test the following commands, i.e.


```
> conda activate gprMax
> python
```
```
import pycuda.driver as drv
from pycuda.compiler import SourceModule
drv.init()
dev = drv.Device(0)
ctx = dev.make_context()
```

**Comment by Jooliee** [comment]
Hi Dr. Warren, here is the result fyi:
![image](https://user-images.githubusercontent.com/53849688/99385151-848acc80-290b-11eb-98a5-e781e13baf25.png)

**Comment by craig-warren** [comment]
@Jooliee good, that suggests the GPU is being initialised OK in pycuda. I want you to insert a print statement into the gprMax code to see how much further we can get. Go to your installation of gprMax and edit the file `model_build_run.py` which is inside the gprMax folder. At line 589 add `print('GPU check')`. The run the `cylinder_Ascan_2D.in` model again and see if that line is printed.

**Comment by Jooliee** [comment]
`print('GPU check')` has been inserted:
![image](https://user-images.githubusercontent.com/53849688/99387332-c5381500-290e-11eb-856d-01b4a14a5aa8.png)
And seems like it wasn't printed after running  `python -m gprMax cylinder_Ascan_2D.in -gpu`
![image](https://user-images.githubusercontent.com/53849688/99387200-8b670e80-290e-11eb-9766-3a08416ce855.png)
![image](https://user-images.githubusercontent.com/53849688/99387484-0c260a80-290f-11eb-8027-3433dee48e3a.png)

**Comment by craig-warren** [comment]
@Jooliee the print statement must be tabbed to the same indent as lines 588 and 590, that is how Python works.

**Comment by Jooliee** [comment]
Thanks for reminding. Have tried again and still no printing.

**Comment by craig-warren** [comment]
@Jooliee OK so you need to try moving the print statement to various places within the `solve_gpu` function to find where the function is failing. I suggest starting at line 503, if you don't see it printing at that position then something more fundamental is wrong.

**Comment by ChiaraD1994** [comment]
Hi, Dr.Warren.
I am actually having the exactly same problem.
I tried to add the line "print('GPU check')" at line 503, and I didn't see anything in the cmd.

I'm  using CUDA 11 on Windows 10 with a NVIDIA Geforce RTX 1650 MQ

Thanks in advance.

**Comment by Jooliee** [comment]
@craig-warren Thank you, but still no printing after moving the statement to line 503.

**Comment by Taoistyi** [comment]
@craig-warren
Hi, thank you for your reply.
Firstly, I am using quadro RTX 4000.
Also I tried your solutions in above,
and almost same results are obtained as Jooliee and ChiaraD1994.

By changing the position of print command,
it is found that line 502 cause some problems.
 ctx = dev.make_context()
after this line, the program stopped and return to a null result.

Best regards.

**Comment by wkang2072** [comment]
Hi, Dr. Warren.
I am also having exactly the same problem as above.
I tried to add the line "print('GPU check')" both at lines 503 and 589, but I saw nothing in the cmd.
I'm using CUDA 10.0 on Windows 10 with an NVIDIA Geforce GTX 980.

Best regards.

**Comment by craig-warren** [comment]
Hi all,

This seems like a recent issue, and since there have not been any updates to gprMax in a while, we need to try and ascertain what the source of the issue is. So far everyone reporting the issue is using Windows 10 with either CUDA 10 or 11, and it is with the following GPUs:

Geforce GTX 1650 MQ
Geforce GTX 980
Geforce RTX 2070 MQ
Quadro RTX 4000

Can everyone confirm the following steps do not result in any error:

```
> conda activate gprMax
> python
```
```
import pycuda.driver as drv
from pycuda.compiler import SourceModule
drv.init()
dev = drv.Device(0)
ctx = dev.make_context()
ctx.pop()
del ctx
```

Next can you go to the module `exceptions.py` and comment (with a hash symbol) line 26, i.e. `# sys.tracebacklimit = None`. Then please try and run the `cylinder_Ascan_2D.in` example with the `-gpu` flag.

**Comment by ChiaraD1994** [comment]
Thank you Dr. Warren.

I followed your reccomandations, but after the line "ctx = dev.make_context()" in cmd, the program stopped and returned to a null result, so I wasn't able to write the next two lines: 
ctx.pop()
del ctx

I also tried to comment line 26 in the module "exceptions.py" and then to run the "cylinder_Ascan_2D.in" with the -gpu flag, but also this time the program stopped and returned to a null result.

Best regards.

**Comment by Jooliee** [comment]
> Thank you Dr. Warren.
> 
> I followed your reccomandations, but after the line "ctx = dev.make_context()" in cmd, the program stopped and returned to a null result, so I wasn't able to write the next two lines:
> ctx.pop()
> del ctx
> 
> I also tried to comment line 26 in the module "exceptions.py" and then to run the "cylinder_Ascan_2D.in" with the -gpu flag, but also this time the program stopped and returned to a null result.
> 
> Best regards.

Hi Dr. Warren, I got exactly the same results.

**Comment by craig-warren** [comment]
Dear all, 

Can you test the attached pycuda example (you will need to change the file extension from `.txt` to `.py`. It should be run as follows:
```
conda activate gprMax
python dump_properties.py
```

[dump_properties.txt](https://github.com/gprMax/gprMax/files/5565610/dump_properties.txt)

**Comment by ChiaraD1994** [comment]
Thank you Dr. Warren, 
I attached the cmd result.

![Screen1](https://user-images.githubusercontent.com/74616300/99646370-ad68aa00-2a50-11eb-9535-592fbb30f1ab.png)
![Screen2](https://user-images.githubusercontent.com/74616300/99646373-ae99d700-2a50-11eb-9f5c-5ab9563c94a9.png)

**Comment by Jooliee** [comment]
Hi Dr. Warren, here are my results:
![image](https://user-images.githubusercontent.com/53849688/99646937-14f01b00-2a8c-11eb-9069-5ba882cc9447.png)
![image](https://user-images.githubusercontent.com/53849688/99646984-220d0a00-2a8c-11eb-85d0-8c046e9963f8.png)

**Comment by craig-warren** [comment]
OK, so it appears that the issue is around [`creating a context`](https://documen.tician.de/pycuda/driver.html#pycuda.driver.Device.make_context) on the device. Can you try the following test script (again you'll need to change `.txt' to `.py`
[test_context.txt](https://github.com/gprMax/gprMax/files/5566738/test_context.txt)
If working correctly the results should look similar to the following:
```
(gprMax) Craigs-Mac-Pro:gprMax cwarren$ python ~/Desktop/test_context.py 
Found device: GeForce GTX 1060 6GB
Trying to create context....
Context created on device: GeForce GTX 1060 6GB
Context removed.
End of test
(gprMax) Craigs-Mac-Pro:gprMax cwarren$ 
```

**Comment by Jooliee** [comment]
Yes you are right, seems like something went wrong aroud `creating a context:`
![image](https://user-images.githubusercontent.com/53849688/99667829-e718cf80-2aa7-11eb-84bc-c75cb2bef0ef.png)

**Comment by ChiaraD1994** [comment]
Hi Dr. Warren, I got exactly the same results.
![Screen](https://user-images.githubusercontent.com/74616300/99675764-e6684500-2a77-11eb-8be8-67958dcc5716.png)

**Comment by craig-warren** [comment]
OK, can you try the following test script (again you'll need to change `.txt' to `.py`) which uses [a new way of creating a context with pycuda](https://documen.tician.de/pycuda/driver.html#pycuda.driver.Device.retain_primary_context):
[test_context_new.txt](https://github.com/gprMax/gprMax/files/5567363/test_context_new.txt)

**Comment by ChiaraD1994** [comment]
Thank you Dr. Warren for the patience,
but in my case also this code doesn't work..
![Screen1](https://user-images.githubusercontent.com/74616300/99680505-680ea180-2a7d-11eb-9a95-eb0864e5d09c.png)

**Comment by Jooliee** [comment]
> Thank you Dr. Warren for the patience,
> but in my case also this code doesn't work..
> ![Screen1](https://user-images.githubusercontent.com/74616300/99680505-680ea180-2a7d-11eb-9a95-eb0864e5d09c.png)

Hi Dr. Warren, I got the same result with Chiara.

**Comment by craig-warren** [comment]
@ChiaraD1994 @Jooliee can you try running with the Python debugger (pdb), e.g. `python -m pdb ~/Desktop/test_context_new.py`. When you get the `Pdb` prompt hit `c` and enter. This is what the output looks like if working correctly:
```
(gprMax) Craigs-Mac-Pro:gprMax cwarren$ python -m pdb ~/Desktop/test_context_new.py
> /Users/cwarren/Desktop/test_context_new.py(1)<module>()
-> import pycuda.driver as drv
(Pdb) c
Trying to create context....
Context created on device: GeForce GTX 1060 6GB
Context removed.
End of test
The program finished and will be restarted
> /Users/cwarren/Desktop/test_context_new.py(1)<module>()
-> import pycuda.driver as drv
(Pdb)
```

**Comment by ChiaraD1994** [comment]
Hi Dr. Warren,
this is the result..I don't know what should be the problem..
![Immagine 2020-11-20 165505](https://user-images.githubusercontent.com/74616300/99820510-2a7b4880-2b51-11eb-8fa5-2468bf3e5da1.png)

**Comment by Jooliee** [comment]
Hi Dr. Warren, I got the same result.
![image](https://user-images.githubusercontent.com/53849688/99862113-8b4b6500-2bd3-11eb-85e0-fb6bcbd38466.png)

**Comment by wkang2072** [comment]
Hi, Dr. Warren. Sorry for my late response.
I followed all your recommendations and got exactly the same results as others.

**Comment by wkang2072** [comment]
![gprMax_capture](https://user-images.githubusercontent.com/41602444/99935737-be911e00-2da4-11eb-960b-7c8031e5a467.jpg)

**Comment by craig-warren** [comment]
@ChiaraD1994 @Jooliee @wkang2072 please take a look at some advice from the author of the pycuda package here - https://github.com/inducer/pycuda/issues/212#issuecomment-730577223 in particular

> Do the CUDA SDK samples work on that machine? Particularly the one for the driver SDK?

**Comment by ChiaraD1994** [comment]
Hi Dr. Warren,
I saw the advices from the author of the pycuda package, and I tried to run the SDK samples (I also find this guide for the SDK samples https://hpc.oit.uci.edu/nvidia-doc/sdk-cuda-doc/doc/release/Getting_Started_With_CUDA_SDK_Samples.pdf ).

The initial examples, e.g BandwidthTest and deviceQuery, work correctly, because confirm that all necessary tests passed.
![Immagine 2020-11-23 123016](https://user-images.githubusercontent.com/74616300/99957335-d4441a80-2d87-11eb-99e9-d10e4ef8c295.png)
![Immagine 2020-11-23 123104](https://user-images.githubusercontent.com/74616300/99957337-d5754780-2d87-11eb-8b87-8c39a2708739.png)

**Comment by craig-warren** [comment]
@ChiaraD1994 thats positive, can you also try this example https://docs.nvidia.com/cuda/cuda-samples/index.html#cuda-context-thread-management as it uses the cuCtxCreate API call which may be the problematic one.

**Comment by ChiaraD1994** [comment]
This is the result

![Immagine 2020-11-23 131118](https://user-images.githubusercontent.com/74616300/99960758-90541400-2d8d-11eb-909d-2f773649b419.png)
![Immagine 2020-11-23 131204](https://user-images.githubusercontent.com/74616300/99960760-91854100-2d8d-11eb-90fc-da6a418eded3.png)

**Comment by fegy123** [comment]
I also meet this question,
just use cuda10.1.243，cudnn7.6.5，and pycuda-2020.1+cuda101-cp38-cp38-win_amd64.whl，and it does work
I think maybe it is because the latest version of pycuda can only support cuda10.1 but not cuda11

**Comment by wkang2072** [comment]
@Jooliee @craig-warren @Taoistyi @ChiaraD1994 @fegy123 

Hi, here I share my current status.
According to fegy123's comment, I tried to use different version of CUDA Toolkit and pycuda.
Basically I followed the steps documented in issue no. 162. 
[https://github.com/gprMax/gprMax/issues/162](url)
But there are two differences.
In step 4, I installed CUDA Toolkit 10.1.243 and
In step 6.3, I didn't type 'pip install pycuda' but 
'pip install pycuda-2020.1+cuda101-cp38-cp38-win_amd64.whl'

For now, I don't use cudnn, but it does work as the capture below. 
![capture_gprmax](https://user-images.githubusercontent.com/41602444/100969149-f6068400-3575-11eb-8a3e-2719137bc8bc.jpg)

Thank you so much for your information and
I also think this may be the problem of compatibility, but how can I find the matching
information between the version of pycuda and CUDA toolkit?

Best regards.

**Comment by fegy123** [comment]
> @Jooliee @craig-warren @Taoistyi @ChiaraD1994 @fegy123
> 
> Hi, here I share my current status.
> According to fegy123's comment, I tried to use different version of CUDA Toolkit and pycuda.
> Basically I followed the steps documented in issue no. 162. ([/issues/162](https://github.com/gprMax/gprMax/issues/162))
> But there are two differences.
> In step 4, I installed CUDA Toolkit 10.1.243 and
> In step 6.3, I didn't type 'pip install pycuda' but
> 'pip install pycuda-2020.1+cuda101-cp38-cp38-win_amd64.whl'
> 
> For now, I don't use cudnn, but it does work as the capture below.
> ![capture_gprmax](https://user-images.githubusercontent.com/41602444/100969149-f6068400-3575-11eb-8a3e-2719137bc8bc.jpg)
> 
> Thank you so much for your information and
> I also think this may be the problem of compatibility, but how can I find the matching
> information between the version of pycuda and CUDA toolkit?
> 
> Best regards.


Hi，use this to check the version information between cuda ，python and pycuda

https://www.lfd.uci.edu/~gohlke/pythonlibs/?cm_mc_uid=08085305845514542921829&cm_mc_sid_50200000=1456395916#pycuda

**Comment by Jooliee** [comment]
It works! Thank you so much @wkang2072 @fegy123  @craig-warren. That's what I've done:
(1) I degraded CUDA from 11.0 to 10.1;
(2) I reinstalled `pycuda` downloaded from [https://www.lfd.uci.edu/~gohlke/pythonlibs/?cm_mc_uid=08085305845514542921829&cm_mc_sid_50200000=1456395916#pycuda](url). Since I am using `Python 3.6`, I installed `pycuda-2020.1+cuda101-cp36-cp36m-win_amd64.whl`.

**Comment by craig-warren** [comment]
@Jooliee @Taoistyi @ChiaraD1994 @fegy123, I have had some more time to look into this, and I think I have solved the issue without having to download any pre-built binaries of pycuda. The issue seems to stem from the MS Build Tools for Visual Studio that we were recommending you use with gprMax, which was the 2015 version. If you use the 2019 version, with the latest version of CUDA (11.1), then you can install pycuda in the usual way and everything works. So if you want to do this I would recommend the following:

- Using Add/remove programmes, uninstall all previous versions of CUDA and components
- Using Add/remove programmes, uninstall all previous versions of MS Build tools and components
- Remove the gprMax conda environment using `conda env remove --name gprMax`
- Run `conda clean --all` to remove all cached packages
- Follow the revised gprMax install instructions for MS Build Tools for Visual Studio 2019 - http://docs.gprmax.com/en/latest/include_readme.html#microsoft-windows
- Download and install the latest version of CUDA (currently 11.1)
- Check environment variables to ensure paths are set for both MS Build Tools (required for things like cl.exe) and CUDA (required for nvcc)
- Re-create gprMax conda environment with `pycuda` line uncommented in `conda_env.yml` - `conda env create -f conda_env.yml`
- Activate new environment and test gprMax model with `-gpu` flag.

This process has now worked on both a desktop and laptop Windows 10 machine with different NVIDIA GPUs.

Please post feedback if you try it.
