### ISSUE TITLE
phase problem

### ISSUE THREAD

**Issue by Yanghappy1991** [gprMax/gprMax#272]
I use “GPRMAX v3.1.5” software to simulate ground penetrating radar to detect underground voids。
My input file：

#domain: 1.5 1.5 0.0015
#dx_dy_dz: 0.0015 0.0015 0.0015
#time_window: 35e-9

#material: 1.0 0 1.0 0 atmosphere
#material: 81.0 0.003 1.0 0 fresh_water
#material: 12.0 0.004 1.0 0 L1

#waveform: ricker 1 800e6 my_ricker

#hertzian_dipole: z 0.15 1.3 0 my_ricker
#rx: 0.25 1.3 0

#src_steps: 0.02 0 0
#rx_steps: 0.02 0 0

#box: 0 0 0 1.5 1.5 0.0015 atmosphere
#box: 0 0 0 1.5 1.3 0.0015 L1

#cylinder: 0.7 0.9 0 0.7 0.9 0.0015 0.25 atmosphere

Simulation results：PIC 1.A-SCAN and PIC2. B-SCAN：

PIC 1.A-SCAN

 
PIC2. B-SCAN

Issues 1：Definition of reflection coefficient：r=(\sqrt{\varepsilon_1}-\sqrt{\varepsilon_2})/(\sqrt{\varepsilon_1}+\sqrt{\varepsilon_2})-----------（1）；r：Reflection coefficient，\varepsilon_1：Relative permittivity of the first dielectric， \varepsilon_2：Relative permittivity of the second dielectric。The phase polarity of reflection wave mainly depends on the dielectric constant of the upper and lower layers，When the relative dielectric constant of the upper medium is larger than that of the lower medium, the reflection number is positive, the phase of the reflected wave is positive, which is consistent with the phase of the initial electromagnetic wave, and vice versa.
A shown in the input file：dielectric constant of the background medium \varepsilon_1=12，atmosphere \varepsilon_2=1。According to the definition formula of reflection coefficient (1)：The electromagnetic wave is projected from the surface to the top of the cavity, that is, the interface between the background medium and the air. Because of 12>1,,the reflection coefficient is r positive, so the phase of the reflected wave is positive, the phase of the reflected wave is not reversed, and it is consistent with the direct wave。For example，The initial phase of visible radar direct wave is positive (red-blue-red), the phase indicated by the blackest arrow in the A-SCAN is consistent with that of the top black arrow in the B-SCAN and the reflection coefficient formula.
At this point, one part of the electromagnetic wave is reflected at the top of the cavity, and the other part continues to propagate downward through the top of the cavity，To the bottom of the cavity, it can be considered as the interface between air and background media.Now atmosphere \varepsilon_2=1, dielectric constant of the background medium \varepsilon_1=12，Because of 12>1, According to the definition formula of reflection coefficient (1)，The reflection coefficient is negative, and the phase of the reflected wave at the bottom of the cavity should be opposite to that of the direct wave, which is negative (blue-red-blue). However, the phase is visible from the green arrow in figure A-SCAN, the phase is still positive, and the green arrow in the corresponding B-SCAN indicates that the phase is consistent, positive and the phase is not reverse. This is contrary to the reflection coefficient formula. Why?

**Comment by agianno** [comment]
This is not an issue with the code. For modelling questions please use the gprMax google discussion forum.
