### ISSUE TITLE
Difference in voltage source & transmission line models

### ISSUE THREAD

**Issue by zzq15966331060** [gprMax/gprMax#273]
I have installed the latest gprMax v3.1.5 on Linux.
According to "http://docs.gprmax.com/en/latest/examples_antennas.html"
I directly use the command "python -m tools.plot_antenna_params user_models/antenna_wire_dipole_fs.out"(Wire dipole antenna model) and the result is different from official documentation.
Besides, I have run another example "cylinder_Bscan_GSSI_1500.in". The result is also different. The amplitude of my result is half of the official result.
I think that maybe your antennas code have changed but your official documentation not.

Looking forward to your reply.

**Comment by craig-warren** [comment]
@zzq15966331060 thanks for your comments. Let me address both your points:

1. The example of the s-parameters from the wire dipole antenna (http://docs.gprmax.com/en/latest/examples_antennas.html#results) - can you explain what differences you observe between your output and the docs? I see a small change in the value of the s11 resonant peak (-40dB in docs versus -42dB with current code), but everything else looks similar.
2. The example of the B-scan with the GSSI 1.5GHz antenna model - thanks for spotting this. The original model used to produce the figure you saw in the docs used a transmission line source model. The current model uses a voltage source. These are clearly different source models which will give different results. I have updated the figure in the docs to match the output from the current antenna model which uses the voltage source - http://docs.gprmax.com/en/latest/examples_antennas.html#id4

**Comment by zzq15966331060** [comment]
Thank you for your reply.
I have figured out the second question. The new figure is similar to my result.
For the first question, there are some differences about the range of axis, but the values looks familiar. My main question is that there only show two figures, based on the command "python -m tools.plot_antenna_params user_models/antenna_wire_dipole_fs.out".
![image](https://user-images.githubusercontent.com/66564754/100097766-f927b300-2e97-11eb-884d-8dc6cabd2b80.png)
![image](https://user-images.githubusercontent.com/66564754/100097860-1c526280-2e98-11eb-87de-fa739ac44cb8.png)

**Comment by craig-warren** [comment]
@zzq15966331060 thats correct you can customise the plotting and turn on other plots (such as the input admittance) by editing the plotting script, for example see - https://github.com/gprMax/gprMax/blob/72071473375c0a2123c94f63387ec760ffa2e1d4/tools/plot_antenna_params.py#L374
