### ISSUE TITLE
The program is stuck when generating B scan data in batch with pycharm

### ISSUE THREAD

**Issue by yangkun-2020** [gprMax/gprMax#276]
When generating B-Scan data in batch in PyCharm, there is a random program freeze problem, which typically occurs when one of the models executes 99% of the time using the GPU, for example：
![image](https://user-images.githubusercontent.com/69704428/104536681-70d1bd00-5653-11eb-833e-3aeff9b7d773.png)
I don't know why it causes this problem, which seriously affects my batch generation of B-scan data,Can anyone answer this question？Here's my Python program：
`import numpy as np
import random
import h5py
import shutil
import matplotlib.pyplot as plt
from gprMax.gprMax import api
from tools.plot_Bscan import mpl_plot
from tools.outputfiles_merge import get_output_data, merge_files

def average_filter(f1):
    r = np.shape(f1)
    meanVal = np.mean(f1, axis=1).reshape(r[0], 1)
    new_Val = meanVal
    for _ in range(r[1] - 1):
        new_Val = np.hstack((new_Val, meanVal))
    outputdata = f1 - new_Val
    return outputdata

def two_dimensional_fourier(f1):
    fft_f1 = np.fft.fft2(f1)
    r = np.shape(fft_f1)
    filting = np.ones(r)
    filting[:, 0:3] = np.zeros((r[0], 3))
    fft_f1 = fft_f1 * filting
    ifft_f2 = np.fft.ifft2(fft_f1)
    outputdata = np.real(ifft_f2)
    return outputdata

def svd_pca(f1, sval_nums):
    u, s, v = np.linalg.svd(f1, full_matrices=False)
    img_restruct1 = (u[:, sval_nums:]).dot(np.diag(s[sval_nums:])).dot(v[sval_nums:, :])
    outputdata = img_restruct1
    return outputdata

if __name__ == "__main__":
    # f = open(r'C:\Users\Administrator\Desktop\Bscan_set\Drainage_concrete_pipe\uniform\batch_model.in', 'a+')
    # #f = open(r'C:\Users\Administrator\gprMax\batch_In_file\batch_model.in', 'a+')
    # a = f.tell()
    # f.close()
    for i in range(14, 30):
        f = open(r'C:\Users\Administrator\Desktop\Bscan_set\Drainage_concrete_pipe\uniform\batch_model.in', 'w')
        cmd1 = '#domain: 4 1.5 0.002\n'
        cmd2 = '#dx_dy_dz: 0.002 0.002 0.002\n'
        cmd3 = '#time_window: 80e-9\n'
        cmd4 = '#waveform: ricker 1 0.2e9 my_ricker\n'
        cmd5 = '#hertzian_dipole: z 0.200 1.300 0 my_ricker\n'
        cmd6 = '#rx: 0.240 1.300 0\n'
        cmd7 = '#src_steps: 0.012 0 0\n'
        cmd8 = '#rx_steps: 0.012 0 0\n'

        center_y = round(random.uniform(0.4, 0.7), 3)
        center_x = round(random.uniform(1, 3), 3)
        inside_R = round(random.uniform(0.100, 0.250), 3)
        concrete_E = round(random.uniform(8.8, 10.2), 2)
        water_E = round(random.uniform(79, 81.1), 2)
        uniform_soil_E = round(random.uniform(4, 6.3), 2)
        cmd9 = '#material: {i} 0.000001 1 0 uniform_soil\n'.format(i=uniform_soil_E)
        cmd10 = '#material: {i} 0.0001 1 0 concrete\n'.format(i=concrete_E)
        cmd11 = '#material: {i} 0.01 1 0 my_water\n'.format(i=water_E)
        cmd12 = '#box: 0 0 0 4 1.2 0.002 uniform_soil\n'
        cmd13 = '#cylinder: {x} {y} 0 {x} {y} 0.002 {r} concrete\n'.format(x=center_x, y=center_y, r=round(inside_R+0.038, 3))
        cmd14 = '#cylinder: {x} {y} 0 {x} {y} 0.002 {r} free_space\n'.format(x=center_x, y=center_y, r=inside_R)
        cmd15 = '#cylindrical_sector: z {x} {y} 0 0.002 {r} 180 180 my_water'.format(x=center_x, y=center_y, r=inside_R)
        f.write(cmd1)
        f.write(cmd2)
        f.write(cmd3)
        f.write(cmd4)
        f.write(cmd5)
        f.write(cmd6)
        f.write(cmd7)
        f.write(cmd8)
        f.write(cmd9)
        f.write(cmd10)
        f.write(cmd11)
        f.write(cmd12)
        f.write(cmd13)
        f.write(cmd14)
        f.write(cmd15)
        f.close()
        shutil.copy(r'C:\Users\Administrator\Desktop\Bscan_set\Drainage_concrete_pipe\uniform\batch_model.in',
                    r'C:\Users\Administrator\Desktop\Bscan_set\Drainage_concrete_pipe\uniform\model{}.in'.format(i))
        # api实现fdtd的B扫运行，并将结果文件整合并显示出来
        filename = r'C:\Users\Administrator\Desktop\Bscan_set\Drainage_concrete_pipe\uniform\batch_model.in'
        api(filename, n=300, gpu=[0])
        filename1 = merge_files(r'C:\Users\Administrator\Desktop\Bscan_set\Drainage_concrete_pipe\uniform\batch_model', i, removefiles=True)
        rxnumber = 1
        rxcomponent = 'Ez'
        outputdata, dt = get_output_data(filename1, rxnumber, rxcomponent)
        #信号去除直达波
        # outputdata = average_filter(outputdata)
        #outputdata = two_dimensional_fourier(outputdata)
        outputdata = svd_pca(outputdata, 1)
        fig = plt.figure(num='', figsize=(20, 10), facecolor='w', edgecolor='w', frameon=False)
        axes = fig.add_axes([0, 0, 1, 1])
        axes.set_axis_off()
        axes.imshow(outputdata, extent=[0, outputdata.shape[1], outputdata.shape[0] * 4.71731e-12, 0],
                        interpolation='nearest',
                        aspect='auto', cmap='gray', vmin=-np.amax(np.abs(outputdata)), vmax=np.amax(np.abs(outputdata)))
        plt.savefig(r'C:\Users\Administrator\Desktop\Bscan_set\Drainage_concrete_pipe\uniform\image{}.jpg'.format(i))
        plt.close()
`

**Comment by yangkun-2020** [comment]
My memory is 32GB,  CPU is i5-9600KF,   GPU is 1080ti --- 11GB
This is my code view：
![image](https://user-images.githubusercontent.com/69704428/104540016-a2e61d80-5659-11eb-9578-242fe9a4d8b6.png)
![image](https://user-images.githubusercontent.com/69704428/104540086-c27d4600-5659-11eb-9e56-cb8d52167b23.png)
![image](https://user-images.githubusercontent.com/69704428/104540147-db85f700-5659-11eb-955f-c76910435e70.png)

**Comment by craig-warren** [comment]
@yangkun-2020 I suspect it may have something to do with calling the gprMax `api` function within a for loop. Can you do a test with a single iteration of the for loop, and also removing it entirely.

**Comment by yangkun-2020** [comment]
> @yangkun-2020 I suspect it may have something to do with calling the gprMax `api` function within a for loop. Can you do a test with a single iteration of the for loop, and also removing it entirely.

This problem has been tentatively solved by me. When I turn off PyCharm and rerun it, I haven't found this problem so far. I suspect that my Python interpreter is running for a long time, causing some inexplicable error . Moreover, this error always occurs at 99% of the end of A-scan. At this time, the calculated field value data should be stored in the. Out file, but the program is stuck. I guess this is related to the IO stream of the file. The write IO stream of the file is occupied, resulting in the program always waiting, but I can't prove this point
