### ISSUE TITLE
Question regarding the installation instructions

### ISSUE THREAD

**Issue by samfux84** [gprMax/gprMax#279]
Hi,

I am trying to install gprMax on the HPC cluster of our university.

What confuses me a little bit are the installation instructions. They state

```
(gprMax)$ python setup.py build
(gprMax)$ python setup.py install
```

To me this looks like a standard installation with Python's distutils package. Usually for such installations one can remove the installation directory afterwards, because the package gets installed into the "site-packages" directory of the Python installation.

But later you mention:

`Open a Terminal (Linux/macOS) or Command Prompt (Windows), navigate into the top-level gprMax directory,`

This looks like gprMax needs to be built in-place and one needs to keep the installation directory. But when running "python setup.py install", some files are copied to the "site-packages" directory of the Python installation.

Do I need to keep the installation directory or are the files copied to the "site-packages" directory of the Python installation sufficient?

Any help is appreciated.

Thank you in advance.

Best regards

Sam

**Comment by craig-warren** [comment]
@samfux84, yes it should work fine from site-packages, although I haven't personally used it much this way.

**Comment by samfux84** [comment]
Thank you for your reply. I will then remove the installation directory.
