### ISSUE TITLE
miniconda missing mpi4py

### ISSUE THREAD

**Issue by ELEGER** [gprMax/gprMax#28]
Hi all,
Just to mention that after creating the environment with conda,
you have to install mpi4py package using conda, it is not there by default.

Cheers
e

**Comment by craig-warren** [comment]
Yes, at the moment `mpi4py` is not automatically installed in the Miniconda environment. Reason being it requires an install of Microsoft MPI 6 on Windows which we felt would be more confusing for the average user. On Linux and Mac OS X it should just install OpenMPI with `mpi4py`.

Please let me know how it goes with the MPI task farm functionality as this is a feature we have not been able to test much.

**Comment by GGDRriedel** [comment]
I just want to iterate on this: Installing openMPI is pretty straight forward throgh modern conda. 
It manages PIP as well now. 

so through its own anaconda environment I was able to get it running through: 

installing openmpi through PIP: 

```
pip install mpi4py
```

and then installing the python package as written here: 
https://anaconda.org/anaconda/mpi4py

Now I invoked an MPI process like written in 

http://docs.gprmax.com/en/latest/openmp_mpi.html

Works perfectly, currently frying my PC
