### ISSUE TITLE
gprMax uses a Python feature that has been deprecated in Python 3.5 and removed in Python 3.7

### ISSUE THREAD

**Issue by samfux84** [gprMax/gprMax#281]
Hi,

gprMax uses the following code:

`osversion = 'Linux (' + osrelease + ', ' + platform.linux_distribution()[0] + ')'`

According to

https://docs.python.org/3.5/library/platform.html#platform.linux_distribution

the platform.linux_distribution feature has been removed in Python 3.7

The replacement for platform.linux_distribution() is platform.dist() so the code would need to be changed to

`osversion = 'Linux (' + osrelease + ', ' + platform.dist()[0] + ')'`

Best regards

Sam

**Comment by craig-warren** [comment]
@samfux84 thanks for flagging but this was updated in gprMax about a year ago. Please pull the latest code.
