### ISSUE TITLE
gcc not found on Mac with M1 chip

### ISSUE THREAD

**Issue by eskimeow** [gprMax/gprMax#283]
I have got a new managed macbook (with the new apple silicon chip) from work. I installed Xcode, Homebrew and gcc with no problem. However, when I tried to execute `python setup.py build`, error comes out says `Cannot find gcc 4-10 in /usr/local/bin`. After some digging I found the gcc was installed in the `/usr/bin` folder instead of the `/usr/local/bin` folder. Also the installed gcc has no suffix but just `gcc` without a number, which corresponds to version 10 according to [homebrew](https://formulae.brew.sh/formula/gcc). I tried using `gccpath = glob.glob('/usr/bin/gcc*')`. The gcc can be found now but the rpath `/usr/local/opt/gcc/lib/gcc/c/` seems not right as I couln't find this location. Running the `python setup.py build` still not working. I am not quite familar with Linux, the windows version was easy to install and runs flawless for me.

**Comment by craig-warren** [comment]
@eskimeow thanks for spotting this. I don't have a Mac with a M1 chip to test with, but @agianno does, so may be able to assist.

**Comment by agianno** [comment]
Sadly as far as I know there is no working version of GCC for the M1 based Macs. I have one and have not managed to make it work. I had manage to install with homebrew but even if it compiles the executable produced is not working. I have tried various flags to set the processor to ARM architecture and this did not work either. It is planned that GCC 11 will have support for M1 but until then it is a game of wait and see if someone produces a working version but this will most likely mean compiling GCC from sources.

**Comment by eskimeow** [comment]
Many thanks for the information. I will stick with the windows version for now.

**Comment by jasminium** [comment]
Currently, from [homebrew](https://brew.sh/2020/12/01/homebrew-2.6.0/)

_We currently recommend running Homebrew using Intel emulation with Rosetta 2._

Possibly, you can right-click and open your terminal using Rosetta 2 and install the usual way. I haven't tested this but it may work for you! @agianno could we give this a go? I think this issue might start coming up (i'm also thinking of getting an m1!)

Another option is to run gprMax in a Docker container [here](https://github.com/jasminium/docker-gprmax) Though there are also M1 issues with Docker too!

**Comment by eskimeow** [comment]
> Currently, from [homebrew](https://brew.sh/2020/12/01/homebrew-2.6.0/)
> 
> _We currently recommend running Homebrew using Intel emulation with Rosetta 2._
> 
> Possibly, you can right-click and open your terminal using Rosetta 2 and install the usual way. I haven't tested this but it may work for you! @agianno could we give this a go? I think this issue might start coming up (i'm also thinking of getting an m1!)
> 
> Another option is to run gprMax in a Docker container [here](https://github.com/jasminium/docker-gprmax) Though there are also M1 issues with Docker too!

Thanks for the tips. Unfortunately I tried with no luck.
I tried the following:
1. install homebrew to rosetta2
```
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```
2. install gcc
```
arch -x86_64 brew install <package>
```

3. then run the build command
```
python setup.py build
```
or 
```
arch -x86_64 python setup.py build
```
4.Finally, I got the following error.
```
clang: error: unsupported option '-fopenmp'
error: command '/usr/bin/gcc' failed with exit code 1
```

**Comment by craig-warren** [comment]
I've updated `setup.py` to look for gcc on Macs with M1 CPUs in the correct place. I've tested this with hombrew installed gcc on a Apple Mac mini with M1 CPU, and it all seems to work now.
