### ISSUE TITLE
Missing Paraview Macro

### ISSUE THREAD

**Issue by hkuszmau** [gprMax/gprMax#284]
I can not find the gprMax_materials.py in the tools/Paraview macros directory. Where would it be?

**Comment by mzmmoazam** [comment]
I believe gprMax_materials.py was in an older version until v.3.0.0b20. If you want to get the geometry of your model, you can run gprMax using the optional command line argument `--geometry-only`. For more details check [docs](https://docs.gprmax.com/_/downloads/en/latest/pdf/) page no 28 - 29.

**Comment by craig-warren** [comment]
@hkuszmau the macro is called `gprMax_info.py` which you'll find here - https://github.com/gprMax/gprMax/blob/6f8838752dda57710998a4d45501daf1a7616e33/tools/Paraview%20macros/gprMax_info.py

As @mzmmoazam it was originally called `gprMax_materials.py` in an early version but the name changed.
