### ISSUE TITLE
Cant Build gprMax

### ISSUE THREAD

**Issue by rohdedm** [gprMax/gprMax#289]
I get these two errors when executing the python setup.py build. My path environment was set properly.

LINK : fatal error LNK1104: cannot open file 'build\lib.win-amd64-3.9\gprMax\pml_updates\pml_updates_magnetic_HORIPML_ext.cp39-win_amd64.pyd'

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\link.exe' failed with exit code 1104

**Comment by rohdedm** [comment]
The "build\lib.win-amd64-3.9\gprMax\pml_updates\pml_updates_magnetic_HORIPML_ext.cp39-win_amd64.pyd" file does not seem to exist in the build I doenloaded.

**Comment by craig-warren** [comment]
@rohdedm that file is not part of the gprMax package. What you download or pull from GitHub is the source code. Parts of it are then compiled with the compiler for your platform, which in your case is MS Windows. It looks like the MS linker cannot find that file during the linking stage, which suggests it was never built during the build stage.

**Comment by rohdedm** [comment]
Craig, thanks for the reply. So should I just try the build again?

thank you,
David

**Comment by craig-warren** [comment]
@rohdedm yes, and I would first check that `cl.exe` and `link.exe` are on your path.

**Comment by rohdedm** [comment]
I will do that.  thank you,
David

**Comment by rohdedm** [comment]
I was able to build and install gprMax and it's now running just fine. I had to uninstall and reinstall the Build Tools for Visual Studio -not sure what went wrong. I also reset the path just to be safe. It's all good now.
thank you,
David
