### ISSUE TITLE
snapshot error

### ISSUE THREAD

**Issue by mzunguman** [gprMax/gprMax#29]
Hello, 
I have an issue and questions regarding snapshots in 2D and 3D. An answer to my 2D problem might solve my 3D question, so the former first. With the 2D model below I get errors with creating snapshots in the xy-plane.

*#domain: 1.0 1.0 0.002
#dx_dy_dz: 0.002 0.002 0.002
#snapshot: 0.002 0.002 0 0.998 0.998 0.001 0.002 0.002 0.002 4e-9 snap1*

I always get an error concerning the lower or upper coordinates. I guess I'm not sure what the minimum/maximum coordinates may be with regard to the model extensions. For me, no alteration of the lower (0 or 0.002) or upper (0 or 0.002) coordinate works.

A further question I have is about the snapshot time. Does gprMax choose the closest time-step to it or does it interpolate?

Cheers,
Sam

[test_Stadler_2D.txt](https://github.com/gprMax/gprMax/files/104928/test_Stadler_2D.txt)

**Comment by craig-warren** [comment]
@mzunguman, there are 2 reasons for your example getting an error message:

1. Our bounds checking for the snapshots was incorrect for the 2D case - it should have been OK for 3D. I've fixed this in the master branch.
2. The upper bound of the snapshot in your model in the z-direction is 0.001, but your dz is 0.002.

gprMax rounds the requested snapshot time to the nearest timestep.

Let me how you get on. You should now be able to specify snapshots to the limits of the domain.

**Comment by mzunguman** [comment]
**@craig-warren**, thanks a lot for the speedy reply. the second error you read was in fact a typo from my part, the model didn't run with an upper z-bound of 0.002. I ran my set of models again though and now it works fine in 2D and 3D. 

Best regards, Sam
