### ISSUE TITLE
Not able to plot B-scan feeding a 'merged.out' file

### ISSUE THREAD

**Issue by saiteja-kuchipudi** [gprMax/gprMax#290]
I tried to model a very basic 2D box and tried plotting a B-scan. Merged all 40 src, rx positions into a 'merged.out' file. Tried running tools.plot_Bscan on the merged file in Ey direction. I am getting this error code>> KeyError: "Can't open attribute (can't locate attribute: 'nrx')". How should I move forward?
![Screenshot (19)](https://user-images.githubusercontent.com/69788462/126763601-812b4d64-c92b-4768-bdac-6ea0609a35ae.png)

**Comment by craig-warren** [comment]
@saiteja-kuchipudi most likely this is because you haven't merged your A-scans into a B-scan correctly, that is why the `nrx` attribute is missing.
