### ISSUE TITLE
User definied function as waveform

### ISSUE THREAD

**Issue by GaleonAD** [gprMax/gprMax#291]
I think that defining waveform with function defined by user can be useful. It skips the interpolation process and so improve performance in some cases. I have looked at the architecture of the package and I think the simplest way to add this is by extending functionality of the #extitation_file: command. 

User gives python file with function defined (function of time) and the functions from that file are loaded and used as waveforms.

What do you think?

**Comment by craig-warren** [comment]
@GaleonAD yes, it is something we have been talking about for a while now. It will likely be included in v.4 - definitely as part of the new Python API, and possible also as a hash command.

Craig
