### ISSUE TITLE
PEC Material for imported models 

### ISSUE THREAD

**Issue by GGDRriedel** [gprMax/gprMax#292]
I am importing model geometry from hdf file that contains the numbered matials in its space(0,1,2,...) 

Materials are imported through a materials file containing the materials with the corresponding ordering(0,1,2...)

Now. One material needs to be PEC.

however, i can't find a way to create such a material through the #material command. 

When I use inf for its permitivity and use it for a material in my model, I get an error since the corresponding objects are much smaller than the wavelength and essentially not sampled. 

How would I create a PEC that could be used in an imported model? 

Cheers

**Comment by craig-warren** [comment]
@GGDRriedel using `inf' for the conductivity should do it, the other parameters are then irrelevant as gprMax will set the FDTD update coefficients for PEC directly when it detects infinite conductivity.

Craig
