### ISSUE TITLE
Modelling a hollow circular section

### ISSUE THREAD

**Issue by saiteja-kuchipudi** [gprMax/gprMax#293]
I have been trying to model a concentric ring circumscribing a circle. All I can do is Putting one solid circle inside a big circle, so that it appears like I need. Can someone suggest me the way to model a hollow circular section (or a ring) using script supporting gprMax.
Thanks

**Comment by craig-warren** [comment]
This is not code related. Please post of out Google Group - https://groups.google.com/g/gprmax
