### ISSUE TITLE
Compatibiilty with ParaView 5.10

### ISSUE THREAD

**Issue by astroChance** [gprMax/gprMax#298]
I just installed gprMax and ParaView today (v5.10) today (Oct 10), and I received the following error when trying to open the 'cylinder_half_space.vti' file created by following your 'Day 1 - Introduction to gprMax' tutorial. I downgraded to ParaView 5.9.1 and did not receive the same error message when opening the created .vti file

```Traceback (most recent call last):
  File "C:\Program Files\ParaView 5.10.0-RC1-Windows-Python3.9-msvc2017-AMD64\bin\Lib\site-packages\paraview\servermanager.py", line 476, in __setattr__
    setter = getattr(self.__class__, name)
AttributeError: type object 'Threshold' has no attribute 'ThresholdRange'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 66, in <module>
  File "C:\Program Files\ParaView 5.10.0-RC1-Windows-Python3.9-msvc2017-AMD64\bin\Lib\site-packages\paraview\servermanager.py", line 482, in __setattr__
    _bc.setattr(self, name, value)
  File "C:\Program Files\ParaView 5.10.0-RC1-Windows-Python3.9-msvc2017-AMD64\bin\Lib\site-packages\paraview\_backwardscompatibilityhelper.py", line 397, in setattr
    raise NotSupportedException("The 'ThresholdRange' property has been "
paraview.NotSupportedException: The 'ThresholdRange' property has been removed in ParaView 5.10. Please set the lower and upper thresholds using the 'LowerThreshold' and 'UpperThreshold' properties, then set the 'ThresholdMethod' property to 'vtkThreshold.THRESHOLD_BETWEEN' to threshold between the lower and upper thresholds.```

**Comment by craig-warren** [comment]
@astroChance thanks for flagging this. Looks like the way the Threshold property is defined has changed in Paraview 5.10. This is breaking the gprMax/Paraview macro. I will try to take a look at this in the next few weeks.

Craig

**Comment by craig-warren** [comment]
@astroChance I've updated the gprMax/Paraview macro which has fixed this.

**Comment by WinkZh** [comment]
My version is 5.10 too, I also met this problem, how can I repair it? It wasn' t repaired.

**Comment by craig-warren** [comment]
@WinkZh update to latest gprMax and then remove and readd the macro in Paraview.
