### ISSUE TITLE
Command for Geometry view

### ISSUE THREAD

**Issue by rajathkumarmp** [gprMax/gprMax#30]
Was following the docs: http://docs.gprmax.com/en/latest/examples_simple_2D.html

How do we plot the fig 15 "Geometry of a 2D model of a metal cylinder buried in a dielectric half-space."?

**Comment by craig-warren** [comment]
Geometry and snapshot files - http://docs.gprmax.com/en/latest/geometry_snapshots.html

**Comment by rajathkumarmp** [comment]
@craig-warren 

while creating snapshot

xs, ys, zs  are the lower left (x,y,z) coordinates of the volume of the snapshot in metres and xf, yf, zf are the upper right (x,y,z) coordinates of the volume of the snapshot in metres.

what is the "volume of the snapshot" ?

**Comment by craig-warren** [comment]
@rajathkumarmp, always happy to help, but please try to read the documentation first. There is information about the snapshot command at: http://docs.gprmax.com/en/latest/input.html#snapshot

Additionally make sure you have the latest code, as we fixed a bug with the snapshot command limits #29 recently.

**Comment by rajathkumarmp** [comment]
@craig-warren  that was a silly doubt. Understood. Thank you.

But the geometry .vti file does not show the tx and rx. Not a necessity but would be a nice add on.
