### ISSUE TITLE
Building gprMax with the newest version of the Build Tools for Visual Studio 2022

### ISSUE THREAD

**Issue by eyoabz** [gprMax/gprMax#303]
Hello

It seems like the Build Tools for Visual Studio 2019 mentioned in your installation instruction is no longer available. Is Build Tools for Visual Studio 2022 going to work fine? 

Also, if not too much bother, to set the Path and environment as follow "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.30.30705\bin\Hostx64\x64" . Where do you add the form.

Thank you in advance for your help.

Kind Regards

Eyoab

**Comment by craig-warren** [comment]
@eyoabz I've checked VS Build Tools 2022 with gprMax on Windows 10 and they work fine. The readme has been updated to reflect this. Thanks. Just Google to find how to set the Path environment variable in Windows.

**Comment by eyoabz** [comment]
Thank you for your quick response. It worked out well.

Regards
