### ISSUE TITLE
New 400MHz Antenna

### ISSUE THREAD

**Issue by mzunguman** [gprMax/gprMax#31]
**@craig-warren** or whomever has information. 

For my work, I am interested in modelling the 400MHz GSSI Antenna, which has a similar build-up as your pre-made 1.5GHz GSSI Antenna. By modifying the dimensions (which we sort of have for the 400MHz antenna) I plan to use your exising model. It is however quite time consuming to reverse engineer and understand the antenna dimensions from a geometry and the antenna.py file, at least for me that is. Do you maybe have some sort of schematic with the dimensions written down which I could use? If successful and in case you're interested, I would be glad to commit my efforts.

Cheers,
Sam

**Comment by craig-warren** [comment]
@mzunguman, the `antennas.py` module, geometry files, and also my PhD thesis (http://hdl.handle.net/1842/5614) are your best sources for details and dimensions of the antenna models. I'm afraid I don't have information in any other useful format.

Good luck with you modelling, and of course it would be nice if you can commit the final model to our library.

**Comment by mzunguman** [comment]
** @craig-warren**, thanks a lot for the help. I'm sure this can help me and I'll be in touch when I have further questions.

Cheers

**Comment by mzunguman** [comment]
**@craig-warren**

I have a question concerning the modelling of the Rx & Tx bowties, please correct me if I'm wrong. In the 1.5GHz Antenna, you achieved this by using multiple plate commands, and placing the feed wire horizontally between the 3mm space between the two bowtie-halves. 

Have you tried doing this with a triangle command? The problem would be to model the 2mm tip of the bowtie. I guess to do this I could model on top of the triangle, a 2mm long plate. 

Cheers

**Comment by craig-warren** [comment]
@mzunguman, Yes I used plates, you can use triangles also. When it is important to set detail down to single cells, using a plate is more reliable than the triangle (the algorithm for setting cells based on a triangle will sometimes set a cell that you don't want, or not set one that you do).

For the 1mm resolution model: I used the edge command to create 2 x 1mm 'wires' to connect to the arms of the bowtie on either side of a 1mm gap where the source was placed.

For the 2mm resolution model: There were no edges (wires), just a 2mm gap where the source was placed.

**Comment by mzunguman** [comment]
**@craig-warren**, I think I have accurately modelled the geometry of a 400MHz GSSI antenna, but now I have a few questions regarding the implementation of the taguchi optimisation process. The problem is that the radiated field doesn't correlate well with real data I have. I am looking at the normalised amplitudes and the crosstalk response. Most importantly, the center-frequency of the wavelet has to be increased. Is the taguchi opt. process working at the moment? If so, do you think I could effectively use it to optimize the material properties?

**Comment by craig-warren** [comment]
@mzunguman, glad to here your are progressing. Can you (if you are willing) post a plot of the results?

I am currently developing the Taguchi optimisation procedure inside gprMax, which you may have noticed. It is not yet ready for primetime, hence why there is no documentation as yet. If you can figure out how to use it from the code, feel free to give it a try. I would think it will be another few weeks before I have finished implementing/checking and can start documenting how to use it.

**Comment by mzunguman** [comment]
**@craig-warren**, Thanks for the reply. I will see how far I get with the taguchi optimisation. Regarding the antenna, Heres a geometry view of it. I don't actually know what the insides look like, I took a good guess from what I know of 200MHz and 1.5 GHz antennas. I don't know how tall the metal casing inside the box is, and the dimensions of the pcb plate. So I took your model of the 1.5GHz antenna and adpated the dimensions. So far the crosstalk has a lower frequency than it should have. At the moment I'm playing with some parameters.

[antenna2.pdf](https://github.com/gprMax/gprMax/files/148011/antenna2.pdf)

**Comment by mzunguman** [comment]
**@craig-warren**, I am currently looking into the taguchi optimisation code and I might be able to use it in a few weeks time but until then I want to ask you some things. I do in fact need some quantitatively better data, with regards to the antenna adaptation, within the next two weeks for a presentation of mine. 

Assuming (which might be erronous still) that the geometry is right, the permittivity of the absorber should be the most influential parameter I think. Or else, what do you suggest to "play" around with at first to achieve a better fit? 

Furthermore, I wanted to ask where in the code did you apply your results from your phd thesis, concerning the the receiver and transmitter resistances? I only see the 50 Ohm in the "voltage_source" specification. I am asking because this might then be a parameter I do need to vary.

**Comment by craig-warren** [comment]
@mzunguman, from my experience you really have to be sure that at least the geometry is correct before experimenting with other parameters. EM absorber for these applications is usually a lossy material and likely also dispersive (I did not original account for this). The source resistance is specified in the source command. The receiver resistance is specified by setting the conductivity of a cell edge.

**Comment by ugy77** [comment]
@craig-warren , I'm still new to this gprmax, i have a question for you, i already run the coding for the antenna like MALA 1.2Ghz, however i do not know how to use the command for plotting the antenna. when i used " python -m tools.plot_antenna_params user_models/antenna_like_MALA_1200_fs.out", there is error saying that "Unable to open object". Can you help me with it?

**Comment by craig-warren** [comment]
@ugy77 I assume you want to look at the s11 and/or input impedance of the MALA antenna model? To do that the antenna model must be fed using a ``#transmission_line`` (http://docs.gprmax.com/en/latest/input.html#transmission-line). If you look at the antenna model in the ``user_libs/antenna.py`` module on line 375 you'll see it is fed using a ``#voltage_source``. You can change this to a ``#transmission_line`` but it will likely change the behaviour antenna model.

**Comment by ugy77** [comment]
@craigwarren, thank you for the reply. I will try to fed to trandsmission
line. But if I want to see the geometry view of the bowtie antenna, what
should I do? I already try to use paraview, however, it still do not show
up.

**Comment by craig-warren** [comment]
@ugy77 You can place a ``#geometry_view`` in your input file or uncomment the geometry views in ``user_libs/antenna.py`` module on lines 370-371.

**Comment by ugy77** [comment]
[image: Inline image 2]


@craigwarren, it showed this when i try to plot the output for the antenna
like MALA 1.2GHz.

**Comment by craig-warren** [comment]
@ugy77 Your image did not post.

**Comment by craigmwarren** [comment]
Hey Craig, I am getting email notifications from this thread, your email might be wrong on your account settings and pointing to my email (since we both are Craig Warren, we probably have close to the same email)

**Comment by craig-warren** [comment]
@ugy77 can you make sure you use the correct GitHub handle for me, which is @craig-warren and not @craigwarren (similar but different!)

Thanks.
