### ISSUE TITLE
[stderr: b"tmpjn5i8cgy.cu\r\nC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\include\\crt/host_config.h(160): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2019 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.\r\n"]

### ISSUE THREAD

**Issue by LKSkp** [gprMax/gprMax#312]
[stderr:
b"tmpjn5i8cgy.cu\r\nC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.2\\include\\crt/host_config.h(160): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2019 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.\r\n"]

**Comment by craig-warren** [comment]
@LKSkp please post this as a correctly formatted question/issue - then we can respond.
