### ISSUE TITLE
why set Rebar's relative dielectric constant =300 gprMax.exceptions.GeneralError:

### ISSUE THREAD

**Issue by zhangweizhenGitHub** [gprMax/gprMax#317]
gprMax.exceptions.GeneralError: Non-physical wave propagation: Material 'gjin' has wavelength sampled by 2 cells, less than required minimum for physical wave propagation. Maximum significant frequency estimated as 4.32623e+09Hz

but set Rebar's relative dielectric constant =10 ,it is work!!

**Comment by craig-warren** [comment]
This is not a code issue, its is a question of understanding electromagnetics and the Finite-Difference Time-Domain (FDTD) method. Rebar are generally made from steel - which can be simulated as a Perfect Electric Conductor (PEC) and has infinite permittivity (dielectric constant).

**Comment by zhangweizhenGitHub** [comment]
thanks
