### ISSUE TITLE
ValueError: bins must be monotonically increasing or decreasing

### ISSUE THREAD

**Issue by prielso** [gprMax/gprMax#318]
I run a very "simple" scenario of a fractal box in a 2D model (x, y) and I get this error over and over again. every time I run the Bscan I get this error in a different Ascan, so I think it has something to with the fractal dimension distribution. the full output of the Ascan run is:

--- Model 88/250, input file: user_models/hello_world_files/hello_world.in --------------------------------------------------------------------------------------------

Constants/variables used/available for Python scripting: {c: 299792458.0, current_model_run: 88, e0: 8.8541878128e-12, inputfile: C:\Users\prielso\gprMax\user_models\hello_world_files\hello_world.in, m0: 1.25663706212e-06, number_model_runs: 250, z0: 376.73031366686166}

Model title: simulation scene for B-scan
Number of CPU (OpenMP) threads: 6
Spatial discretisation: 0.001 x 0.001 x 0.001m
Domain size: 1 x 0.5 x 0.001m (1000 x 500 x 1 = 500000 cells)
Mode: 2D TMz
Time step (at CFL limit): 2.35865e-12 secs
Time window: 5e-09 secs (2121 iterations)
Simple sources will step 0.001m, 0m, 0m for each model run.
All receivers will step 0.001m, 0m, 0m for each model run.

Waveform signal of type ricker with maximum amplitude scaling 1, frequency 8e+08Hz created.
Hertzian dipole with polarity z at 0.01m, 0.4m, 0m, using waveform signal created.
Receiver at 0.012m, 0.4m, 0m with output component(s) Ex, Ey, Ez, Hx, Hy, Hz created.
Mixing model (Peplinski) used to create my_soil with sand fraction 0.5, clay fraction 0.5, bulk density 2g/cm3, sand particle density 2.66g/cm3, and water volumetric fraction 0.1 to 0.2 created.

Memory (RAM) required: ~109MB

Fractal box ground from 0m, 0m, 0m, to 1m, 0.4m, 0.001m with my_soil, fractal dimension 1.5, fractal weightings 1, 1, 1, fractal seeding None, with 50 material(s) created, dielectric smoothing is off.
Fractal surface from 0m, 0.4m, 0m, to 1m, 0.4m, 0.001m with fractal dimension 1.5, fractal weightings 1, 1, fractal seeding None, and range 0.396m to 0.4m, added to ground.
Processing geometry related cmds:   0%|                                                                                                        | 0/3 [00:00<?, ?cmds/s]
Traceback (most recent call last):
  File "C:\Users\prielso\Miniconda3\envs\gprMax\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\prielso\Miniconda3\envs\gprMax\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\prielso\gprMax\gprMax\__main__.py", line 6, in <module>
    gprMax.gprMax.main()
  File "C:\Users\prielso\gprMax\gprMax\gprMax.py", line 69, in main
    run_main(args)
  File "C:\Users\prielso\gprMax\gprMax\gprMax.py", line 191, in run_main
    run_std_sim(args, inputfile, usernamespace)
  File "C:\Users\prielso\gprMax\gprMax\gprMax.py", line 232, in run_std_sim
    run_model(args, currentmodelrun, modelend - 1, numbermodelruns, inputfile, modelusernamespace)
  File "C:\Users\prielso\gprMax\gprMax\model_build_run.py", line 187, in run_model
    process_geometrycmds(geometry, G)
  File "C:\Users\prielso\gprMax\gprMax\input_cmds_geometry.py", line 1228, in process_geometrycmds
    bladesindex = np.unravel_index(np.digitize(A, probability1D), (surface.fractalsurface.shape[0], surface.fractalsurface.shape[1]))
  File "<__array_function__ internals>", line 5, in digitize
  File "C:\Users\prielso\Miniconda3\envs\gprMax\lib\site-packages\numpy\lib\function_base.py", line 4924, in digitize
    raise ValueError("bins must be monotonically increasing or decreasing")
**ValueError: bins must be monotonically increasing or decreasing**

I would love if u can explain to me what's causing this so I can avoid this from happening in the future.

also a big thank you for this amazing tool.

Priel

**Comment by craig-warren** [comment]
@prielso can you attach (or copy) your complete input file here so we can take a look. Upon first glance it looks to be an issue with the #add_grass command.

**Comment by prielso** [comment]
below is the full "hello_world" input file, I agree that it appears to be a problem with the add_grass comand. but I wonder what causes this problem? tnk u for replying

#title: simulation scene for B-scan
#domain: 1 0.5 0.001
#dx_dy_dz: 0.001 0.001 0.001
#time_window: 5e-09

#soil_peplinski: 0.5 0.5 2.0 2.66 0.001 0.01 my_soil

#waveform: ricker 1 800000000.0 signal
#hertzian_dipole: z 0.01 0.4 0 signal
#rx: 0.012 0.4 0
#src_steps: 0.001 0 0
#rx_steps: 0.001 0 0

#fractal_box: 0 0 0 1 0.4 0.001 1.5 1 1 1 10 my_soil ground
#add_surface_roughness: 0 0.4 0 1 0.4 0.001 1.5 1 1 0.396 0.4 ground
#add_grass: 0 0.4 0 1 0.4 0.001 0.5 0.44000000000000006 0.45999999999999996 100 ground

##geometry_view: 0 0 0 1 0.5 0.001 0.001 0.001 0.001 hello_world_geo n

last time I run it for n=500 the Error occurred at the 130th run.

**Comment by craig-warren** [comment]
@prielso whilst I take a look, one thing you should note is that you should be seeding the fractals for the #fractal_box, #add_surface_roughness and #add_grass commands - otherwise you will get a different fractal every time you run a A-scan that is part of your B-scan. As an example see - http://docs.gprmax.com/en/latest/input.html#fractal-box and the `i2` parameter.

**Comment by craig-warren** [comment]
@prielso yes you can use any integer to seed the fractals. I will still look into the issue.

**Comment by prielso** [comment]
since seeding the the random number for the fractals I didn't come across this error.
