### ISSUE TITLE
calling gprMax from another directory-windows and linux problem

### ISSUE THREAD

**Issue by SajadJ** [gprMax/gprMax#32]
Hello Craig, 

I need to call gprMax from another directory (a subdirectory-new folder- in the gprMax-master parent directory). Is this possible at all?
I'm getting the following error:
C:\Miniconda3\python.exe: No module named gprMax

Any solution? 
Thanks a lot,
Sajad

**Comment by craig-warren** [comment]
@SajadJ I think if you are calling the gprMax from a directory that is not the top-level gprMax, then you need to add the top-level directory to your `$PYTHONPATH` environment variable.

**Comment by SajadJ** [comment]
Great! worked.
