### ISSUE TITLE
GPU installation - numpy/pycuda clash

### ISSUE THREAD

**Issue by GuilbertDavid** [gprMax/gprMax#321]
Dear all,
I had no problems installing gprMax and pycuda.

Without gpu I can generate an the example cylinder_Ascan_2D.in, but when I want to use -gpu I get an error.

![Error_gpu](https://user-images.githubusercontent.com/105917696/190612993-352ef56a-5078-44a2-8c66-a3e6d6b4c3fe.png)

Numpy version is 1.22.3 and pycuda version is 2022.1, I am  under Windows 10.
Have you encountered this problem before?
Best regards

**Comment by craig-warren** [comment]
@GuilbertDavid thanks for flagging this. As you observe this seems to be an issue with numpy and pycuda. Currently we don't pin the numpy version in our conda environment and I don't think a version is pinned with pycuda either. I'll do some digging to try and understand the clash.

**Comment by craig-warren** [comment]
@GuilbertDavid can you try the following:

1. Amend the numpy line in your conda_env.yml file to `numpy<1.23.0`
2. Delete and re-create your conda environment: `conda env remove --name gprMax`, `conda clean --all`, `conda env create -f conda_env.yml`
3. Activate conda, clean and re-build gprMax: `conda activate gprMax`, `python setup.py cleanall`, `python setup.py build`, `python setup.py install`

**Comment by GuilbertDavid** [comment]
I have done as you tell me, I still have the same message.

**Comment by GuilbertDavid** [comment]
I am able to use gprMax with gpu
I go down to cuda driver 11.6
I have done the installation of pycuda like this: 
1. pip install pipwin
2. pipwin install pycuda

I have a warning when using gpu
UserWarning: The CUDA compiler succeeded, but said the following: kernel.cu
kernel_store_outputs = SourceModule(kernel_template_store_outputs.substitute(REAL=cudafloattype, NY_RXCOORDS=3, NX_RXS=6, NY_RXS=G.iterations, NZ_RXS=len(G.rxs), NX_FIELDS=G.nx + 1, NY_FIELDS=G.ny + 1, NZ_FIELDS=G.nz + 1), options=compiler_opts)

**Comment by craig-warren** [comment]
@GuilbertDavid what version of CUDA were you using when you saw the failures?

**Comment by GuilbertDavid** [comment]
The driver version of cuda was 11.7.
When I go down to 11.6, I have also try the command you give me and I got the same error message.

**Comment by GuilbertDavid** [comment]
I have test the example
python -m gprMax user_models/cylinder_Bscan_2D.in -n 60
Simulation completed in [HH:MM:SS]: 0:04:23.257596

python -m gprMax user_models/cylinder_Bscan_2D.in -n 60 -gpu
Simulation completed in [HH:MM:SS]: 0:09:47.942997

Using gpu takes more time, is this normal ?
