### ISSUE TITLE
using impulse response and source signal to simulate contsine waveform based signal

### ISSUE THREAD

**Issue by sravani-chil** [gprMax/gprMax#322]
Hi all,

I am trying to use GPRMax impluse response to simulate contsine waveform based signal by a given sine source signal. 

I have done two simulations on GPRMax, one with the impulse response waveform as source signal, the other one with the contsine waveform as source signal. Then convolute the impulse response signal got from the receiver with the sine source function to compare with the contsine waveform signal got from the receiver. 

But I couldn't see the nice alignment between the convoluted signal and the contsine signal. I cannot figure out what could cause this issue, it would be nice to have some insights here.  

Based on the results and plots shown below,  I have the following questions,
1) about the impulse response output in my example, as I set the amplitude as 1, but I could see that the EZ value of impose response is more than 200, shouldn't be 1?
2) the convoluted signal value has an obvious shift in y-axis, more biased to any y values <0, I don't know whether it is some artifacts that expected from the FDTD method with high frequency at 1.5GHz or the way how I use np.convolute to create the convoluted signal is wrong. 

Here are more detailed information of simulations. 
- GPRMax inputs:
-------------------------------------------------------------------------------------------------
**Impulse response Input file:**
#domain: 0.300 0.300 0.300
#dx_dy_dz: 0.001 0.001 0.001
#time_window: 10e-9

#waveform: impulse 1 1.5e9 impose_waveform
#hertzian_dipole: z 0.20 0.15 0.2 impose_waveform
#rx: 0.150 0.150 0.2 

**Contsine waveform input file**:
#domain: 0.300 0.300 0.300
#dx_dy_dz: 0.001 0.001 0.001
#time_window: 10e-9

#waveform: contsine 1 1.5e9 cosine_waveform
#hertzian_dipole: z 0.20 0.15 0.2 cosine_waveform
#rx: 0.150 0.150 0.2 

------------------------------------------------------------------------------------------------------
- Plots for the impulse response from GPRMax
-
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/48795943/191757599-81fb1155-4966-4a8d-ab57-5020d005a246.png)

----------------------------------------------------------------------------------------------------------
- Python results for the signal convolution part:
source signal, sine function with frequency= 1.5GHz, and dt=1.926ps as time step used in the software, 10ns for the simulation time window. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/48795943/191756727-db810bd9-5f9a-432c-8437-b4e427ca1eb5.png)

convolution results: 
![conv1](https://user-images.githubusercontent.com/48795943/191758322-f36668e5-a3bf-4a60-a128-5f4fd8a6073f.png)

Thanks very much for your help in advance.

**Comment by agianno** [comment]
Hi,

This is not an issue with the code and what you get is expected behaviour. The builtin const sine excitation is ramped to avoid introducing high frequency noise in the FDTD solver that otherwise will be unavoidable. This is explained in the documentation on excitation functions. If you replicate the ramped excitation as the signal to be convolved the convolution approach should be very similar to the one you get from gprMax with the same excitation. Please discuss this further if you wish in our google forum where explanation and guidance is given by users to other users of gprMax.
