### ISSUE TITLE
Installation gprMax.

### ISSUE THREAD

**Issue by Bayabati** [gprMax/gprMax#323]
Hi Dr Craig Warren.
I have windows 10 + Python 3.6 (64-bit) 
I've done these steps:
$ conda update conda
$ conda install git
But I have problem with this command .How can I fix it?
" PS C:\Users\Karwan Store\desktop> git clone https://github.com/gprMax/gprMax.git
Cloning into 'gprMax'...
fatal: unable to access 'https://github.com/gprMax/gprMax.git/': OpenSSL SSL_connect: Connection was reset in connection to github.com:443"

**Comment by craig-warren** [comment]
@Bayabati I suspect this is an issue with your network connection. Did you resolve it?

**Comment by Bayabati** [comment]
I've done ping command and you can see the different results for difference URL address.(www.github.com is ok but the other ones are not ok) I like  try this command by IP address instead of URL . 
Your URL address  is :https://github.com/gprMax/gprMax.git
Can you share your IP address please?



results:
### (base) PS C:\Users\Karwan Store\desktop> ping www.github.com
Pinging github.com [140.82.121.4] with 32 bytes of data:
Reply from 140.82.121.4: bytes=32 time=142ms TTL=47
Reply from 140.82.121.4: bytes=32 time=142ms TTL=47
Reply from 140.82.121.4: bytes=32 time=160ms TTL=47
Reply from 140.82.121.4: bytes=32 time=144ms TTL=47

Ping statistics for 140.82.121.4:
    ### Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 142ms, Maximum = 160ms, Average = 147ms
### (base) PS C:\Users\Karwan Store\desktop> ping www.github.com/gprMax
Ping request could not find host www.github.com/gprMax. Please ### check the name and try again.
### (base) PS C:\Users\Karwan Store\desktop> ping www.github.com/gprMax/gprMax.git
Ping request could not find host www.github.com/gprMax/gprMax.git. Please ### check the name and try again.
### (base) PS C:\Users\Karwan Store\desktop> ping www.github.com/gprmax/gprmax.git
Ping request could not find host www.github.com/gprmax/gprmax.git. Please ### check the name and try again.

**Comment by Bayabati** [comment]
(base) PS C:\Users\Karwan Store\desktop> ping https://www.github.com/gprmax/gprmax.git
Ping request could not find host https://www.github.com/gprmax/gprmax.git. Please check the name and try again.

**Comment by agianno** [comment]
You can only ping IP addresses or websites that resolve to IP addresses. It is normal not to be able to ping the gprMax repo. This is not an issue with the code.

**Comment by Bayabati** [comment]
When Mr Craig Warren said maybe this is an issue with my network connection, I tried to find and solve issue by ping and tracert command. I think if my network connection has any issue, should not be able to send and recive any paket.What do you think aboute it?

**Comment by agianno** [comment]
Do you see the repo if you put the URL ( https://www.github.com/gprmax/gprmax.git )  in your browser? If so the problem might be with your SSL certificates or a antivirus prohibits the connection for some reason. Try to disable the antivirus for these tasks if that is not the problem. Some people with similar problems tried and resolved this error doing the following but I am not sure if the problem is the same in yours case. It has nothing to do with gprMax but with the way your system connects and allows programmes to use secure connections to programme like git.

git config --global --unset-all remote.origin.proxy
