### ISSUE TITLE
Taguchi fitness_function - xcorr

### ISSUE THREAD

**Issue by WLahn** [gprMax/gprMax#324]
I'm trying to optimize a custom antenna model via taguchi,
but can not find the 'dx, dy, dz'-attribute in the .out-file.

https://github.com/gprMax/gprMax/blob/9c32901f0646852d9577acec88146dc389599343/user_libs/optimisation_taguchi/fitness_functions.py#L96

As far as I checked, it should be 'dx_dy_dz', 
but when I check an .out-file, it seems like the resolution does not get written into the file at all.

My hdf5 structure looks like this:
<HDF5 file "antenna_bowtie_opt_final1.out" (mode r)>
├── rxs
│&emsp;└── rx1
│&emsp;&emsp;└── Ex (2598)
└── tls
&emsp;└── tl1
&emsp;&emsp;├── Iinc (2598)
&emsp;&emsp;├── Itotal (2598)
&emsp;&emsp;├── Vinc (2598)
&emsp;&emsp;└── Vtotal (2598)

Is there a command I need to set in order to export the resolution?

Thanks for your help

**Comment by craig-warren** [comment]
@WLahn check the file attributes at the root and you should find it.

**Comment by WLahn** [comment]
Thanks, I found it!
So the attribute name just needs to be fixed from 'dx, dy, dz' to 'dx_dy_dz'

**Comment by craig-warren** [comment]
@WLahn I suspect you are using an old version of the code as this was changed some years ago.
