### ISSUE TITLE
Simulation with Openmpi and GPU

### ISSUE THREAD

**Issue by Gzhuoyan** [gprMax/gprMax#325]
Hi everyone:
    I'm a beginner of gprMax, recently i'm considering to accelerate the simulation with 4 GPUs. For now, i can just successfully do it on one GPU. The openmpi is successfully installed since i run the "hello" test, and the result is as follows:
![1668062677207](https://user-images.githubusercontent.com/117889618/201019470-f500dba0-d22d-4d55-b214-83d3db027ff4.png)
    The problem is when i run gprMax combing MPI and 4 GPUs, this following error occurs:
![5a0366986f971040b99dc361ad49fb9](https://user-images.githubusercontent.com/117889618/201020021-e2fa4e5a-a658-4f9b-827d-6310737032c6.png)
libmpi.so.12 is an ancient version, i'm confused that if i have to downgrade the openmpi to this version? Thanks for answering!

    I run the model on Linux, Ubantu 20.04, gprMax 3.1.6, Openmpi 4.1.4.

**Comment by craig-warren** [comment]
@Gzhuoyan looks like an issue between your OpenMPI installation and the Python mpi4py package. In the first instance suggest you uninstall mpi4py and try re-installing as follows: `pip uninstall mpi4py; pip install mpi4py --no-cache`

**Comment by Gzhuoyan** [comment]
> 

Thanks a lot! The problem is solved so simply. I thought it was the issue regarding to version of the libmpi~
![1668073499973](https://user-images.githubusercontent.com/117889618/201056875-ab277e57-8831-4698-966b-42dd52e6084b.png)
