### ISSUE TITLE
Memory not released when running multiple models in loop with GPU

### ISSUE THREAD

**Issue by YBstory** [gprMax/gprMax#326]
The program does not seem to have a good mechanism for releasing memory, and when run too many times, the GPU memory footprint gets higher and higher. Adding torch.cuda.empty_cache() inside the solve_gpu(currentmodelrun, modelend, G) function in model_build_run.py seems to prevent the GPU from getting higher and higher memory usage.

**Comment by YBstory** [comment]
The problem still doesn't seem to be solved, and "cuda out of memory" still appears when running more times, is there any other solution? I am running on linux platform.

**Comment by craig-warren** [comment]
Further similar report of this at https://groups.google.com/g/gprmax/c/Ta-_mXCAow4

**Comment by Kurt9806** [comment]
Hello, I've faced a similar issue. It seems that deleting the context at the end of the model_build_run.py is not sufficient. 
A temporary solution has been to declare a garbage collector using gc.collect() with torch.cuda.empty_cache() and cuda.close().

**Comment by craig-warren** [comment]
@YBstory @Kurt9806 think this should now be fixed by https://github.com/gprMax/gprMax/commit/0848c13b2b2db888b2f3f37a54c36231245ea589
