### ISSUE TITLE
benchmark with real world data - IFSTTAR

### ISSUE THREAD

**Issue by cyanzhao42** [gprMax/gprMax#329]
Hi, I am working on IFSTTAR - [TU1208 open dataset](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwicyLyH28_7AhXiAzQIHRfuDtUQFnoECAYQAQ&url=https%3A%2F%2Fwww.mdpi.com%2F2072-4292%2F10%2F4%2F530&usg=AOvVaw0Ft47AzkexF1O6D3Swah8Z). I am wondering if anyone aware of any work/open source code benchmark gprMax with this dataset. Thanks!

**Comment by craig-warren** [comment]
@cyanzhao42 - can you post this question in our Google Group (Forum) please - https://groups.google.com/g/gprmax
