### ISSUE TITLE
miniconda install issue

### ISSUE THREAD

**Issue by Bjorn5768** [gprMax/gprMax#33]
Hi,

I am trying to install gprMax on a Windows 32-bit machine using the instructions provided:
https://github.com/gprMax/gprMax

I downloaded the latest gprMax-master file. I note in step 1) you mention copying contents of windows-32 zip file into gprMax directory. Where do I obtain the windows-32bit zip file?

Installed Python 3.5 Version of Miniconda (32-bit version):
http://conda.pydata.org/miniconda.html

Followed through step two and have activated the new environment (activate gprMax).
I have also installed the C libraries suggested in step 3.

When I run the cylinder_Ascan_2D.in example I get the following issue:

![screenshot](https://cloud.githubusercontent.com/assets/17143511/12919213/fb61b68c-cf3a-11e5-8bf6-39cacd487a0e.jpg)

I have read through the thread:
https://github.com/gprMax/gprMax/issues/27
You mention a step 4 of building the Cython extensions, could this be the problem? If so, how do I do this?

Best Regards,
Bjorn

**Comment by craig-warren** [comment]
@Bjorn5768 the master release is for developers (see the Installation for developers instructions). If you don't intend to develop, re-read step 1:
> Click on Releases from the top header and choose the release you want (latest is at the top).

You'll find the latest release is currently v.3.0.0b19 (Bowmore), download the source code for it and the windows-32bit zip file which you'll also find there. 

Everything else you have done is OK. So you should be working after that.

**Comment by Bjorn5768** [comment]
Thank you for a very quick response. Software now installed and working. Best Regards, Bjorn.
