### ISSUE TITLE
subclassing Waveform

### ISSUE THREAD

**Issue by timhuff** [gprMax/gprMax#331]
It appears that the Waveform class is... manually subclassing itself? It seems that this should be an abstract class with a registry. It seems that doing this would enable simple user-defined waveforms and clean up the code of Waveform, itself. If these changes were implemented in a non-backward breaking way, would a pull request be welcome?

**Comment by craig-warren** [comment]
@timhuff thanks for the observation - yes I think the Waveform class could be better implemented. A PR would be welcome but could you look on our devel branch as this will be the next release of gprMax, hopefully in a few months, so we don't really want to make any specific changes to the master branch right now.
