### ISSUE TITLE
B-scan problem with GPU - memory not released?

### ISSUE THREAD

**Issue by QZZZZZYF** [gprMax/gprMax#335]
![image](https://user-images.githubusercontent.com/100697412/222368252-8733f90e-29a8-4010-9b55-d1103e50f1d3.png)
Bscan can run normally without calling GPU, but it cannot run normally after calling GPU.
The driver version of cuda was 11.7.

**Comment by craig-warren** [comment]
This could be the same issue as https://github.com/gprMax/gprMax/issues/326

Can you check using nvidia-smi that the GPU memory is being released after the first model has run.

**Comment by QZZZZZYF** [comment]
![image](https://user-images.githubusercontent.com/100697412/222607449-d7838160-7b44-450c-ba57-a6ffd38d15b7.png)

**Comment by craig-warren** [comment]
@QZZZZZYF think this should now be fixed by https://github.com/gprMax/gprMax/commit/0848c13b2b2db888b2f3f37a54c36231245ea589
