### ISSUE TITLE
windows 11  cannot install gprMax

### ISSUE THREAD

**Issue by kujta1** [gprMax/gprMax#337]
Hi , 
I am trying to install GPRMax, 
in both of my Windows 11 machines there is this problem 

yee_cell_setget_rigid_ext.c
C:\Users\kujti\anaconda3\envs\gprMax\Lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\kujti\anaconda3\envs\gprMax\libs /LIBPATH:C:\Users\kujti\anaconda3\envs\gprMax /LIBPATH:C:\Users\kujti\anaconda3\envs\gprMax\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64" /EXPORT:PyInit_yee_cell_setget_rigid_ext build\temp.win-amd64-cpython-311\Release\gprMax\yee_cell_setget_rigid_ext.obj /OUT:build\lib.win-amd64-cpython-311\gprMax\yee_cell_setget_rigid_ext.cp311-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-311\Release\gprMax\yee_cell_setget_rigid_ext.cp311-win_amd64.lib
   Creating library build\temp.win-amd64-cpython-311\Release\gprMax\yee_cell_setget_rigid_ext.cp311-win_amd64.lib and object build\temp.win-amd64-cpython-311\Release\gprMax\yee_cell_setget_rigid_ext.cp311-win_amd64.exp
Generating code
Finished generating code
building 'gprMax.cython.fields_updates_dispersive' extension
creating build\temp.win-amd64-cpython-311\Release\gprMax\cython
"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\kujti\anaconda3\envs\gprMax\Lib\site-packages\numpy\core\include -IC:\Users\kujti\anaconda3\envs\gprMax\Lib\site-packages\numpy\core\include -IC:\Users\kujti\anaconda3\envs\gprMax\include -IC:\Users\kujti\anaconda3\envs\gprMax\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /TcgprMax\cython\fields_updates_dispersive.c /Fobuild\temp.win-amd64-cpython-311\Release\gprMax\cython\fields_updates_dispersive.obj /O2 /openmp /w
cl : Command line warning D9025 : overriding '/W3' with '/w'
fields_updates_dispersive.c
C:\Users\kujti\anaconda3\envs\gprMax\Lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
gprMax\cython\fields_updates_dispersive.c(1320): error C2061: syntax error: identifier '__pyx_t_double_complex'
gprMax\cython\fields_updates_dispersive.c(1320): error C2059: syntax error: ';'
gprMax\cython\fields_updates_dispersive.c(1325): error C2061: syntax error: identifier '__pyx_t_double_complex_from_parts'
gprMax\cython\fields_updates_dispersive.c(1325): error C2059: syntax error: ';'
gprMax\cython\fields_updates_dispersive.c(1325): error C2059: syntax error: '<parameter-list>'
gprMax\cython\fields_updates_dispersive.c(1332): error C2061: syntax error: identifier '__pyx_t_float_complex'
gprMax\cython\fields_updates_dispersive.c(1332): error C2059: syntax error: ';'
gprMax\cython\fields_updates_dispersive.c(1337): error C2061: syntax error: identifier '__pyx_t_float_complex_from_parts'
gprMax\cython\fields_updates_dispersive.c(1337): error C2059: syntax error: ';'
gprMax\cython\fields_updates_dispersive.c(1337): error C2059: syntax error: '<parameter-list>'
gprMax\cython\fields_updates_dispersive.c(2383): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(2384): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(5423): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(5423): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(5471): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(5471): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(5739): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(5739): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(5787): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(5787): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(6055): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(6055): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(6103): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(6103): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(6719): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(6719): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(6767): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(6767): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(7035): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(7035): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(7083): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(7083): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(7351): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(7351): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(7399): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(7399): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(9739): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(9739): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(9937): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(9937): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(10135): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(10135): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(10610): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(10610): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(10808): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(10808): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(11006): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(11006): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(13767): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(13767): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(13807): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(13807): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(14044): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(14044): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(14084): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(14084): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(14321): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(14321): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(14361): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(14361): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(14942): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(14942): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(14982): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(14982): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(15219): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(15219): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(15259): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(15259): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(15496): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(15496): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(15536): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(15536): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(17598): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(17598): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(17758): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(17758): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(17918): error C2065: '__pyx_t_double_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(17918): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(18351): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(18351): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(18511): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(18511): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(18668): error C2065: '__pyx_t_float_complex': undeclared identifier
gprMax\cython\fields_updates_dispersive.c(18668): error C2059: syntax error: ')'
gprMax\cython\fields_updates_dispersive.c(37022): error C2061: syntax error: identifier '__pyx_t_double_complex_from_parts'
gprMax\cython\fields_updates_dispersive.c(37022): error C2059: syntax error: ';'
gprMax\cython\fields_updates_dispersive.c(37022): error C2059: syntax error: '<parameter-list>'
gprMax\cython\fields_updates_dispersive.c(37176): error C2061: syntax error: identifier '__pyx_t_float_complex_from_parts'
gprMax\cython\fields_updates_dispersive.c(37176): error C2059: syntax error: ';'
gprMax\cython\fields_updates_dispersive.c(37176): error C2059: syntax error: '<parameter-list>'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

Can somboody help

**Comment by craig-warren** [comment]
@kujta1 is this the master or devel branch you are using?

**Comment by lavande-jessica** [comment]
Hi, I have the same problem, did you solve it?

**Comment by craig-warren** [comment]
`cython\fields_updates_dispersive.pyx` had been erroneously added to the master branch. It has now been removed so gprMax should now install correctly.
