### ISSUE TITLE
evtk is deprecated

### ISSUE THREAD

**Issue by apcode** [gprMax/gprMax#339]
from pyevtk import *

import warnings

warnings.warn(
    'the "evtk" package is deprecated, use "pyevtk" instead',
    DeprecationWarning,
)

**Comment by craig-warren** [comment]
@apcode can you point to where you are experiencing this? Presumably using the devel branch?

**Comment by apcode** [comment]
Yeah, sorry I could have been more detailed. I was on the devel branch but switched back to main and it works.

I am trying to get the GPU version up and running inside a docker container. Haven't got it working. I think I might need another cuda/pycuda dev install but haven't had time to look into it.

My Dockerfile:
```
FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04

# Require a compiler to build gprMax
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    apt-get install -y wget git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

ENV PATH=$CONDA_DIR/bin:$PATH

# Copy the requirements.txt first to leverage the Docker cache
COPY requirements.txt .
RUN pip install -r requirements.txt

# We build gprMax from source because the simulation optimised for
# different architectures.
RUN git clone https://github.com/gprMax/gprMax.git
WORKDIR /app/gprMax
# We should fix this to a specific version as its the dev branch!
# RUN git checkout devel
RUN python setup.py build
RUN python setup.py install

WORKDIR /app

# Copy app files last to prevent cache busting
# COPY . .   # using -v to mount dir to keep out files.

ENTRYPOINT [ "python", "-m", "gprMax"]
```

**Comment by craig-warren** [comment]
@apcode OK, makes more sense. The master branch does not use evtk as we rolled our own VTK files then. Now we are trying to leverage the pre-built functionality of pyevtk. Note the issue you may be seeing is that the devel and master branches use different conda environment files, i.e. if you are using the devel branch you need to build a new conda environment from the conda_env.yml file on the devel branch. Maybe you already clocked this though.

**Comment by apcode** [comment]
Makes sense. I hadn't heard of pyevtk.  I've been using pyvista in another project. It's really great.

That's a good point. I don't setup the conda env. I didn't because I was in a docker container. I'll check.

**Comment by apcode** [comment]
Ah, it's just the dependencies. You can ignore my other issue. 
I've been using a requirements.txt
```colorama
cython
h5py
jupyter
matplotlib
numpy
pip
psutil
scipy
terminaltables
tqdm
pycuda
humanize
pyevtk
pyfiglet
```

Looks like it should work though.
