### ISSUE TITLE
Compiled or line interpreted?

### ISSUE THREAD

**Issue by Bjorn5768** [gprMax/gprMax#34]
Hi,

We are performing a comparison of running a simulation on gprMax version 3.0.0b19 to an older version 2.0 and note that the speed is significantly slower on the new version (around five times slower).

Please advise if this version is compiled or line interpreted?

Best Regards,

Bjorn

**Comment by craig-warren** [comment]
@Bjorn5768 gprMax v3 is written in Python with the performance-critical parts compiled to C (and parallelised using OpenMP) with Cython. The old v2 code was written purely in C.

I'm surprised you are seeing such a speed difference. We have not performed any extensive benchmarking but our impression was the new code performed similarly to the old. Can you provide the input file you are using for your tests and a description of the hardware you are running on?

We have noticed performance problems with Intel's hyper-threading technology and OpenMP ( #1 ) but gprMax is set not to use hyper-threading so this shouldn't have an effect.

**Comment by Bjorn5768** [comment]
Hi,
I am working with Vincent at Utsi Electronics, I will forward on input files and further details by email asap.
Best Regards,
Bjorn
