### ISSUE TITLE
help me~~! i want to make Bscan 

### ISSUE THREAD

**Issue by buhwan** [gprMax/gprMax#347]
![mine](https://github.com/gprMax/gprMax/assets/129297218/a3e569c1-46ff-4673-9491-e17e9ea81820)
--------------------------------------------------------------------------------------------------------
#domain: 1.000 0.250 0.450
#dx_dy_dz: 0.002 0.002 0.002

#time_window: 5e-9

#material: 3.5 0.01 1.0 0 bakelite
#material: 6.0 0.01 1.0 0 rubber
#material: 3.0 0.00001 2.0 0.01 dry_sand
#material: 2.86 0.00048 1.0 9.75 TNT

#waveform: ricker 1 1.5e9 my_ricker

#hertzian_dipole: y 0.100 0.110 0.360 my_ricker
#rx: 0.100 0.140 0.360

#src_steps: 0.006 0 0
#rx_steps: 0.006 0 0

#box: 0 0 0 1.000 0.250 0.200 dry_sand
#cylinder: 0.500 0.125 0.150 0.500 0.125 0.147 0.056 rubber
#cylinder: 0.500 0.125 0.147 0.500 0.125 0.094 0.056 bakelite
#cylinder: 0.500 0.125 0.147 0.500 0.125 0.097 0.053 TNT
#cylinder: 0.500 0.125 0.147 0.500 0.125 0.097 0.002 pec
-----------------------------------------------------------------------------------------------------------
!python -m gprMax "/content/drive/MyDrive/gprmaxgroup.in" -n 11
So we ran the simulation, we created the Bscan, and there's no parabolic shape
Like the photo file above, when it is detected, the gpr Bscan 
I want to do it like I'm creating a parabola, but what parts should I fix and take action??? 
I'd like you to help me, please.

![Bscan image](https://github.com/gprMax/gprMax/assets/129297218/e080ca0e-7c73-49ff-8ca0-045af386b013)

**Comment by agianno** [comment]
Use the gprMax discussion forum for such questions. This is only a mechanism to report bugs and issues with the code and it is not the place to ask for help in how to use it.

**Comment by buhwan** [comment]
Thank you. Actually, I applied to join the gprMax-users because I wanted to participate in the discussion at Forum 
It hasn't been accepted yet. I ended up posting here because I was frustrated while waiting. I'm sorry.

The ID I applied for is jbh9867@gmai.com .
I would appreciate it more if you could check or help me.
