### ISSUE TITLE
(ImportError: No module named 'gprMax.fields_update') problem

### ISSUE THREAD

**Issue by demilich18** [gprMax/gprMax#35]
Hi,
First I would thank you for sharing the new version of GPRMAX.
It includes some new features that looks really interesting.
However, I got some problem while start runing the GPRMAX.
I followed your guidence, and the installation of the Python and GPRMAX goes smooth.
But I received error while trying to run the examples that you shows in the guidence.
The error is shown as:
File "C:\gprMax-master\gprMax\gprMax.py", line 32, in <module>
    from gprMax.fields_update import *
ImportError: No module named 'gprMax.fields_update'

I found a similar issue that you closed 2 weeks ago and you mentioned you already fixed it with the latest GPRMAX-master version. I am also using this version but the error appears.
The only difference to the previous issue is that I am using the windows10-64 bit. Is this can be the reason for this problem?

Best regards.

**Comment by craig-warren** [comment]
@demilich18 the master release is for developers (see the Installation for developers instructions). If you don't intend to develop, re-read step 1:

> Click on Releases from the top header and choose the release you want (latest is at the top).

You'll find the latest release is currently v.3.0.0b19 (Bowmore), download the source code for it and the windows-64bit zip file which you'll also find there. You can also follow the screencast https://youtu.be/dvC0_7qFVbE

I've just tested this on my Windows 10 (64bit) machine and it works fine.

**Comment by demilich18** [comment]
@craig-warren  
Thank you for your help! Now it works well.
I am totally new to this github site so I missed the release page and the  binary extensions.
Best wishes

**Comment by craig-warren** [comment]
No probs.

**Comment by niksyahrim** [comment]
Hi @craig-warren, Somehow I'm facing the same problem here when I tried to run the model "cylinder_Ascan_2D". Getting this error message: "ImportError: No module named 'gprMax.fields_update' ". I had followed the screencast step-by-step with version v.3.0.0b21. And i am running Windows 10 64 Bit. Any tip where I should start to rectify the problem? Many thanks!

**Comment by niksyahrim** [comment]
Hi, I tried with older version  v.3.0.0b19, and it worked. Thanks.

**Comment by craig-warren** [comment]
OK, thanks for the information. I'll look into why v.3.0.0b21 might not have been working. The error you were getting suggests gprMax could not see the compiled modules.

**Comment by apcode** [comment]
I'm installing on ubuntu 14.04.
I had to also run:
> python setup.py build
> python setup.py install

to get it to work. Otherwise I got the error listed in this issue.

I guess this could be added to the installation instructions.

**Comment by craig-warren** [comment]
Yes we probably need to improve the installation instructions further. Can I check, @niksyahrim and @apcode did you copy the compiled modules into the gprMax directory? i.e.

* Expand both zip files and copy the contents of the `windows-32bit`, `windows-64bit`, `linux-64bit` or `macosx-64bit` directory into the gprMax-v.X.Y.Z/gprMax directory.

@agianno maybe we can look into automating/simplifying this. If there was an easier route to installing a C compiler on Windows this would all be less of a problem ;-)

**Comment by craig-warren** [comment]
I'm going to close this as I think if you are using a release download then this error arises out of forgetting to copy the pre-built Cython extensions to the gprMax-v.X.Y.Z/gprMax directory. 

For developers (or those more familiar with Python/Cython) pulling the code from GitHub and running ``python setup.py build_ext -i`` is what is required to build the Cython extensions for yourself. This is detailed in the 'Installation for developers' instructions: [http://docs.gprmax.com/en/latest/readme_install_devs.html#installation-for-developers](http://docs.gprmax.com/en/latest/readme_install_devs.html#installation-for-developers)

**Comment by NishanthBhonsle** [comment]
Experiencing a similar kind of an error.
Trying to build the latest version is giving the following error : 
File "setup.py", line 159, in <module>
    annotate=False)
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 798, in cythonize
    cythonize_one(*args[1:])
  File "/usr/lib/python3/dist-packages/Cython/Build/Dependencies.py", line 915, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: gprMax/fields_update.pyx

Installing on ubuntu 14.04 and i have copied all the contents from Linux-64 bit directory into gprMax-v.X.Y.Z/gprMax directory. 
Tried executing the following commands as well : 
python setup.py build
python setup.py install
But getting the same error.

**Comment by craig-warren** [comment]
@NishanthBhonsle it sounds like you have mixed user and developer install instructions. Are you trying to install the latest version, or build from the master branch (developer instructions)?

**Comment by NishanthBhonsle** [comment]
I am trying to build from the master branch.

**Comment by craig-warren** [comment]
OK, so no need to copy any pre-built modules. Have you followed [http://docs.gprmax.com/en/latest/readme_install_devs.html#installation-for-developers](http://docs.gprmax.com/en/latest/readme_install_devs.html#installation-for-developers)? and run

`python setup.py build_ext --inplace`

**Comment by NishanthBhonsle** [comment]
Yes, have followed the same exact steps as mentioned in the documentation. The previous version was working fine and perfect. Getting the same error again even after trying to build without copying any pre-built modules.

**Comment by craig-warren** [comment]
OK, thats strange. I'll take a look on the Linux virtual machine next week.

**Comment by craig-warren** [comment]
@NishanthBhonsle I suspect something funky is going on with your specific setup. I have just successfully built from the master branch on my Linux (Ubuntu 14.04) VM.

Are you using Miniconda and the environment file from the gprMax package?

**Comment by NishanthBhonsle** [comment]
Yes I am. Will try to build it all over once again. Thank You.

**Comment by meirgershenson** [comment]
Have the same problem after update last week so I reinstall from scratch and it is still the same.  Window 10 64 bits followed the two videos on you tube..

**Comment by craig-warren** [comment]
@meirgershenson I tested on our Windows 10 (64-bit) VM and all seems OK. Can you copy/paste or screengrab the steps you took and the exact error message you are getting. Also can you make sure your gprMax environment is up-to-date with ``(gprMax) $ conda env update -f conda_env.yml``

**Comment by meirgershenson** [comment]
This time I followed the manual not the you-tube which is confusing.  It worked. Thanks.

**Comment by craig-warren** [comment]
Glad it is working. I'll annotate the video to add this command.

**Comment by sankenaresh** [comment]
Hi,
I followed your installation guidelines for the installation of the Python and gprMax  and it goes smooth.
I  tried to run one of the user models:cylinder_Bscan_2D.in , run went smooth and i  got the merged output file:cylinder_Bscan_2D_merged.out 
But I received error while trying to run the merged outputfile to view an image of the B-scan
The error is shown as:
![error](https://user-images.githubusercontent.com/35888658/35480788-f193b738-03ca-11e8-8393-dd3272807f22.PNG)
