### ISSUE TITLE
gprMax Installation Issue: 'gprMax\fields_updates_ext.c': No such file or directory

### ISSUE THREAD

**Issue by nad1** [gprMax/gprMax#351]
Hello,

Firstly, thank you so much for this amazing work.

I'm trying to install gprMax, but I have some problems.

In this step, I get errors.
`python setup.py build`
![gprmax1](https://github.com/gprMax/gprMax/assets/11485939/14d0758f-3c97-4fe2-b38d-128339657ec1)

The reason might be about setting the Path and Environment Variables. Because I couldn't understand how to do it. Is this problem related to that?

**Comment by craig-warren** [comment]
@nad1 can you try running ``python setup.py cleanall`` then re-building

**Comment by craig-warren** [comment]
@nad1 I suspect its an issue with MS C compiler not being on your PATH. Can you check your PATH environment variable - you can get guidance here - https://docs.gprmax.com/en/latest/include_readme.html#microsoft-windows

**Comment by nad1** [comment]
> @nad1 I suspect its an issue with MS C compiler not being on your PATH. Can you check your PATH environment variable - you can get guidance here - https://docs.gprmax.com/en/latest/include_readme.html#microsoft-windows

I suspect it too, because I couldn't do that part. Unfortunately, the guide in the link and from Microsoft to Set the Path and Environment Variables is not clear for me. Could you please make it more clear?

**Comment by nad1** [comment]
> @nad1 there are lots of articles explaining how to set the PATH environment variable on Windows, e.g. https://learn.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee537574(v=office.14)

@craig-warren Thank you for sharing this.

I added the "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx86\x64"8 path into "Path" variable there. But, I still have the same error.

I added it into both user and system "Path" variable, then only in system "Path" variable. After that I tried it with (Program Files (x86)) path, but still no result. Should I create another variable?

![gprmax3](https://github.com/gprMax/gprMax/assets/11485939/f664031f-0602-4c39-88ca-f033fb328520)
