### ISSUE TITLE
paraview's typeError with GprMax_info

### ISSUE THREAD

**Issue by dajianba** [gprMax/gprMax#359]
when I input a group of .vti files by using paraview and click the "gprmax_info.py" button.
The software warns me that "TypeError: expected str, bytes or os.PathLike object, not FileNameProperty"
I do not know what this means or how to solve it. Does anyone know what to do? Thank you.
paraview version ：5.11.1
![图片2](https://github.com/gprMax/gprMax/assets/103230441/cd636d21-1909-44d1-9ebc-96b3f22e3620)

**Comment by craig-warren** [comment]
@dajianba can you make sure you are using the latest version of gprMax and re-install the gprMax Paraview macro.
