### ISSUE TITLE
[GPU Issue]: pycuda.driver.CompileError: nvcc compilation of /tmp/tmpeuo7r59m/kernel.cu failed

### ISSUE THREAD

**Issue by tedmsxu** [gprMax/gprMax#363]
Hello,

I am using the latest gprMax. I did 'git pull' which shows me that the version is up to date.

My computer has GPUs. 

<img width="631" alt="image" src="https://github.com/gprMax/gprMax/assets/13006239/1a1efbd5-ab27-42cf-833a-cb22e679319f">

I can execute the following line successfully

`python -m gprMax user_models/cylinder_Ascan_2D.in`

but fail to do:

`python -m gprMax user_models/cylinder_Ascan_2D.in -gpu 0`

I got error message here:

<img width="1497" alt="image" src="https://github.com/gprMax/gprMax/assets/13006239/b79b29be-ec3b-43fe-bfcb-edd540fb713c">

Could you please advise me?

Thank you,

Linan XU

**Comment by craig-warren** [comment]
@tedmsxu can you test running one or two of the examples that come with the NVIDIA CUDA installation - https://developer.nvidia.com/cuda-code-samples, to make sure CUDA is working correctly on your GPUs.

**Comment by craig-warren** [comment]
@tedmsxu can you downgrade your Python version to 3.10.x and test (maybe the same as #380)
