### ISSUE TITLE
Memory required for model is not considering total available RAM + swap

### ISSUE THREAD

**Issue by nestor-sg** [gprMax/gprMax#364]
Hi, this is related to https://github.com/gprMax/gprMax/issues/209 in which I have the following error:
`gprMax.exceptions.GeneralError: Memory (RAM) required ~141GB exceeds 15.4GiB detected!`

gprMax is checking only the RAM available, and not the total available memory, which would include swap. For example, I have a total of 214G free considering RAM + swap:
```
(gprMax) nestor@wsl-rocky:~/gprMax/user_models$ free -ht
               total        used        free      shared  buff/cache   available
Mem:            15Gi       713Mi        14Gi       2.0Mi       360Mi        14Gi
Swap:          200Gi          0B       200Gi
Total:         215Gi       713Mi       214Gi
```
The linked issue https://github.com/gprMax/gprMax/issues/209 was closed on 2019 hinting that it was resolved. I'm using the latest v.3.1.6 (Big Smoke) from Apr 14, 2022.

- Is there any particular configuration flag to enable all memory to be detected?
- Is this still an open issue?

Many thanks!

**Comment by craig-warren** [comment]
@nestor-sg I'm on fieldwork at the moment and will look further when back in the office, but I think the basic rationale for this was that using swap to run models reduces performance massively, so only physical RAM should be considered.

**Comment by nestor-sg** [comment]
Thank you @craig-warren, no rush, hopefully it can be confirmed. I can appreciate the compromise that swap would cause on performance. 

Only reason why I'd like to confirm is due to properly consider budget/specs for a replacement server, we currently have 500 GB RAM in a server that will need to be replaced very soon, I was testing performance comparisons with a GPU-based workstation with much less RAM. If RAM is certainly needed for our needs, then we'll likely stick to a server option.

Cheers!

**Comment by craig-warren** [comment]
@nestor-sg we use the available memory metric (https://psutil.readthedocs.io/en/latest/index.html#psutil.virtual_memory) to determing whether model(s) can run on given hardware - this metric excludes swap. I think continuing with this metric is appropriate for most users as building and running model(s) on physical RAM will be faster than using swap. However, I have downgraded the check for available memory from an exception to a warning, which will let the user continue. However, clearly this may cause a crash if there is genuinely not enough memory.

**Comment by nestor-sg** [comment]
Thank you @craig-warren, I'd be happy to test it out when available. I understand and appreciate the compromise. Thanks for your reply. Cheers!

**Comment by craig-warren** [comment]
@nestor-sg no worries. Change available in the 'devel' branch now.
