### ISSUE TITLE
Lighting in Paraview

### ISSUE THREAD

**Issue by mzunguman** [gprMax/gprMax#37]
**@craig-warren**, I have a question regarding the .vti files that are produced by the "snapshots". Could be that this problem I have is Paraview-specific, I just couldn't find an answer. When opening the .vti files in paraview, there seems to be a greyish background that underlays all the colors from the colorbar (arbitrary in this case). This is not the background color of the *viewer* window in paraview, but a color behind the model data.

This makes the 2D-diagrams not as neat as they could be. Would you know how to go about this or have you had this issue before? Could it have to do with the fact that the "snapshots" produce a volume?

**Comment by craig-warren** [comment]
@mzunguman Can you upload an image of what you are seeing?

**Comment by mzunguman** [comment]
**@craig-warren**, here's one image of the many I created. Don't mind the geometry or lack thereoff you see there. The colorbar seems not the issue here because I tried out multiple ones. I wanted white to be in the middle and tried out multiple color palettes that incorporate this. I made sure that the opacity was set to 1 for all colors (that way white is not just a lack of color but actually the color white). However, and as you can see on the image, grey is always in the background and mixes with the colors.
[test.pdf](https://github.com/gprMax/gprMax/files/132257/test.pdf)
The main issue I had with this is that low amplitudes become barely visible, when keeping a constant colorbar over the entire simulation time. I've done previous simulations with other software where this color issue is not present and where the amplitudes at late times can still be seen. Therefore I don't think it's a matter of the amplitudes being generally to small, but that they can't be seen due to the grey overlay.

**Comment by craig-warren** [comment]
I suspect the grey colour is because of the colour map you are using in ParaView. I have tried the Cool to Warm (Extended) colour map, and with the background colour set to white I get no grey.

**Comment by mzunguman** [comment]
**@craig-warren**, I'm still seeing the grey overlay. But I'll continue working with that for the moment, thanks for help.

**Comment by mzunguman** [comment]
**@craig-warren**, I found the solution to my problem here. So the problem was that there was a gray overlay over the entire model and the colors. That is due to the lighting settings which have to be turned off. I didn't fiddle with the default settings beforehand so I think this might be a general issue when displaying field distributions. For beginners like me, you could maybe adress in the readme. Anyway, problem solved.

**Comment by craig-warren** [comment]
For reference to turn the default lighting off in Paraview:

- In the Properties panel click on the gear icon to turn on the advanced properties
- Go to the Lights section and click edit
- Uncheck the Light Kit check box and click Close

**Comment by craig-warren** [comment]
Added to tips section in docs - http://docs.gprmax.com/en/latest/output.html#geometry-output
