### ISSUE TITLE
no module named 'pyfiglet'

### ISSUE THREAD

**Issue by Robertmontro** [gprMax/gprMax#38]
Every time I try to simulate the cilinder_ascan_2d.in  it shows this message 
![image](https://cloud.githubusercontent.com/assets/17854292/13782745/b0513f24-eac8-11e5-9524-46b8ff23cf89.png)

I don't know what to do. I have made the instalation twice and downloaded the lastest version.

Please, help.

**Comment by craig-warren** [comment]
@Robertmontro the pyfiglet module should be installed when you configured Miniconda, i.e. ``conda env create -f conda_env.yml``. To check what is installed, with the gprMax environment activated run ``conda list`` and post the results here.

**Comment by Robertmontro** [comment]
![image](https://cloud.githubusercontent.com/assets/17854292/13787747/7c4be9e4-eadd-11e5-8596-17515f63a5bd.png)

**Comment by craig-warren** [comment]
Hmmm...strange pyfiglet should be installed automatically when you configured Miniconda. Anyway, with the gprMax environment activated you can install it with ``pip install pyfiglet``

**Comment by Robertmontro** [comment]
done.

Thanks. it's fixed

**Comment by Robertmontro** [comment]
I have another problem. it doesn't appeare no geometry of the sistem.

Wich program do i need?

**Comment by craig-warren** [comment]
@Robertmontro it is documented in the User Guide at [http://docs.gprmax.com/en/latest/geometry_snapshots.html](http://docs.gprmax.com/en/latest/geometry_snapshots.html)
