### ISSUE TITLE
Cannot use GPU with models that contain sub-grids.

### ISSUE THREAD

**Issue by DragonLT** [gprMax/gprMax#386]
When I tried to turn on GPU option when using subgriding, I got the following error:

    You cannot currently use CUDA or OpenCL-based solvers with models that contain sub-grids.
Does that mean the current beta version doesnot support the subgrids and GPU to work at the same time?

My way to call the gpu function in the python scripts is like this:
`gprMax.run(scenes=[scene], n=1, geometry_only=False, outputfile=fn, subgrid=True, autotranslate=True, gpu=[1])`
and this works well for other examples that donot use subgridding.

**Comment by craig-warren** [comment]
@DragonLT - correct there is no support for GPU with subgrids which is why you get that error meesage.
