### ISSUE TITLE
hdf5 file not generated with only transmission line source/receiver (v4)

### ISSUE THREAD

**Issue by mcooper12590** [gprMax/gprMax#390]
When running gprMax with a transmission line source/receiver and no other receivers an .h5 file is not created due to tl not being checked in model_build_run line 279. This effects the antenna_wire_dipole_fs example. Additionally, if the tl is in a subgrid without an rx in the subgrid the subgrid is not created in the .h5 file as it is not checked in field_outputs line 71.

**Comment by craig-warren** [comment]
@mcooper12590 I've made some changes which I think will fix this. Can you pull the devel branch and test again.

**Comment by mcooper12590** [comment]
It works after changing the typo G.G.subgrids in field_outputs line 72 to G.subgrids.

Thanks!

**Comment by craig-warren** [comment]
Thanks typo now corrected!
