### ISSUE TITLE
Installation in MacOS 10.16

### ISSUE THREAD

**Issue by rbernalo** [gprMax/gprMax#393]
Hello!
I´ve already sorted out many problems and warnings. But when finally trying this line:
(gprMax) MacBook-Pro-de-UIS:gprMax uis$ python -m gprMax gprMAx/new//name_of_input_file
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/uis/gprMax/gprMax/gprMax.py", line 30, in <module>
    import h5py
ImportError: No module named h5py
(gprMax) MacBook-Pro-de-UIS:gprMax uis$ python -m tools.plot_Ascan user_models/cylinder_Ascan_2D.out
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named tools

I have Python 3.8, so I don´t understand why it looks for Python 2.7. Any help will be appreciated!

**Comment by NiclasSchwalbe** [comment]
Same problem here with numpy!

**Comment by NiclasSchwalbe** [comment]
My problem got fixed by running some command like:

/Users/username/anaconda3/envs/gprMax/bin/python /Users/niclas/Documents/GitHub/gprMax/gprMax/setup.py build

Visual Studio Code outsmarted me with this solution!
