### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [gprMax/gprMax#397]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/gprMax/gprMax/assets/147402107/d93f0e98-e48f-4e8f-ac23-c98d2a6f1df3)

**Comment by Kalyanimhala** [comment]
@craig-warren  kindly assign me this issue, I want to work on it. Thank You!

**Comment by craig-warren** [comment]
@Kalyanimhala nice idea - happy for you to propose a PR for this.

**Comment by harshkasat** [comment]
Hey @craig-warren, I was thinking if it would be okay for me to take over @Kalyanimhala's's project since it seems like they haven't been able to respond in over a month. What do you think?

**Comment by harshkasat** [comment]
![image](https://github.com/gprMax/gprMax/assets/104870914/c85d79d1-3479-4fb8-9155-029178a2aebd)
 * @craig-warren  Do you have any suggestions on this?

**Comment by harshkasat** [comment]
Hi @craig-warren, I've created a pull request. Could you please check it out?
