### ISSUE TITLE
unrecognized arguments: -benchmark

### ISSUE THREAD

**Issue by Mark-Dunscomb** [gprMax/gprMax#40]
Hi,
I'm working to optimize my system configuration and greatly appreciate the idea of the benchmarking sub-packet described in the b23 User Guide. However, I'm working with b21 (the latest build that I've seen on github), which does not appear to have the sub-packet with it.  I therefore created a subfolder in the tests subfolder with the benchxxx.in files and replaced __input__.py with the latest file.  Still, gprMax does not recognize the -benchmark argument.  I'm obviously missing another file.  What is that and where may I find it?  Or.... is b23 available somewhere so that I can replace my b21 and use the benchmarking?
Thanks for your help!!!

**Comment by craig-warren** [comment]
@Mark-Dunscomb yes, making b21 work with the benchmarking sub-module would be tricky. I'll be doing a new release shortly, but you can always pull the latest code from the master branch and build the Cython modules yourself, see the 'Installation for developers' instructions at [http://docs.gprmax.com/en/latest/readme_install_devs.html#installation-for-developers](http://docs.gprmax.com/en/latest/readme_install_devs.html#installation-for-developers)

**Comment by Mark-Dunscomb** [comment]
Super, thanks for your help!

**Comment by craig-warren** [comment]
I've made a beta 24 release, so you can use that, if you don't fancy building your own. 

Please let us known how you get on with the benchmarking, as we'd like results from different OS'es and machines to help us with performance tuning.

**Comment by Mark-Dunscomb** [comment]
Definitely will.  Thanks.

**Comment by Mark-Dunscomb** [comment]
Hi Craig. The benchmarking worked well with two small issues; the user guide points you to using plot_benchmark from tools and it's located in tests.  Not a big deal.  Also, the plotting did not ask for equipment information but plotted the title from a Mac OS.   Attached images of the results.  One with a typical laptop and one with an older xeon CPU workstation.  We'll be ordering a newer workstation...  I re-titled them in the files to be correct.
Thanks again!

Thanks again!
![benchmarking_lenovo_t430_2 5ghz_intel_core_i5_3210m _windows7_150x150x150](https://cloud.githubusercontent.com/assets/17883893/13828556/68d5702c-eb98-11e5-8546-8a5a908ad0cb.png)
![benchmarking_dell_z420_xeon_es-1620_0_3 6ghz_windows7_150x150x150](https://cloud.githubusercontent.com/assets/17883893/13828557/68d977bc-eb98-11e5-82f3-d9cbb988efc5.png)

**Comment by craig-warren** [comment]
Interesting, the threading performance on the Dell is the best we have seen yet (although our benchmarks were with a slightly older version of the code). Can you post your NumPy files of the data, so I can add it to the archive.

**Comment by Mark-Dunscomb** [comment]
Hi Craig,
    I have them but don't have access to push files and can't attach them to this post (It won't accept the file type).  I'll need an email address or some other way to send them unless there is a simpler way via gitHub, which is very possible.  Thoughts?

**Comment by craig-warren** [comment]
@Mark-Dunscomb probably easiest just to email to info@gprmax.com
