### ISSUE TITLE
Bscan in 3D model

### ISSUE THREAD

**Issue by VNjinx** [gprMax/gprMax#401]
When performing Bscan simulation for 3D model, there is a big gap between the bscan simulation image of z=0 and z= 0.4, is it because of my in file writing problem or what.
![z=0 4](https://github.com/gprMax/gprMax/assets/150330619/f62a0a86-dc94-46f4-9a81-d3da43f196fb)
![z=0](https://github.com/gprMax/gprMax/assets/150330619/0a585727-ae50-47d4-afd3-718beeb6b5b1)
#domain: 1 1 1
#dx_dy_dz: 0.0025 0.0025 0.0025
#time_window: 2e-08

#waveform: ricker 1.0 500000000.0 mysource
#hertzian_dipole: z 0.1 0.98 0.4 mysource
#rx: 0.15 0.98 0.4
#src_steps: 0.02 0.0 0.0
#rx_steps: 0.02 0.0 0.0

#material: 4.0 0.004 1.0 0.0 liqing
#material: 9.0 0.005 1.0 0.0 jiceng
#material: 12.0 0.003 1.0 0.0 luji

#box: 0.0 0.0 0.0 1 0.8 1 luji
#box: 0.0 0.8 0.0 1 0.9 1 jiceng
#box: 0.0 0.9 0.0 1 0.95 1 liqing
#box: 0.0 0.95 0.0 1 1 1 free_space

#cylinder: 0.5 0.5 0 0.5 0.5 1 0.2 pec
#cylinder: 0.5 0.5 0 0.5 0.5 1 0.18 free_space

**Comment by craig-warren** [comment]
@VNjinx you are going to need to further explain what you mean. Your inout file is set to step sources and receivers in the x-direction to create a B-scan. If you are creating multiple B-scans, e.g. to build a 3D data set to slice, how are you modifying your input to achieve this? Also this is probably not a code issue, so you should post the question in our Google Group - https://groups.google.com/g/gprmax
