### ISSUE TITLE
Bug fix: Grid global object persists through multiple python API calls

### ISSUE THREAD

**Issue by ThomasRigoni7** [gprMax/gprMax#402]
In the master branch, the FDTDGrid object G in model_build_run.py is not deleted at the end of multiple simulation runs (after multiple A-scans). 

This causes the object to be still in the globals() of the module when the gprMax APIs are called again inside the same python program, causing all configuration and geometry to be incorrectly derived only from the first input file, even in the second run.

Will present a quick pull request to fix this issue.

**Comment by craig-warren** [comment]
@ThomasRigoni7 thanks for flagging this. I thought that the FDTDGrid object should be deleted  every time the model_build_run function is called unless the geometry_fixed flag is used. I'm guessing therefore you are using geometry_fixed and the issue occurs if you have multiple B-scans from a Python script using the API?

**Comment by ThomasRigoni7** [comment]
@craig-warren That is exactly what I'm doing, yes. 
The issue lies in the fact that after a B-scan the grid does not get cancelled if geometry_fixed is set, so, if run using the API, the variable will still be there and the first run of the next B-scan will reuse the old grid instead of creating a new one from the new input file.

**Comment by ThomasRigoni7** [comment]
I realized there might be an error in the pull request, done a new pull request #405  to fix it :)
