### ISSUE TITLE
Custom waveform behavior does not match docs (v4)

### ISSUE THREAD

**Issue by mcooper12590** [gprMax/gprMax#404]
In the documentation for the excitement file it reads:
"If there are less amplitude values than the number of iterations that are going to be performed, the end of the sequence of amplitude values will be padded with zero values up to the number of iterations."

However, if an excitation file contains a time column less than the number of iterations an error is thrown
```shell
ValueError: A value (...) in x_new is above the interpolation range's maximum value (...).
``` 
Adding fill_value="extrapolate" fixes the error, but the custom waveform past the last value extrapolates based on the fitting function kind="..." rather than pads with zeros, leading to unwanted behavior of the source.

**Comment by craig-warren** [comment]
@mcooper12590 I think it is the docs that perhaps need clarified. The assumption is that if you are supplying your own time vector then it is the correct length (number of iterations) for the model. It is only in the case that there is no time vector that padding will occur to the amplitude values.

**Comment by mcooper12590** [comment]
Thanks. I had gotten around it by using a start/stop time in the transmitter function. Clarifying in the docs would be helpful.

**Comment by craig-warren** [comment]
@mcooper12590 thanks I have updated the docs to clarify the behaviour for future users.
