### ISSUE TITLE
Run gprmax iteratively from python without saving files

### ISSUE THREAD

**Issue by alberto-battistel** [gprMax/gprMax#407]
I would like to use gprMax in an inverse problem and use it to simulate some measurements from a defined geometry. 
In the inverse problem formulation gprmax should run several times changing a few geometry or material parameters until the simulated results match the experimental ones. However the need to pass from .in files and .out files makes it very slow and troublesome. 
Is it possible to run gprmax in a loop and having the data only in the compiler workspace?

**Comment by craig-warren** [comment]
@alberto-battistel it is not a behaviour that is available in the master (current) or devel branch. However, there is nothing stopping you from making the necessary modifications to the code yourself....the beauty of open source! If you do investigate this I'd recommend you start from the devel branch as this will be easier and it will soon be the new version of gprMax anyway.

**Comment by craig-warren** [comment]
@alberto-battistel not straightforward to describe in a simple message! I would suggest you start (if you haven't already) with familiarising yourself with the structure of gprMax and main functions. Again I would do this in the devel branch as it has a more futureproof design.
