### ISSUE TITLE
question about Field Strength

### ISSUE THREAD

**Issue by ysx2023** [gprMax/gprMax#408]
in the demo B-scan from a metal cylinder you mentioned on http://docs.gprmax.com/en/latest/examples_simple_2D.html,can the peek value really reach about 1000V/m?can you tell me how to calculate the Ez using a math function so that i can check whether its right

**Comment by craig-warren** [comment]
@ysx2023 this is not a code issues - please post to our Google Group - https://groups.google.com/g/gprmax
