### ISSUE TITLE
Feeding point in an open-ended coaxial probe

### ISSUE THREAD

**Issue by alberto-battistel** [gprMax/gprMax#409]
I want to simulate an open-ended coaxial probe which, in my case, is simply an SMA connector. The connector's end exposes the inner conductor surrounded by the dielectric. Around the dielectric, there is a metal flange that composes the body of the connector.
How should the feeding point be simulated?
At the moment I created a 1 cm long PEC cylinder with a dielectric cylinder inside and a metal wire at the center. On the top, the dielectric cylinder is one cell shorter than the PEC cylinder which makes the connector metallically closed on one side. On the bottom, the dielectric is aligned with the PEC which makes for the open-ended side of the probe. The flange is simulated as a PEC box around the PEC cylinder. 
1. What should be used as feeding: a transmission line or a voltage source?
2. Where should the feeding be placed? Between the PEC top and the center wire? Should only the feeding be placed instead of the center wire?
3. Any other suggestion?

Thanks for the help

**Comment by craig-warren** [comment]
@alberto-battistel can you post this to our Google Group (https://groups.google.com/g/gprmax) please as it is not really a code issue.
