### ISSUE TITLE
GPU version

### ISSUE THREAD

**Issue by apcode** [gprMax/gprMax#41]
Any plans for a GPU version? You should get a 20-40x speedup on a GPU. You could also use pycuda so it nicely integrates with the current python.

**Comment by craig-warren** [comment]
@apcode For sure it is close to the top of the todo list :-) Just a question of finding time and resources.  pycuda and/or pyopencl both seem like interesting options. I also like the approach taken by http://www.pyfr.org (a Python-based CFD solver) who use these packages to create various different backends.

**Comment by agianno** [comment]
@apcode Indeed we have been looking and following the developments in the GPU scientific computing world for some years. In the early days as the size of the onboard memory in the GPUs was not much there was no much point in doing big FDTD models with them having to communicate matrix info back and forth from the CPU to the GPU. This was killing the speedup. These days you get cards that can hold the complete FDTD model in the GPU memory and these will provide great speedups. The way to do this is clear and possible BUT as @craig-warren has pointed out needs appropriate resource and time and maybe someone willing to work on this (it could be an interesting PhD ;-)). We are definitely keen to go down that route.

**Comment by Mark-Dunscomb** [comment]
@agianno Hi Antonis, any further thoughts and/or movement on incorporating GPUs?  I realize it's not a small undertaking but it's worth asking...  thanks!

**Comment by agianno** [comment]
@Mark-Dunscomb Hi Mark, the GPU code - based in CUDA - is ready and have been tested. As it has been developed for a specific project we are in the process of getting the final OKs from our funders to merge it with the main code. I am not sure how long this will take but I do hope we should be bale to launch it for IWAGPR 2017 that we are organising in Edinburgh (www.iwagpr2017.org) or earlier. So, it will be soon. Performance looks very good even for commodity cards like the Titan X and the 1080Ti

**Comment by Mark-Dunscomb** [comment]
@agianno Excellent!  I've got several projects I'm working on that unfortunately call for using a full antenna model on top of a rather large model space.  My last partial run went for 23 days.  Once I add in dispersion, randomization, etc.  You get the idea - I'm very interested in speeding up.  I'll keep an eye out for it and will definitely let you know how it performs.  Cheers and have a good weekend.
