### ISSUE TITLE
Problem with relation between parameter "beta" and fractal dimension "D"

### ISSUE THREAD

**Issue by dariuszPZ** [gprMax/gprMax#411]
When experimenting with different values of fractal dimension I discovered the distributions don't change continuously.
In fact when changing only "D" I can create only 6 different distributions. 

I think the problem is in the function 

`cpdef void generate_fractal3D(int nx, int ny, int nz, int nthreads, int b...` (fractals_generate_ext.pyx)

The function is called with "b" defined as:

`self.b = -(2 * self.dimension - 7) / 2`

Which is a float number, and it seems that implicit conversion  happens when calling a `generate_fractal3D(...)` for the parameter `int b`.

There seems to be another problem:

In the [thesis](https://era.ed.ac.uk/handle/1842/20449?show=full) cited in the gprMax doc we can find how to create the distribution and it is given by:
![image](https://github.com/gprMax/gprMax/assets/152518519/2d7ced48-0f7d-4f55-8cfb-077994122c48)

The relation between beta and "D" is given by (reference in the thesis)
![image](https://github.com/gprMax/gprMax/assets/152518519/a30f4df4-bbf5-4018-9532-c09fd287dcc7)

In the code the beta/2 is calculated as:
![image](https://github.com/gprMax/gprMax/assets/152518519/ffd9ad1b-777f-43bc-99ce-f7c9e88efa7d)

Then it is sent to the `generate_fractal3D()` (as the int) but then there seems to be another problem in function body:
![image](https://github.com/gprMax/gprMax/assets/152518519/a422cc9a-4d7f-4582-93ca-9419c45b71e4)

The sum is raised to the power of 1/2 and then raised to the power of beta/2 which at the end gives beta/4 which is different with the relation given in the text.

Please let me know is it expected behaviour or those are in fact bugs.

**Comment by agianno** [comment]
I think what is calculated there is (b/2) directly and not b but this should gave been commented better to be more clear. Need to check the function in more detail for the float to int conversion and why this happens

**Comment by dariuszPZ** [comment]
But it seems in the code that the sum(in the eq 6.12) is raised to the power b/4 not b/2.

**Comment by agianno** [comment]
We will have a better look but it seems that the code follows what is discussed in the thesis. It seems b is actually (\beta/2) (Figure 55 of the thesis) and the is used in the C function but passed as integer which needs to be investigated more. I believe what is generated is fractal and a stochastic distribution that seems reasonable but it needs to be more clear what formula follows exactly. I suspect you can experiment in your code by changing the int to a float and see what happens. It will need to be re-cythonised and recompiled but worth trying.

**Comment by dariuszPZ** [comment]
Some quick debugging:
For D = [1, 2, 3] I get self.b = [2.5, 1.5, 0.5] which is \beta/2 according to the relation.

Then we divide it again in the C function here(forget float - int conversion for a moment):
![image](https://github.com/gprMax/gprMax/assets/152518519/d8a72216-97b6-448c-a02f-667585263709)
Seems like dividing by two happens twice.

**Comment by agianno** [comment]
That is the square root that is needed in calculating the norm which is the distance from the centre to the position of the wavenumber. The actual power is 'b' of that norm but I can see your point as this does not seem to be the case in equation 6.12 which is (-b/2) and not (-1/2) * (b/2)

**Comment by craig-warren** [comment]
@dariuszPZ @agianno the int/float bug is now fixed, and I have update the behaviour of the fractal dimension (D) which is now passed directly, i.e. no longer is (2D - 7) used.

**Comment by dariuszPZ** [comment]
@craig-warren Thank you very much for the change.

However, I'm not sure how this is in agreement with the cited papers.

The thesis gives formula:
![image](https://github.com/gprMax/gprMax/assets/152518519/42770f92-90a3-4a99-9175-a525daa501a8)
With:
![image](https://github.com/gprMax/gprMax/assets/152518519/0096e47d-c7ee-4436-9200-6b47d95d657b)

The previous code used a formula:
![image](https://github.com/gprMax/gprMax/assets/152518519/f218eb06-9e89-473c-90d7-1d757e815de3)
(the beta parameter was divided twice)

Now it seems that the formula is:
![image](https://github.com/gprMax/gprMax/assets/152518519/48ec0858-bb6e-4712-980a-2aec43ce6559)
In terms of \beta:
![image](https://github.com/gprMax/gprMax/assets/152518519/289a4d26-edd5-43b5-92ce-9dcc746b4e6c)
