### ISSUE TITLE
Error in water epsilon r (master branch)

### ISSUE THREAD

**Issue by ThomasRigoni7** [gprMax/gprMax#413]
Hi, in the master branch, when using a fractal box with related surface roughness and adding some water with the command `#add_surface_water:`, the value for the relative permittivity epsilon r is set as the value at infinity equal to 4.9 (line 1098 of `input_cmds_geometry.py`).

I wasn't able to check if some other value, possibly dependent on the frequency, is used when advancing the simulation, but when exporting the geometry with `#geometry_objects_write:` the only line added to the materials file is `#material: 4.9 0 1 0 water`, without any debye dispersion associated to it, when the material has debye in its type. This is because in the aforementioned file the number of poles of the water material is kept at 0 and not set to 1.

The calculation for the er value when using the `calculate_er` function in `materials.py` seems to give sensible results to me (around 80 for frequencies around 1GHz), but I'm by far not an expert. This function, though, doesn't seem to me to be used in the code elsewhere, except than in the dispersion analysis.

This problem could lead to a different model of water being used between an regular input file and one in which the geometry has been saved and reloaded, also I suspect that the debye model is not applied to water in the first place, because when I try to add `m.poles = 1` at line 1098 of `input_cmds_geometry.py`, then the resulting A-scan is different.

In the picture in green and blue two original A-scans, black one loaded from the geometry files, red one with poles set to 1.
As you can see the red is the only differing one. Numerically also the black is slightly different, but very close.

![Ascan_water](https://github.com/gprMax/gprMax/assets/43821032/feccd185-4c67-4a66-947b-bf54accf4a1b)

from this source:
```
## General comands
#title: prova_acqua_2d
#domain: 0.2 0.3 0.002
#dx_dy_dz: 0.002 0.002 0.002 
#time_window: 2.5e-08 
#output_dir: prova_acqua_2d
#messages: n

## Source:
#waveform: ricker 1 1000000000.0 my_ricker 
#hertzian_dipole: z 0.08 0.25 0.001 my_ricker 
#rx: 0.12 0.25 0.001


#soil_peplinski: 1 0 4 5 0.001 0.002 my_soil_top
#fractal_box: 0 0.1 0 0.2 0.2 0.002 1.5 1 1 1 10 my_soil_top my_fractal_box_top 7
#add_surface_roughness: 0 0.1 0 0.2 0.1 0.002 1.5 1 1 0.05 0.15 my_fractal_box_top 7
#add_surface_water: 0 0.10 0 0.2 0.10 0.002 0.05 my_fractal_box_top

#soil_peplinski: 0.7 0.3 1 1.5 0.010 0.020 my_soil_bot
#fractal_box: 0 0 0 0.2 0.15 0.002 1.5 1 1 1 10 my_soil_bot my_fractal_box_bot 42
#add_surface_roughness: 0 0.15 0 0.2 0.15 0.002 1.5 1 1 0.05 0.15 my_fractal_box_bot 42

#geometry_view: 0 0 0 0.2 0.3 0.002 0.002 0.002 0.002 prova_acqua_2d_view n 
#geometry_objects_write: 0 0 0 0.2 0.3 0.002 prova_acqua_2d_geom
```

**Comment by craig-warren** [comment]
@ThomasRigoni7 thanks for spotting this, there is indeed a bug here that effects the builtin materials for water and grass that are generated when either the `#add_surface_water` or `#add_grass` commands are used.

Both water and grass are modelled as dispersive materials using a single pole Debye model. The setting of Er in the material command is correct as this adopts the value of relative permittivity at infinite frequency, e.g. for water is 4.9. However, the bug (as you spotted) is that the poles property of the material is never set to 1, so only some of the dispersive functionality is happening. I am about to fix this for both water and grass. **N.B this does not effect any user-defined dispersive materials as these are handled correctly.**

Incidently the `calculate_er` is only used for the dispersion analysis.

**Comment by craig-warren** [comment]
@ThomasRigoni7 the theory behind the dispersive material modelling approach is described by my colleagues @IraGia 
 and @agianno in their paper - https://ieeexplore.ieee.org/document/6748914 In particular we implement the Current Density Method described in section III.
