### ISSUE TITLE
'gbk' can't decode README.rst in setup.py

### ISSUE THREAD

**Issue by ambglh** [gprMax/gprMax#422]
how to solve
(gprMax) E:\laser\gprMax>python setup.py build
Traceback (most recent call last):
  File "setup.py", line 52, in <module>
    long_description = fd.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa8 in position 13936: illegal multibyte sequence

**Comment by ambglh** [comment]
windows 11 and Python 3.11

**Comment by craig-warren** [comment]
@ambglh odd. I don't have a Win11 installation to hand, but tested a new installation of gprMax on macOS with Python 3.11.x and saw no issues.

**Comment by harshkasat** [comment]
@ambglh, did you pull the latest changes from the master branch? I have the same specs as you, and I didn't encounter any errors when I ran `py setup.py build`.
![image](https://github.com/gprMax/gprMax/assets/104870914/aa1f0d67-8469-4ebf-8b45-622c43e2018d)

* Hardware & Software Stack
* Window 11
* python version 3.11

**Comment by realbili** [comment]
@ambglh hey, I'm having the same problem. and I just solved it. On Window 11 and python version 3.10.
<img width="677" alt="1709830242467" src="https://github.com/gprMax/gprMax/assets/93770744/2ba2b968-feb0-4a38-84c1-23b7d00b4250">
you need to change line 51 in `setup.py` from 'r' to 'rb'.
It not about python version or someting, just some decode methods, you probably will enconter this problem many times.

**Comment by craig-warren** [comment]
I don't think reading the file in binary mode is the answer, since this is a text file. I think the issue is with the encoding (and possibly only on MS Windows). I've added an explicit encoding arg to the file open call in https://github.com/gprMax/gprMax/commit/17d0a74402105c36cd30c4f86a930984878b7c7d. Can you see if this resolves the error @realbili @harshkasat @ambglh

**Comment by realbili** [comment]
@craig-warren It runs perfectly now, thanks a lot, Sir. 
My Platform is `Win 11` and `Python 3.10`, on `devel` branch
