### ISSUE TITLE
Problem about the snapshot of the electromagnetic fields using #snapshot command

### ISSUE THREAD

**Issue by sglx12345** [gprMax/gprMax#427]
I have added #snapshot: 0 0 0 0.240 0.210 0.002 0.002 0.002 0.002 2e-9 snap1 in the file cylinder_Ascan_2D.in to see its wavefield. The software successfully generated snap1.vti. When I use the Paraview to open it, it failed due to the error below:

Traceback (most recent call last):
  File "<string>", line 254, in <module>
  File "D:\ParaView 5.5.2-Qt5-Windows-64bit\bin\lib\json\__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "D:\ParaView 5.5.2-Qt5-Windows-64bit\bin\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\ParaView 5.5.2-Qt5-Windows-64bit\bin\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No
 JSON object could be decoded")
ValueError: No JSON object could be decoded

I changed the version of Paraview, but still not succeed. The vti file and in file is in attached files. How to solve this problem?
[cylinder_Ascan_2D.zip](https://github.com/gprMax/gprMax/files/14477834/cylinder_Ascan_2D.zip)

**Comment by craig-warren** [comment]
@sglx12345 I have no problem opening and viewing your snapshot file in Paraview. Are you sure you are following the instructions for viewing snapshots? See - https://docs.gprmax.com/en/latest/output.html#snapshots I think you may have tried to view this as a geometry file using the gprMax macro.

**Comment by sglx12345** [comment]
Thank you，the problem has been solved
