### ISSUE TITLE
This came up when I was trying to plot the orientation of the antenna

### ISSUE THREAD

**Issue by liutieyu0906** [gprMax/gprMax#430]
![image](https://github.com/gprMax/gprMax/assets/48509540/078e15db-e0dc-4989-9042-a792723fc7a6)

**Comment by craig-warren** [comment]
@liutieyu0906 thanks for spotting this. It was an issue with importing the electromagnetic constants - should be fixed in https://github.com/gprMax/gprMax/commit/d75ea4dc45315485f33e5b8ccac07501468851da

**Comment by liutieyu0906** [comment]
Thank you

**Comment by liutieyu0906** [comment]
Thank you very much for answering my questions and I look forward to seeing you in Changchun in June for the Ground Penetrating Radar International Conference!
