### ISSUE TITLE
When I visualise the GSSI 1.5 GHz antenna, I can't see the bowtie-shaped

### ISSUE THREAD

**Issue by liutieyu0906** [gprMax/gprMax#432]
![image](https://github.com/gprMax/gprMax/assets/48509540/5a7a4798-5a2f-46cb-93ab-0ca7dc0cc5ff)

**Comment by craig-warren** [comment]
@liutieyu0906 make sure you are visualising both (normal and fine) geometry views. The bowties which are made of plates will only show in the latter.
