### ISSUE TITLE
Slow model build time with v4 vs v3

### ISSUE THREAD

**Issue by liutieyu0906** [gprMax/gprMax#437]
![image](https://github.com/gprMax/gprMax/assets/48509540/5e1efc8a-8d21-4c31-8b90-7988155d9e0c)

**Comment by craig-warren** [comment]
@liutieyu0906  What command in your input file comes after the geometry view command? as this is command that is likely causing the slow down.

**Comment by liutieyu0906** [comment]
![image](https://github.com/gprMax/gprMax/assets/48509540/b4dc42cb-638f-4653-974e-fbb67acd531b)
There's nothing after the geometry view command.

**Comment by craig-warren** [comment]
@liutieyu0906 can you provide some comparative times between v3 and v4. If you set the time window of your model to something small so that it executes quickly, then provide the model run times and total simulation times (printed by gprMax) for v3 and v4. That should help get a better idea of the issue.

**Comment by liutieyu0906** [comment]
[gprmax.zip](https://github.com/gprMax/gprMax/files/15062427/gprmax.zip)
I have tested the time of v3 and v4 for the same model simulation, v3 took only 540 seconds to complete the program and v4 took 177 minutes and 56 seconds to complete the program, I have attached the model files that I used where horn_antenna.in and Runsimulation are the program for v3, horn_antenna_Bscan.py is the v4, and the txt file h5 is the file read in the model.

**Comment by fang123r** [comment]
how to download and use GPRMAX v4 version at present

**Comment by craig-warren** [comment]
@fang123r v4 is the 'devel' branch which you can pull/switch from GitHub. Please remember this is currently in beta.

**Comment by fang123r** [comment]
Where is the "devel" branch? I don't find it

**Comment by liutieyu0906** [comment]
You can find it here

> Where is the "devel" branch? I don't find it

**Comment by liutieyu0906** [comment]
![image](https://github.com/user-attachments/assets/abf71191-067d-4003-aa98-f94439869d35)


> Where is the "devel" branch? I don't find it

**Comment by fang123r** [comment]
Expert: Can you import a custom antenna model into GPRMAX for forward simulation?

**Comment by liutieyu0906** [comment]
> 专家：您可以将自定义天线模型导入GPRMAX进行前向仿真吗？

I'm trying this job at present

**Comment by liutieyu0906** [comment]
> Expert: Can you import a custom antenna model into GPRMAX for forward simulation?

I'm trying this job at present

**Comment by fang123r** [comment]
@craig-warren Hello experts, the following is the in file of my model, and there is an error of IndexError: list index out of range during the simulation process, I would like to ask what the error is.

#title: 3dguliao1
#domain：1 1 1
dx_dy_dz: 0.004 0.004 0.004
#time_window: 1e-7

#material: 1 0 0 0 air
#material: 6 0.01 0 0 aggregate

include: D:\3Dguliao\model_data.in

#wareform: ricker 1 1e9 my_ricker
#hertzian_dipole: z 0.1 0.2 0.2 my_ricker
#src_steps: 0 0.1 0
#rx-array: 0.9 0.2 0.2 0.9 0.8 0.8 0 0.1 0

#pem_cells: 10 10 10 10 10 10
#geometry_view:0 0 0 1 1 1 0.004 0.004 0.004 3dguliao1 n

Another question is whether it is possible to import a complex 3D model into gprmax for numerical simulation, this model is a model with irregular balls in 3D space that I built through Python code, and I know that the model can be imported into gprmax in the form of a 3D matrix by querying the data. However, I am currently getting an error of IndexError: list index out of range, and I would like to ask how to solve it.

**Comment by agianno** [comment]
Please use our Google group forum for questions and advice on modelling and input files that do not work. This is to report gprMax code bugs or issues.  

Your material specifications are wrong. The relative magnetic permeability (third parameter) cannot be zero. It needs to be one for non-magnetic materials.
