### ISSUE TITLE
about png2h5

### ISSUE THREAD

**Issue by WHATABLOCK** [gprMax/gprMax#439]
I'm reaching out to seek  advice on using the png2h5 command. When dealing with png images containing numerous colors, manual color selection becomes impractical. Do you have any suggestions to streamline this process?

**Comment by WHATABLOCK** [comment]
![tuoyuan](https://github.com/gprMax/gprMax/assets/164294247/ec135240-d4d2-4cbc-bbaf-d5f26b95842f)

**Comment by craig-warren** [comment]
@WHATABLOCK the png2h5 tool was intended as a way to import simple geometries from png images into gprMax. For more complex geometries and distributions of materials I suggest you try to use the #geometry_objects_read command and get your data into hdd5 format yourself. You can see what is required in the docs - https://docs.gprmax.com/en/latest/input.html#geometry-objects-read
