### ISSUE TITLE
Conda problem with non-ASCII username

### ISSUE THREAD

**Issue by TolunayAydin** [gprMax/gprMax#44]
When i tried conda env create -f... at the end of installation i got the following error.Can you help me?
Thanks in advance.
![ekran alintisi](https://cloud.githubusercontent.com/assets/18307172/14316089/c38ab50a-fc09-11e5-9a61-59585f8ff6c4.JPG)

**Comment by craig-warren** [comment]
@TolunayAydin this looks like an issue with Miniconda not gprMax. I've edited the title of your issue.

I suspect it may have something to do with non-ASCII characters in your username. Can you print the output of `conda info` please.

**Comment by TolunayAydin** [comment]
Thank you Craig i solved the problem by looking into another issue i used ''pip install pyfiglet'' command and it solved the problem.

**Comment by craig-warren** [comment]
Great, I'll close the issue then.
