### ISSUE TITLE
dokumentation not consistent  (snapshot)

### ISSUE THREAD

**Issue by igel89** [gprMax/gprMax#442]
The documentation of gprMax is no longer consistent with regard to snapshot.

https://docs.gprmax.com/en/latest/input.html#snapshot
--------------
#python:
for i in range(1, 31):
    print('#snapshot: x1 y1 z1 x2 y2 z2 dx dy dz {} snapshot{}'.format((i/10)*1e-9, i))
#end_python:
---------------
vs. 

https://docs.gprmax.com/en/latest/output.html#snapshots
-----------
#python:
from gprMax.input_cmd_funcs import *
for i in range(1, 31):
    snapshot(xs, ys, zs, xf, yf, zf, dx, dy, dz, (i/10)*1e-9, 'snapshot' + str(i))
#end_python:
--------------

**Comment by craig-warren** [comment]
@igel89 I don't see the issue here. The first examples prints the snapshot hash command and the second uses the snapshot API function. Two different ways of doing the same thing.
