### ISSUE TITLE
visualization with paraview

### ISSUE THREAD

**Issue by igel89** [gprMax/gprMax#443]
Thank you very much for the program, I am using it in my PhD at the RWTH Aachen (Germany)- Chair of Building Informatics and Geoinformation Systems and Geodetic Institute. 

I have the problem with the implementation of gprMax in Paraview (Macro). I get the following error message:
-------------------------
Traceback (most recent call last):
  File "<string>", line 170, in <module>
  File "C:\Program Files\ParaView 5.12.0\bin\Lib\site-packages\paraview\simple.py", line 750, in Hide
    raise ValueError ("proxy argument cannot be None when no active source is present.")
ValueError: proxy argument cannot be None when no active source is present.
Traceback (most recent call last):
  File "<string>", line 185, in <module>
  File "C:\Program Files\ParaView 5.12.0\bin\lib\ntpath.py", line 249, in dirname
    return split(p)[0]
  File "C:\Program Files\ParaView 5.12.0\bin\lib\ntpath.py", line 211, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not FileNameProperty
-------------
To minimze the sources of error I only use the example files from the gprMax User Guide. 

Execution of gprMax in miniconda
cd C:\Users\Igel\gprMax
conda activate gprMax

To test an animation with standard example: http://docs.gprmax.com/en/latest/examples_advanced.html
Since this is only a model and not an animation, the code for ‘snapshot’ is added as a loop ==> .vti

http://docs.gprmax.com/en/latest/input.html#snapshot
#python:
for i in range(1, 31):
print(‘#snapshot: x1 y1 z1 x2 y2 z2 dx dy dz {} snapshot{}’.format((i/10)*1e-9, i))
#end_python:

Insert the parameters from the 14th line of [heterogeneous_soil.in](http://heterogeneous_soil.in/)
print(‘#snapshot: 0 0 0 0.15 0.15 0.1 0.001 0.001 0.001 {} snapshot{}’.format((i/10)*1e-9, i))

Execute
python -m gprMax user_models/[heterogeneous_soil.in](http://heterogeneous_soil.in/)
Start Paraview
File/Open: user_models/snapshot1.vti
gprMax Macro activate
----
I typically use Windows 11 due to the error I have also tried an installation on Linux Ubuntu. However, it does not work with both.
I would be very grateful for an installation routine for gprMax, Paraview, python etc.  so which versions work together to display the results.

**Comment by igel89** [comment]
addition: The file folder is file folder is written with a big capital L. ->Lib
C:\Programme\ParaView 5.12.0\bin\lib\ntpath.py
C:\Programme\ParaView 5.12.0\bin\Lib\ntpath.py

**Comment by craig-warren** [comment]
@igel89 the Paraview macro button for gprMax is only for viewing the geometry files - where extra steps are necessary to visualise all the materials with the correct names. You do not need the macro for viewing the snapshot files - these can be opened and you can view the fields directly. See the steps to view snapshots in the docs - https://docs.gprmax.com/en/latest/output.html#snapshots
