### ISSUE TITLE
#time_step_limit_type ???

### ISSUE THREAD

**Issue by SajadJ** [gprMax/gprMax#45]
Hello Craig,

I just installed the latest developer version on Mac, and a test revealed that the "#time_step_limit_type:" command is not recognized by the latest version https://github.com/gprMax/gprMax/tree/v.3.0.0b26. 

Is it replaced by a new command? How are you defining a 3D (mean multiple profiles) survey? 

Thanks much,
Sajad

**Comment by craig-warren** [comment]
@SajadJ the `#time_step_limit_type` command is no longer required, as it is now set automatically according to the domain size, i.e. 2D or 3D.

What do you mean by a 3D survey? gprMax can produce B-scans of survey lines. We don't have a post-processing tool to do depth slicing of multiple B-scans if thats what you mean.

**Comment by SajadJ** [comment]
Got it! Thanks.
