### ISSUE TITLE
No module named 'gprMax.fields_updates_ext'

### ISSUE THREAD

**Issue by KeepFighting2024** [gprMax/gprMax#450]
Dear Developer
        I have download the latest version of the gprMax. I have created the conda venv(python = 3.12) and followed the guide to install. But when I used the order 'python -m gprMax user_models/cylinder_Ascan_2D.in', it came out ' No module named 'gprMax.fields_updates_ext''. I have tried reinstall the file but failed to solve.

**Comment by craig-warren** [comment]
@KeepFighting2024 that suggests you have not built gprMax correctly, i.e. the build and install phase has failed.
