### ISSUE TITLE
Non-diagonal anisotropy

### ISSUE THREAD

**Issue by Europium-152** [gprMax/gprMax#451]
Is it possible to add a material with non-diagonal anisotropy such as a cold magnetized plasma?

**Comment by agianno** [comment]
Sadly, the answer is no. The non-diagonally anisotropic case in FDTD  is more complex and is not yet supported. The main reason is that such anisotropy is not found in GPR related modelling scenarios. The formulation is known but it is not as trivial to properly implement quickly. It will be a nice addition but we will need someone to take it on as a project.
