### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by xncoin** [gprMax/gprMax#453]
Hello

I'm trying to calculate this project and I receive this error

line 327, in dispersion_analysis
    freqthres = np.where(power[freqmaxpower:] < -G.highestfreqthres)[0][0] + freqmaxpower
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0

please could you help with this issue

the file is attached 

With kind regards

[Section_2314_.zip](https://github.com/user-attachments/files/16134378/Section_2314_.zip)

**Comment by craig-warren** [comment]
@xncoin you need to understand numerical dispersion. Please see our docs on GPR modelling, particularly on choosing your spatial discretisation - https://docs.gprmax.com/en/latest/gprmodelling.html#spatial-discretization

**Comment by xncoin** [comment]
Hello

I tried to decrease step by X and Y but now I have the error message  

n process_singlecmds
    raise CmdInputError(cmd + ' has too many cells for the domain size')
gprMax.exceptions.CmdInputError: #pml_cells has too many cells for the domain size


With regards
Andrey

**Comment by agianno** [comment]
@xncoin this is not a gprMax bug but a problem of understanding how to use it. Please use our Google Forum https://groups.google.com/g/gprmax to ask questions or check the documentation carefully for the steps to build a model.
