### ISSUE TITLE
BScans

### ISSUE THREAD

**Issue by apcode** [gprMax/gprMax#46]
I'm having a problem with running multiple tx rx positions. I'm clearly missing something.
e.g.
> python -m gprMax user_models/cylinder_Bscan_2D.in
followed by
> python -m tools.plot_Bscan user_models/cylinder_Bscan_2D.out Ez
fails with our-of-range.

It seems there is only one time trace per run.
The documentation says: Provide a simple method to allow you to move the location of all sources (#src_steps) or all receivers (#rx_steps) between runs of a model. 

What does it mean by "between runs of the model"?
If I run it once I only get 1 trace, even though I've specified the tx/rx_steps. 
If I run it multiple times I still only get 1 trace.

I'm clearly missing something, help please!

**Comment by craig-warren** [comment]
@apcode You are correct the `#src_steps` and `#rx_steps` are an easy way to move all sources and receivers. However, you must use them in combination with running the model multiple times, to produce multiple A-scans that comprise a B-scan. For example with the command:

`python -m gprMax user_models/cylinder_Bscan_2D.in -n 60`

This example model might help clarify [http://docs.gprmax.com/en/latest/examples_simple_2D.html#b-scan-from-a-metal-cylinder](http://docs.gprmax.com/en/latest/examples_simple_2D.html#b-scan-from-a-metal-cylinder)

**Comment by apcode** [comment]
Aha, -n 60, that's the "something obvious" I was missing :)
Thanks.
