### ISSUE TITLE
geometry_objects_read material parameter

### ISSUE THREAD

**Issue by igel89** [gprMax/gprMax#464]
I want to read the geometry of a 3-layer soil model from laser-scanned data. #geometry_objects_read: f1 f2 f3 file1 file2
This works so far, but I can't assign different materials to the layers. My problem now is that I have not received a reply despite multiple requests AustinMan
https://web.corral.tacc.utexas.edu/AustinManEMVoxels/AustinMan/download/index.html
 and so I don't know how the assignment for file2 with the different material parameters is structured.
Please provide a short example of how this is structured.

**Comment by craig-warren** [comment]
@igel89 not sure what you are asking here, in any case you don't need access to the AustinMan model to see how the materials file for the #geometry_objects_read command should be structured - that is already in the gprMax package, see https://github.com/gprMax/gprMax/blob/master/user_libs/AustinManWoman/AustinManWoman_materials.txt
