### ISSUE TITLE
Time step calculations seems to be wrong in the new update

### ISSUE THREAD

**Issue by rajathkumarmp** [gprMax/gprMax#47]
For all the models the 'dt' or time step is not adhering to the CFL condition as said in "Guidance for GPR Modelling" section.

In the example cylinder_Bscan_2D.in, provided, when `print(f.attrs['dt']])` is run in the plot_Bscan.py file it displays,

4.7173086735e-12

But when the CFL condition is solved manually the result is,

3.85166640309e-12

Which is clearly greater (which should not be)

This was perfect in the previous versions. But appears to have changed.

This is incorrect right?

**Comment by craig-warren** [comment]
@rajathkumarmp 4.717e-12 seconds is the correct time step at the CFL limit for this 2D model which has a 2mm spatial resolution in all directions, i.e. dt = dx / (sqrt(2) * c)

**Comment by rajathkumarmp** [comment]
@craig-warren But the formula provided in the docs, http://docs.gprmax.com/en/latest/gprmodelling.html#guidance

when we substitute 2mm there it outputs 3.85166640309e-12

Thus got confused.

dt=dx/(sqrt(2)*c) is the right one?

**Comment by craig-warren** [comment]
@rajathkumarmp The formulae are same, as the docs state 

> The stability condition for the 2D case is easily obtained by letting delta z tend to infinity

**Comment by rajathkumarmp** [comment]
@craig-warren Ohh ok! I was considering even dz too. Understood. Thank you
