### ISSUE TITLE
CmdInputError

### ISSUE THREAD

**Issue by GHozzi** [gprMax/gprMax#48]
Hi,
Thanks before for guiding me until now.
when I try to simulate this example , I get some error (see Fig). What should I do to fix this problem? Thank you  :)

----------------------------------------------------------------------------
#domain: 2.000 2.000 1.000
#dx_dy_dz: 0.01 0.01 0.01
#time_window: 12e-9 
#material: 3 0 1 0 dry_sand 
-------------------- Geometry of the problem defined here-----------------
#box: 0.0 0.0 0.0 2.000 2.000 0.850 dry_sand
#cylinder: 0.0 1.000 0.605 2.000 1.000 0.605 0.035 free_space
---------------------------------------------------------------------------
#python:
from user_libs.antennas import antenna_like_GSSI_1500
antenna_like_GSSI_1500(1.00, 0.075 + current_model_run * 0.05 , 0.86)
#end_python:
--------------------------------------------------------------------------

![capture1](https://cloud.githubusercontent.com/assets/16916511/15090855/6ca7a47c-142e-11e6-9e72-d150a0591e0b.jpg)

**Comment by craig-warren** [comment]
Looks like a rounding issue. Your version is pretty old, can you update to the latest version and try again.

**Comment by GHozzi** [comment]
Hi @craig-warren , 
I update gprMax-v.3.0.0b26, but i got the same error and when  i changed #dx_dy_dz: 0.01 0.01 0.01, by  #dx_dy_dz: 0.001 0.001 0.001
I got the error message: 

![scan1](https://cloud.githubusercontent.com/assets/16916511/15092428/d8189e2e-1469-11e6-92d1-70c3658d6608.png)

I do not know how that mistake was made.

**Comment by craig-warren** [comment]
You have a couple of problems:

- Your model is massive! Look at the messages....4 billion cells and 287GB RAM....you have 8GB.
- If you read the module on using the antennas you'll see they can only be used at 1mm or 2mm resolutions.

Craig

**Comment by GHozzi** [comment]
Hi,


when I try to simulate one example from user_model, I get some error. And, I cannot view vti (geometry) from Paraview

**Comment by GHozzi** [comment]
Hi @craig-warren ,

Sorry for the delayed response.  I fixed the above-mentioned error. 

When i want to just check the geometry of the model, (using the optional command line
argument --geometry-only),  I cannot view vti (geometry) from Paraview. Similarly, for the example from user_model (cylinder_Bscan_GSSI_1500.in).

**Comment by craig-warren** [comment]
@GHozzi Can you give some more details of the issue with viewing geometry please.

**Comment by GHozzi** [comment]
I similated geometry of the model (python -m gprMax user_models\cylinder_Bscan_GSSI_1500.in --geometry-only) 
After simulation, i don't find cylinder_GSSI_1500.vti 
For an other example it's worked verry well (For example : python -m gprMax user_models\cylinder_Ascan_2D.in --geometry-only) i found cylinder_half_space.vti

Thank you again for your help @craig-warren 

![capture1](https://cloud.githubusercontent.com/assets/16916511/15177107/4fee2352-1766-11e6-8865-2adabe0a01a4.jpg)

**Comment by craig-warren** [comment]
That's because there is no ``#geometry_view`` command in the ``cylinder_Bscan_GSSI_1500.in`` model. If you want to see the geometry you should add a hash sign in front of ``geometry_view`` to make it a command. You should have seen there was no ``#geometry_view`` command processed in the messages that were printed?

**Comment by GHozzi** [comment]
Ohhh Yes!! I didn't pay attention. Thanks @craig-warren 
I have another issue. Do I have to change values of #domain ( from a lowering of the values )?

![capture](https://cloud.githubusercontent.com/assets/16916511/15180508/0445353a-177a-11e6-8b49-e212622d2c34.jpg)

**Comment by craig-warren** [comment]
@GHozzi I can't tell from your screenshot what domain size you are using, nor what geometry view you have specified. However, I can see you are using an outdated version of the gprMax Paraview macro. Install the new one from the gprMax package in tools->Paraview macros.

All of the information on using the commands has been carefully documented at: [http://docs.gprmax.com](http://docs.gprmax.com)

**Comment by GHozzi** [comment]
Thank you Very much @craig-warren
