### ISSUE TITLE
figure saving issue

### ISSUE THREAD

**Issue by mzunguman** [gprMax/gprMax#49]
I think I found a small error in your new plotting scripts. When trying to save the files, the variable "filename" has to be passed instead of "file". See for example line 342 in the plot_antenna_params.py file. 

Cheers,
Sam

**Comment by craig-warren** [comment]
Thanks for the spot, now fixed in the master branch.

**Comment by mzunguman** [comment]
I think a similar issue came up after the latest update. The filename needs to be passed to the function "mpl_plot" when trying to save the plots.

**Comment by craig-warren** [comment]
Thanks. Now updated.
