### ISSUE TITLE
plotting geometry

### ISSUE THREAD

**Issue by SajadJ** [gprMax/gprMax#5]
I added a fractal_box including a rectangular anomaly (not among predefined materials) as my medium. Using '--geometry-only' I plotted the geometry of the case. But It's not showing the anomaly (in paraview)! 
I changed the kind of anomaly to 'pec' to see if there is an error or not, it worked perfectly and geometry was drawn without an issue. Can you please help me with this issue?   
A picture of issue is attached as well.
![untitled](https://cloud.githubusercontent.com/assets/15625017/10902262/34abbb1e-81c9-11e5-9089-9f09666385d4.jpg)

**Comment by craig-warren** [comment]
Hi Sajad, We have done testing with dielectric targets embedded in heterogeneous soils (using the `#fractal_box` command) and not observed this problem. 

Firstly, can you check you are adding the anomaly after the `#fractal_box`? Secondly, please attach a copy of your input file to this issue, as it will make problem solving much easier.

**Comment by SajadJ** [comment]
Hello Craig, 
Yes, I'm adding the anomaly command (#box) right after #fractal_box command. I was not able to attach the file here, so I'm copying the text below:
-----------------------------------------------------------
-----------------------------------------------------------
#title: B-scan from an object buried in a heterogeneous soil 
#domain: 0.50 0.220 0.001
#dx_dy_dz: 0.001 0.001 0.001
#time_window: 8e-9
#time_step_limit_type: 2D
#pml_cells: 10 10 0 10 10 0

#material: 6 0 1 0 half_space
#soil_peplinski: 0.4 0.6 2.0 2.66 0.001 0.25 soil_pep
#material: 2.9 1.0 1.0 0.0 plastic

#waveform: ricker 1 1.5e9 my_ricker
#hertzian_dipole: z 0.100 0.170 0 my_ricker
#rx: 0.020 0.20 0
#src_steps: 0.01 0 0
#rx_steps: 0.01 0 0


#fractal_box: 0.0 0.0 0.0 0.50 0.200 0.001 2 1 1 1 10 soil_pep my_fractal_box 2
#box: 0.2 0.1 0.0 0.30 0.150 0.001 plastic


#geometry_view: 0 0 0 0.50 0.2 0.001 0.01 0.01 0.01 plastic f

**Comment by craig-warren** [comment]
Hi Sajad, There are a few issues with your input file:

* The main problem is with the `#geometry_view` command. You are using a spatial resolution of 1mm for the model and it is 2D (with 1 cell the z-direction). However, you have requested a 10mm spacing in your `#geometry_view` which is clearly not possible. 
* You probably don't require per-cell-edge geometry information (`f` option), so use the per-cell (`n` option) instead. 
* Be careful about the positioning of your sources and receivers
• Your plastic material has a conductivity of 1 S/m

When I run your model correcting the `#geometry_view` command, i.e. `#geometry_view: 0 0 0 0.5 0.22 0.001 0.01 0.01 0.001 plastic n`,  I can see the plastic box in the soil.

**Comment by SajadJ** [comment]
You are absolutely right! Thank you so much.
Now, it works. The most effective change in this case is f --> n.
Thanks again
