### ISSUE TITLE
What Python packages are required?

### ISSUE THREAD

**Issue by samfux84** [gprMax/gprMax#51]
Hi,

could you please provide a list with Python packages that are required to install gprMax ? Not everybody likes anaconda/miniconda.

Best regards

**Comment by craig-warren** [comment]
@samfux84 you can see what packages are required by looking at the ``conda_env.yml`` file https://github.com/gprMax/gprMax/blob/master/conda_env.yml

**Comment by samfux84** [comment]
Thank you very much for the fast reply.
