### ISSUE TITLE
conda - hdf5 version issue

### ISSUE THREAD

**Issue by mzunguman** [gprMax/gprMax#54]
**@craig-warren**,

I'm reinstalling the latest issue of gprMax due to some server issues I had. When compiling the Cython extensions I get the error starting with "_Sorry:_" in the attached file. Could be related to the server, but maybe you know the reason for this. Updating from the repo has always worked so far. I can't run gprMax at the moment and I'm guessing it's due to this error. Any ideas?

![sam_scr](https://cloud.githubusercontent.com/assets/15184186/15652163/7e5de286-2684-11e6-88eb-7c146260dc23.png)

**Comment by craig-warren** [comment]
I have fixed the indentation error, but that shouldn't have effected being able to run gprMax. What error did you get when trying to run?

**Comment by mzunguman** [comment]
**@craig-warren**,

Thanks for the quick reply. Thought as much. The error I get is below. Probably not related to gprMax but to the Miniconda environment and that it can't get the right version of the HDF5 libary, even though the new version is installed. I think it's an issue with the path. 

![sam_scr_2](https://cloud.githubusercontent.com/assets/15184186/15653034/a14cd170-268a-11e6-8caf-fec268337fa7.png)

**Comment by craig-warren** [comment]
Yeh, I think you probably need to update the gprMax environment. Just run ``conda update --all`` with the environment activated.

**Comment by mzunguman** [comment]
**@craig-warren**,

Thanks for the quick reply. Thought as much. The error I get is below. Probably not related to gprMax but to the Miniconda environment and that it can't get the right version of the HDF5 libary. On our server we have 1.8.17, but Miniconda has version 1.8.16 installed and that's where he should be looking to my knowledge.

![sam_scr_4](https://cloud.githubusercontent.com/assets/15184186/15705375/56f38c16-27ef-11e6-9dc2-bd4dca9fd4de.png)

**Comment by craig-warren** [comment]
Yeh, that does sound like a path issue. Is the conda environment listed first when you do ``echo $PATH``?

**Comment by mzunguman** [comment]
Yes it is. I want to show you a new error I get. I tried installing it again without the Miniconda environment, as I've always done in the past, but I get this strange error now which I don't understand.

![sam_scr_5](https://cloud.githubusercontent.com/assets/15184186/15776476/074c7a20-2988-11e6-84d8-73ba37262beb.png)

**Comment by craig-warren** [comment]
@obtitus Do you think the SyntaxError in ``input_cmd_funcs.py`` is related to Python 3.4?

@mzunguman This is not a problem that should effect you unless you are using Python in your input files and using functions from ``input_cmd_funcs.py``.

**Comment by obtitus** [comment]
Sorry about that, the pull request should fix it.

**Comment by craig-warren** [comment]
@obtitus Awesome thanks.

**Comment by mzunguman** [comment]
**@craig-warren**

Just wanted to make a last remark, in the hopes that it might help others as well. I solved my problem by manually setting the PATH and LD_LIBRARY_PATH variables. I don't know enough about administrating linux servers and how these path variables are handled on a multi-user system, but the following step was necessary for me. I would be thankful for suggestions, improvements or explanations for this. By entering the conda environment, a library path to the _/miniconda/envs/gprMax/lib_ has to be set, otherwise he was using the hdf5 version installed on the system. I previously thought the path which is set by miniconda when entering the gprMax environment was sufficient. Below are the two lines I added:

_- export PATH="/home/stadler/miniconda3/bin:/home/stadler/miniconda3/envs/gprMax/bin:$PATH"_
_- export LD_LIBRARY_PATH="/home/stadler/miniconda3/lib:/home/stadler/miniconda3/envs/gprMax/lib:$LD_LIBRARY_PATH"_

**Comment by craig-warren** [comment]
I think when you first install Miniconda it gives you the option for it to add the Miniconda bin directory to your path, usually via your  ``.bash_profile``

**Comment by mzunguman** [comment]
yeah it does. That's the first portion of the path, and I thought that was enough too. But, for me at least, only after I add the second set of paths does it seem to work.

**Comment by craig-warren** [comment]
Are you sure the environment is being activated correctly? When I activate an environment the following happens:

`w5067:~ cwarren$ source activate gprMax`
`discarding /Users/cwarren/miniconda3/bin from PATH`
`prepending /Users/cwarren/miniconda3/envs/gprMax/bin to PATH`
`(gprMax)w5067:~ cwarren$ `

**Comment by mzunguman** [comment]
In the past as well as now, I got the same message. It must be the new _LD_LIBRARY_PATH_ path I entered that did the trick for me. Don't know why...
