### ISSUE TITLE
Transmission line on receiver antenna

### ISSUE THREAD

**Issue by mzunguman** [gprMax/gprMax#59]
I wanted to know what input options one should use for the transmission line at the receiver? When specified after the transmission line source, does it matter at all? I though of a zero-array.

**Comment by craig-warren** [comment]
You can use a ``#transmission_line`` on a receiver antenna by associating it with a waveform of zero amplitude, e.g.

``#waveform: gaussian 0 1e9 my_zero_src``
``#transmission_line: x 0.1 0.1 0.1 50 my_zero_src``
