### ISSUE TITLE
Centre frequency of ricker and gausiandotdot waveforms

### ISSUE THREAD

**Issue by craig-warren** [gprMax/gprMax#6]
Centre frequencies of the second derivative of a Gaussian and ricker wavelet waveforms that is displayed in the power spectrum is not what is specified by the user. Plotting uses the `plot_waveform` function.

**Comment by craig-warren** [comment]
Both normalised and unnormalised versions of the gaussiandot waveform exhibit this behaviour. I have checked differentiation from the gaussiandot and it looks OK. Next stage is to check the FFT/plotting.

**Comment by agianno** [comment]
I have been looking into the difference of the power spectra and it 
looks that the second order one is a function of omega^2 and the first 
of omega. That is expected as differentiation is multiplying by 
-J*Omega. It looks like we need to scale the frequency of the second 
order gaussian and the norm version by an sqrt(2). So, if the user 
specifies a 500E6 internally this needs to be scaled by sqrt(2) so the 
frequency used by the second order gaussian needs to be 500E6/sqrt(2).

I think the parameters chi, freq, delay and zeta need to change 
accordingly and they cannot be the same for all pulses ...

A


Craig Warren wrote:
>
> Both normalised and unnormalised versions of the gaussiandot waveform 
> exhibit this behaviour. I have checked differentiation from the 
> gaussiandot and it looks OK. Next stage is to check the FFT/plotting.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gprMax/gprMax/issues/6#issuecomment-157081685>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>

**Comment by agianno** [comment]
Fixed by introducing the correct scaling to the frequency requested by the user.
