### ISSUE TITLE
"TypeError: __init__() takes 3 positional arguments but 4 were given" in Linux

### ISSUE THREAD

**Issue by JonhatanBarriga** [gprMax/gprMax#63]
Hi Craig:

I tried to run "heterogeneous_soil.in" in Linux, but appear:
![image](https://cloud.githubusercontent.com/assets/20345667/16670382/ef83e612-4467-11e6-8782-4fd516717b31.png)

With the following error:
TypeError: __init__() takes 3 positional arguments but 4 were given

Thanks.

**Comment by craig-warren** [comment]
@JonhatanBarriga thanks for spotting this. It was a typo/bug introduced on 30 June. It is fixed in v3.0.3.

**Comment by JonhatanBarriga** [comment]
Thanks Craig.
