### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by sohn6124** [gprMax/gprMax#64]
Dear Sir,

 How could you insert the noise  in the radargram(Ascan and Bscan) ?

Thanks.

**Comment by craig-warren** [comment]
@sohn6124 your question is not really an issue or bug with the code, so please post your question in our Google Group (Forum) where you will likely get a better response - [http://www.gprmax.com/forum.shtml](http://www.gprmax.com/forum.shtml) Also you'll have to be more specific about the source of noise you are referring to.
