### ISSUE TITLE
Non-ASCII character in Windows username

### ISSUE THREAD

**Issue by utkuyilmaz-metu** [gprMax/gprMax#65]
Hello,

When I try to installed the version 3.0.0. I get the error that I atteched beow while building the code on Windows 10. I've read a bit about this error, tried some solutions.
Even I found someone complaining about same problem here and you guys suggested installing visual c++ 2015 redist x64 14.0.23026. I had a more recent version of this redist. but in anyway; I uninstalled it and install the one you suggested. Still getting the same error. Do you have any suggestions about it?

> (gprMax3) E:\gprMax>python setup.py build
> Running 'build_ext --inplace'
> running build_ext
> building 'gprMax.fields_update' extension
> Traceback (most recent call last):
>   File "setup.py", line 176, in <module>
>     include_dirs=[np.get_include()])
>   File "C:\Miniconda3\envs\gprMax3\lib\distutils\core.py", line 148, in setup
>     dist.run_commands()
>   File "C:\Miniconda3\envs\gprMax3\lib\distutils\dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "C:\Miniconda3\envs\gprMax3\lib\distutils\dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "C:\Miniconda3\envs\gprMax3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\build_ext.py", line 66, in run
>   File "C:\Miniconda3\envs\gprMax3\lib\site-packages\Cython\Distutils\build_ext.py", line 164, in run
>     _build_ext.build_ext.run(self)
>   File "C:\Miniconda3\envs\gprMax3\lib\distutils\command\build_ext.py", line 338, in run
>     self.build_extensions()
>   File "C:\Miniconda3\envs\gprMax3\lib\site-packages\Cython\Distutils\build_ext.py", line 172, in build_extensions
>     self.build_extension(ext)
>   File "C:\Miniconda3\envs\gprMax3\lib\site-packages\setuptools-23.0.0-py3.5.egg\setuptools\command\build_ext.py", line 178, in build_extension
>   File "C:\Miniconda3\envs\gprMax3\lib\distutils\command\build_ext.py", line 532, in build_extension
>     depends=ext.depends)
>   File "C:\Miniconda3\envs\gprMax3\lib\distutils\_msvccompiler.py", line 306, in compile
>     self.initialize()
>   File "C:\Miniconda3\envs\gprMax3\lib\distutils\_msvccompiler.py", line 199, in initialize
>     vc_env = _get_vc_env(plat_spec)
>   File "C:\Miniconda3\envs\gprMax3\lib\distutils\_msvccompiler.py", line 92, in _get_vc_env
>     universal_newlines=True,
>   File "C:\Miniconda3\envs\gprMax3\lib\subprocess.py", line 626, in check_output
>     kwargs).stdout
>   File "C:\Miniconda3\envs\gprMax3\lib\subprocess.py", line 695, in run
>     stdout, stderr = process.communicate(input, timeout=timeout)
>   File "C:\Miniconda3\envs\gprMax3\lib\subprocess.py", line 1059, in communicate
>     stdout = self.stdout.read()
>   File "C:\Miniconda3\envs\gprMax3\lib\encodings\cp1254.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> **UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 55: character maps to undefined**

**Comment by craig-warren** [comment]
@utkuyilmaz-metu I have a couple of suggestions to try:

1. Does your user name contain any non-ascii characters? We have seen an issue #44 with conda and that before.
2. Also conda seems to sometimes have problems when installed for 'All users' on Windows, which I can see you have done from the traceback.
3. Lastly, can I check that you pulled the latest code (from the master branch of GitHub) using git?

I'll have a check on my Windows 10 virtual machine tomorrow to see if I can see anything.

**Comment by utkuyilmaz-metu** [comment]
Hello Craig,

It's definetely because of my user name (ah, how did I make such a mistake). My user name contains non-ascii character, ı ( i without the dot ). 
I am pulling the latest code with git clone.
But in #44, the user solved the problem with an alternative method (by installing missing package with pip install pyfiglet). 
Now I am checking any methods to overcome this problem. 
I believe it's too late to change my user name.

Also, thank you for your fast reply. 
Do you have any recommendations?

**Comment by craig-warren** [comment]
@utkuyilmaz-metu Can I just quickly confirm you definitely have Python 3 installed, i.e. ``python -V`` shows ``Python 3.5.2 :: Continuum Analytics, Inc.``

**Comment by craig-warren** [comment]
@utkuyilmaz-metu I just did a quick test on my Windows 10 VM and created a user account named ``yılmaz`` I couldn't get Miniconda or even Firefox to install. Therefore I recommend (if you can) you create another user account.

**Comment by utkuyilmaz-metu** [comment]
Hello Craig,

Sorry for late (very late indeed) response. 
But I couldn't work on this problem and continued with beta versions. 
But now; i've solved the problem. 

Briefly; 
I was getting Unicode Decode Error while building.
It was because of my username, which contains non-ASCII character.
I created a new user with ASCII username.
I logged in with it, installed Anaconda (or Miniconda) for that user only.
Then, I built and installed gprMax with this user. It was working well for that user.
When I switch back to my original user account, everything was okay as well.
Thanks for your great help Craig.

You may close the issue now :)

**Comment by craig-warren** [comment]
Glad you found a workaround.
