### ISSUE TITLE
Error with conda install on Windows and mpi4py

### ISSUE THREAD

**Issue by ugy77** [gprMax/gprMax#66]
hi Craig, 
there is error saying that 'unable to open object <component not found>' when i tried to open the output for the antenna. is it because i used the old version of gprmax which is version 3.0.0b18?

**Comment by craig-warren** [comment]
@ugy77 v.3.0.0b18 is pretty old now. Can you post the error message you are getting please.

**Comment by ugy77** [comment]
this is the error that i got.
![image](https://cloud.githubusercontent.com/assets/20106006/17297668/94f952ea-57fe-11e6-8e9b-b1a3c743cb2c.png)

**Comment by craig-warren** [comment]
So firstly, you should definitely update to the latest version (from the master branch) as the b18 indicates the version you have was still in the beta phase and a lot of development has happened since then ; and secondly, have you changed the Mala antenna model to use a ``#transmission_line`` source? By default it uses a ``#voltage_source`` but if you want to look at antenna parameters such as s11, input impedance you'll need to change to a ``#transmission_line``. This will likely alter the output of the antenna model slightly.

**Comment by ugy77** [comment]
thank you, 
then i will try to use the latest version and change the model to use transmission line.

**Comment by ugy77** [comment]
@craig-warren , the latest version that u mentioned before is the v3.0.0 right? do i have to use miniconda version 2.7 or the latest one? Since I already tried to install the latest version of gprmax, however, there are some errors when i tried to use the command "conda env create -f conda_env.yml".

**Comment by ugy77** [comment]
![error installation](https://cloud.githubusercontent.com/assets/20106006/17366363/c24473ee-5982-11e6-95e5-e5de80277683.PNG)


I'm using latest version of gprmax which is v-3.0.0..and miniconda 3, yet the errors occured as shown in the figure. Is there any other way that can I use to update the gprMax?

**Comment by craig-warren** [comment]
@ugy77 Looks like a problem with the ``mpi4py`` package on Windows. I have not seen problems with this before. Did you follow the installation instructions exactly, and if not, can you list the steps you took.

**Comment by ugy77** [comment]
I follow the instruction correctly as it shown in the user guide. I use gprMax v 3.0.0 and miniconda 3,. after installation of miniconda 3 i opened the command prompt and then updte the conda, install git and type the conda env create -f conda_env.yml. same as the steps that i used to install v 3.0.0b18. However, if i used the old version, the installation was completed and i can run the example in the user models, however having problem when i tried to open the output for the antenna like mala and GSSI only, for the other example such as wire dipole and cylinder, I can get the output correctly as the results showed in the user guide.

**Comment by craig-warren** [comment]
You should have v.3.0.5 if you followed the instructions (as that is the version in the master branch on GibHub). Did you complete the build and install steps? i.e. ``python setup.py build`` followed by ``python setup.py install``?

**Comment by ugy77** [comment]
I already tried to use the version in the master branch, and already follow the step as shown in the user guide and also watch the video of installation in the youtube, which are used the latest miniconda 3.5 and  follow the steps correctly, however when i want to create the env by typing conda env create -f conda_env.yml, it showed the error as in the last picture that i post yesterday about the mpi4py. then when i tried to proceed with the python setup.py build and install. it showed this error. 
![error python](https://cloud.githubusercontent.com/assets/20106006/17395946/cfa290ce-5a28-11e6-8f3d-5622ca192662.PNG)

**Comment by craig-warren** [comment]
OK, so stick with v.3.0.5 from the master branch. It seems your conda environment is not being created properly. Lets try creating the environment without the ``mpi4py`` package:

- Edit the ``conda_env.yml`` (in the gprMax directory) file and remove the line ``- mpi4py``
- Then try creating the environment again with ``conda env create -f conda_env.yml``

**Comment by ugy77** [comment]
@craig-warren , Thank you so much, after deleting the -mpi4py, the gprmax can be installed correctly.

**Comment by craig-warren** [comment]
Great. I'm going to close this issue now as it has mostly been about installation and ``mpi4py``. Please open a new issue if you still have difficulties using the Mala antenna model.
