### ISSUE TITLE
Error with the plotting output for antenna like MALA

### ISSUE THREAD

**Issue by ugy77** [gprMax/gprMax#67]
@craig-warren , I tried to run the simulation for the antenna like MALA and the simulation completed. However, when I tried to plot the output of the Ey graph as shown in the figure in the user guide, there are some error said that the "unable to open the object", 
![error](https://cloud.githubusercontent.com/assets/20106006/17400383/65c11f24-5a3f-11e6-8c85-442e487086b8.PNG)

**Comment by craig-warren** [comment]
@ugy77 What exactly are you trying to do?

The Mala antenna model uses a ``#rx`` (by default) on the receiver bowtie. You can plot the output from this by using ``python -m tools.plot_Ascan user_models/antenna_like_MALA_1200_fs.out --outputs Ey`` which will give you the plot shown in the docs. 

If you are interested in investigating the s11, input impedance etc... of the antenna model, then you will need to change the ``#rx`` to a``#transmission_line`` (in user_libs/antennas.py) and you can use ``python -m tools.plot_antenna_params user_models/antenna_like_MALA_1200_fs.out`` which will calculate and plot these parameters. You should have a good understanding of the antenna models before you begin customising them in this way.

**Comment by ugy77** [comment]
okay, thank you so much @craig-warren , now I get it. Before this I thought that if i want to plot the Ey, i still need to use plot_antenna_params. U help me a lot, and I will try to understand more about the antenna models.
