### ISSUE TITLE
Taguchi optimisation module issues

### ISSUE THREAD

**Issue by Mark-Dunscomb** [gprMax/gprMax#68]
Hi, I've been using the Taguchi optimization module and have had some issues.  This morning I updated gprMax and attempted to rerun the process and have a new error; unicode reference to the file name of the code to compile.  I'm not entirely sure what '<string>' is referencing so am not sure why characters 9 and 10 reference.  Can you help?  Error message is below.
Thanks!

Traceback (most recent call last):
  File "C:\Anaconda3\envs\gprMax\lib\runpy.py", line 184, in _run_module_as_main

    "__main__", mod_spec)
  File "C:\Anaconda3\envs\gprMax\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\gprMax\gprMax\__main__.py", line 6, in <module>
    gprMax.gprMax.main()
  File "C:\gprMax\gprMax\gprMax.py", line 72, in main
    run_main(args)
  File "C:\gprMax\gprMax\gprMax.py", line 114, in run_main
    run_opt_sim(args, numbermodelruns, inputfile, usernamespace)
  File "C:\gprMax\gprMax\optimisation_taguchi.py", line 59, in run_opt_sim
    taguchinamespace = taguchi_code_blocks(inputfile, tmp)
  File "C:\gprMax\gprMax\optimisation_taguchi.py", line 205, in taguchi_code_blo
cks
    taguchicompiledcode = compile(taguchicode, '<string>', 'exec')
  File "<string>", line 11
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in positio
n 9-10: truncated \uXXXX escape

**Comment by Mark-Dunscomb** [comment]
Just solved my own issue.  I had used backslashes in the fitness dictionary to indicate the reference file path instead of forward slashes for gprMax format.

**Comment by craig-warren** [comment]
@Mark-Dunscomb glad you solved it. Feedback on the Taguchi optimisation module always welcome, as I think there are a limited number of people using it.

**Comment by Mark-Dunscomb** [comment]
Hi Craig,  I seem to have other issues that I haven't worked out yet.  They are the same that I alluded to in my first post.  That is, the process runs through 18 iterations and then provides the error shown below.  
Symptoms (perhaps related but maybe not):  

-The first time I ran it, I did not include a maxiterations value so it should have run 20 times.  The second time I ran it, I included 'maxiterations': 2 in the fitness directory; still ran 18 times and gave the error below.

-Output files are saved for each iteration but not with "_final.out" as should occur if being saved by the taguchi module.

-The optimization results are not pickled into a ..hist.pickle file.

-Optimization parameters are not shown on the screen at the start of each iteration.

-The reference file is present in the directory indicated in the error message and the name is correct.  

All of this seems to indicate (to me) that fitness_functions.py and/or optimisation_taguchi.py are not being incorporated properly.  

Any thoughts would be greatly appreciated.  thanks!!
###################################################

=== Simulation completed in [HH:MM:SS]: 2:39:08 ===============================

Traceback (most recent call last):
  File "C:\Anaconda3\envs\gprMax\lib\runpy.py", line 184, in _run_module_as_main

    "__main__", mod_spec)
  File "C:\Anaconda3\envs\gprMax\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\gprMax\gprMax\__main__.py", line 6, in <module>
    gprMax.gprMax.main()
  File "C:\gprMax\gprMax\gprMax.py", line 72, in main
    run_main(args)
  File "C:\gprMax\gprMax\gprMax.py", line 114, in run_main
    run_opt_sim(args, numbermodelruns, inputfile, usernamespace)
  File "C:\gprMax\gprMax\optimisation_taguchi.py", line 119, in run_opt_sim
    fitnessvalues.append(fitness_metric(outputfile, fitness['args']))
  File "C:\gprMax\user_libs\optimisation_taguchi\fitness_functions.py", line 106
, in xcorr
    with open(args['refresp'], 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/gprMax/user_libs/opt
imsation_taguchi/GSSI_400MHz_real.txt'

(gprMax) C:\gprMax>

**Comment by Mark-Dunscomb** [comment]
More info:  The primary issue seems to be that I haven't properly referenced the reference response file correctly.  Forward slashes in the path are not understood as a proper path and back slashes indicate an escape so are generating an error.  I tried using r'C:\...' with no success.  I've included the following dictionary in fitness:
'args': {'refresp': 'C:\gprMax\user_libs\optimsation_taguchi\GSSI_400MHz_real.txt', 'outputs': 'RXout'}

How should I be referencing the reference file?
Thanks again, I apologize for the simple python issues.

**Comment by craig-warren** [comment]
@Mark-Dunscomb Yeh, looks like Python can't find/open your reference response file. I've made a couple of changes to make attempting this more robust. Update and try.

Have a look at the docs on the Taguchi process (http://docs.gprmax.com/en/latest/_images/taguchi_process.png). The 18 iterations you refer to are actually 18 experiments (stage 3) that compose part of a single iteration of the process (stages 2-4). So setting ``maxiterations`` to 2 will conduct 2 x (18 experiments + 1 confirmation experiment). The number of experiments is governed by the size of the orthogonal array required to optimise however many parameters you have.

**Comment by Mark-Dunscomb** [comment]
Thanks Craig,  Yeah, thanks, I realized my mistake confusing maxiterations and experiments.  
Line 108 in fitness_functions.py within the xcorr function is:
refrespfile = os.path.absopath(args['refrespfile'])
Should it not be pulling args['refresp']?

Thanks again.

**Comment by craig-warren** [comment]
Yes it should....Fri copy/paste error! Fixed now.

**Comment by Mark-Dunscomb** [comment]
Thanks.  Sim is running.

**Comment by Mark-Dunscomb** [comment]
Hi Craig,
  
I'm encountering a new issue with fitness_functions.py; an UnboundLocalError from Line 136.  Full Error message is below.  I tried specifying modelresp as nonlocal but that didn't do the trick.  Perhaps the "if" statement in Line 123 is not True so modelresp is not defined/bound in Line 125?  Anyway, any thoughts?

Also, in fitness_functions.py
Line 111 should be:
      `with open(refrespfile, 'r') as f:`
instead of:
     `with open(refresp, 'r') as f:`

Also, I originally had written the fitness dictionary in my *.in file in multiple lines so it was easier to read but that messes with the line counter to determine how many optimization parameters there are so I had to the edit the dictionary to be on one line.

Here's to the weekend!  
Mark

Traceback (most recent call last):
  File "C:\Anaconda3\envs\gprMax\lib\runpy.py", line 184, in _run_module_as_main    "__main__", mod_spec)
  File "C:\Anaconda3\envs\gprMax\lib\runpy.py", line 85, in _run_code  exec(code, run_globals)
  File "c:\gprMax\gprMax\__main__.py", line 6, in <module>    gprMax.gprMax.main()
  File "c:\gprMax\gprMax\gprMax.py", line 72, in main    run_main(args)
  File "c:\gprMax\gprMax\gprMax.py", line 114, in run_main  run_opt_sim(args, numbermodelruns, inputfile, usernamespace)
  File "c:\gprMax\gprMax\optimisation_taguchi.py", line 119, in run_opt_sim fitnessvalues.append(fitness_metric(outputfile, fitness['args']))
  File "c:\gprMax\user_libs\optimisation_taguchi\fitness_functions.py", line 136, in xcorr
    modelresp = modelresp / np.amax(np.abs(modelresp))
UnboundLocalError: local variable 'modelresp' referenced before assignment

**Comment by craig-warren** [comment]
Hi Mark,

It shouldn't matter how many lines your ``optparams`` dictionary is written on, so long as it is correct Python. The algorithm just gets the length of the dictionary.

I've corrected line 111, and put some more robust checking into the ``fitness_functions`` module overall. I'll commit these changes tomorrow and you can try them.

I think your error is a result of the algorithm not finding the output in the file. Perhaps you can copy/paste (or better attach) your input file here so I can take a look.

**Comment by Mark-Dunscomb** [comment]
thanks Craig,  Unfortunately the file is on a computer in my office.  I'll send it first thing in the morning, my time.

**Comment by Mark-Dunscomb** [comment]
Hi Craig,
I probably mis-interpreted earlier errors as related to the number of lines in the fitness dictionary.

Here are the input files.  I've attached two; an input file with 5 parameters to optimize and a second "test" file with only one parameter to optimize. I've been using the second to work through bugs, etc.  They are the same other than the number of Optparam's.

Both are renamed as *.txt files because Github will not accept them as *.in files.

Thanks again!


[GSSI_400MHz_Opt_TEST.txt](https://github.com/gprMax/gprMax/files/418061/GSSI_400MHz_Opt_TEST.txt)



[GSSI_400MHz_Opt.txt](https://github.com/gprMax/gprMax/files/418033/GSSI_400MHz_Opt.txt)

**Comment by craig-warren** [comment]
@Mark-Dunscomb one problem I see without running your input files is that you don't have any receiver labelled ``RXout``. You should change:
``rx(Antcntr[0] - 0.080, Antcntr[1] - 0.001, 0.049) `` to 
``rx(Antcntr[0] - 0.080, Antcntr[1] - 0.001, 0.049, identifier='RXout', to_save=['Ey']) ``

**Comment by Mark-Dunscomb** [comment]
Ah, that makes sense.
The sim is running now so I'll know in an hour if that is the only issue (hopefully it is).

BTW, I used the line you provided but received an error with the "to_save=['Ey']" statement so I changed the entire line to:
`print('#rx: {} {} 0.049 RXout Ey'.format(Antcntr[0] - 0.080, Antcntr[1] - 0.001))`
which had no issues. Honestly, I'm not sure why the "to_save" statement gave an error.

I also received a syntax error on Line 192 of fitness_functions.py  so changed it to:
` if outputs == 0:`

**Comment by Mark-Dunscomb** [comment]
Hi Craig,

The test simulation ran although there still may be some bugs.  I set the maxiterations in this test to 1; however it conducted 3 iterations and then stopped based on the delta between iterations.   In fact, the optimization parameter (excitation pulse center frequency in this case) was not changed at all though the three iterations and the delta was zero.  The initial choice was the median of the range, which is appropriate, but the value was not altered in subsequent iterations.  Thoughts why that might happen?

Thanks again for all your help.

[GSSI_400MHz Opt TEST Excitation Freq history.pdf](https://github.com/gprMax/gprMax/files/419107/GSSI_400MHz.Opt.TEST.Excitation.Freq.history.pdf)
[GSSI_400MHz Opt TEST Fitness Value history.pdf](https://github.com/gprMax/gprMax/files/419106/GSSI_400MHz.Opt.TEST.Fitness.Value.history.pdf)

[GSSI_400MHz_Opt_TEST Opt Summary.txt](https://github.com/gprMax/gprMax/files/419098/GSSI_400MHz_Opt_TEST.Opt.Summary.txt)

**Comment by craig-warren** [comment]
It ran for 3 iteration because the ``maxiterations`` variable should not be part of the ``fitness`` dictionary. It should be declared on it's own in the ``#taguchi`` block. I would not test with only a single parameter as this is not what orthogonal arrays were designed for.

I had a discussion in #62 about the scorer function which you might find useful.
