### ISSUE TITLE
 #pml_cells has too many cells for the domain size

### ISSUE THREAD

**Issue by meirgershenson** [gprMax/gprMax#71]
I am trying very simple model.  It worked before with slightly different parameters, but now it quit.
Can you look over it?
Yours Meir
My model is =

#title: Depth response in a dielectric half-space 20m ideal beheviour
#domain: 2.0 22.0 0.1
#dx_dy_dz: 0.1 0.1 0.1
#time_window: 1.0e-7
---------------------------------------------------
#material: 6.0 0.00 1 0 half_space
#waveform: gaussian 1 1.5e8 my_gaussian
#hertzian_dipole: z 1.0 21.0 0 my_gaussian
#rx: 1.0 1.0 0.0
-----------------------------------------------------
#box: 0.0 0.0 0.0 2.0 22.0 0.1 free_space
#box: 0.0 0.0 0.0 2.0 21.0 0.1 half_space
#geometry_view: 0.0 0.0 0.0 2.0 22.0 0.1 0.1 0.1 0.1 Depth_response n

The end of the output is .........    

  File "C:\Users\meir\Desktop\gprmax\gprMax\input_cmds_singleuse.py", line 196, in process_singlecmds
    raise CmdInputError(cmd + ' has too many cells for the domain size')
gprMax.exceptions.CmdInputError: #pml_cells has too many cells for the domain size

**Comment by craig-warren** [comment]
@meirgershenson you only have 20 cells in the x direction of your model domain. Since the standard PML uses 10 cells, 20 cells is not enough.

Craig

**Comment by meirgershenson** [comment]
Thanks
