### ISSUE TITLE
more threads (8) than available physical CPU cores (4)

### ISSUE THREAD

**Issue by meirgershenson** [gprMax/gprMax#72]
I have CPU E5 1620 with 4 CPUs and 8 threads I let GPRmax chose the threads itself and it comes with a message 
WARNING: You have specified more threads (8) than available physical CPU cores (4). This may lead to degraded performance.
Is it relay a problem?

JUST FOUND THE ANSWER DOWN STREAM.

**Comment by craig-warren** [comment]
@meirgershenson gprMax tries to avoid using hyper-threading on Intel CPUs as we have seen this tends to degrade performance. Do you have a single Intel E5-1620 CPU, i.e. 4 cores, 8 cores (with hyperthreading)?
