### ISSUE TITLE
How to write a CSP (Common shot point) in file

### ISSUE THREAD

**Issue by fanciedgpr** [gprMax/gprMax#73]
@craig-warren 
Hi, craig, I want to get a Bscan of Common shot point, that the source point is fixed, and a serial the receive points are arranged in line. How to write the in file that make the software just compute once? How to use the commands?

S   R1   R2   R3      Rn
--------------------------
~ ........~
..~......~
...~..~
......~
 ------------------------

#title: CSP B-scan from layer half-space
#domain: 1 1 0.002
#dx_dy_dz: 0.002 0.002 0.002
#time_window: 18e-9

#material: 6 0 1 0 half_space2
#material: 3 0 1 0 half_space1

#waveform: ricker 1 0.8e9 my_ricker
#hertzian_dipole: z 0.1 0.90 0 my_ricker
#rx: 0.11 0.9 0
#src_steps: 0 0 0 (???)
#rx_steps: 0.02 0 0

#box: 0 0 0 1 0.9 0.002 half_space1
#box: 0 0 0 1 0.6 0.002 half_space2

**Comment by agianno** [comment]
This is not a bug or an issue and this is not the place for such questions. Please use the gprMax forum for questions about using gprMax
