### ISSUE TITLE
Core dump error with #rough_surface command in heterogeneous_soil.in

### ISSUE THREAD

**Issue by Arsenal0768** [gprMax/gprMax#74]
error arises when rough surface simulation is carried out with the example 'heterogeneous_soil.in'
In windows 7 & windows 10 an error arise after the prompt:
'Fractal box my_soil_box from 0m, 0m, 0m, to 0.15m, 0.15m, 0.07m with my_soil, fractal dimension 1.5, fractal weightings 1, 1, 1, fractal seeding None and with 50 values created.
Fractal surface from 0m, 0m, 0.07m, to 0.15m, 0.15m, 0.07m with fractal dimension 1.5, fractal weightings 1, 1, fractal seeding None, and range 0.065m to 0.08m, added to my_soil_box.'

In Ubuntu
--geometry-only can execute, but at the end of the simulation, core_dump error arises
and if use the -n to get a B-Scan, after the first simulation completes, the same error arises.

Thank you in advance for your answer.

Besides, can i use the command #add_surface_roughness to simulate any rough surface
for example
#material: 6 0 1 0 concrete
#fractal_box: 0 0 0 0.15 0.15 0.070 1.5 1 1 1 50 concrete my_soil_box
#add_surface_roughness: 0 0 0.070 0.15 0.15 0.070 1.5 1 1 0.065 0.080 my_soil_box

Thank you in advance for your answer.

**Comment by craig-warren** [comment]
@Arsenal0768 which version of gprMax are you using?

**Comment by Arsenal0768** [comment]
v3.0.7, I just update gprMax

**Comment by Arsenal0768** [comment]
in Ubuntu:
Memory (RAM) used: ~390MB
*** Error in `python': munmap_chunk(): invalid pointer: 0x00007fef7229d010 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7fef84138725]
................
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

**Comment by craig-warren** [comment]
I can reproduce this bug on Windows 7/10 and Linux (Ubuntu 16.04), but not Mac OS X. It seems related to the ``#add_surface_roughness`` command, as commenting this command from the input file ``heterogeneous_soil.in`` makes the bug disappear. I'll look into the problem.

@Arsenal0768 you should be careful with your example:
``#material: 6 0 1 0 concrete``
``#fractal_box: 0 0 0 0.15 0.15 0.070 1.5 1 1 1 50 concrete my_soil_box``
``#add_surface_roughness: 0 0 0.070 0.15 0.15 0.070 1.5 1 1 0.065 0.080 my_soil_box``

What are you trying to achieve? A rough surface on a slab of concrete? If so, you must set the number of materials in the ``fractal_box`` command to 1 (not 50) to use it with a standard material, i.e. your ``concrete`` see http://docs.gprmax.com/en/latest/input.html#fractal-box This will give you a homogeneous box with a rough surface. 

The ``heterogeneous_soil.in`` example uses a Peplinski soil model (and a fractal box) to create a representation of a heterogeneous soil with fractal distributed properties.

**Comment by Arsenal0768** [comment]
thank you very much!
yes i want to simulate the EM in rough surface on a slab of concrete.
and another question is 
every A-Scan simulation, the simulator will read the .in file, and #add_surface_roughness command will execute to generate a random surface. 
does that mean the command #add_surface_roughness can't be used to B-Scan simulation?
if that is the case, how to simulate the rough surface in B-Scan? with the command #geometry_objects_file?
is there any example about the #geometry_objects_file except the AustinManWoman and the Mine.
I have read the lines in file 'input_cmds_geometry.py'

# Open geometry object file and read/check spatial resolution attribute
            f = h5py.File(geofile, 'r')
            dx_dy_dz = f.attrs['dx, dy, dz']
            if dx_dy_dz[0] != G.dx or dx_dy_dz[1] != G.dy or dx_dy_dz[2] != G.dz:
                raise CmdInputError("'" + ' '.join(tmp) + "'" + ' requires the spatial resolution of the geometry objects file to match the spatial resolution of the model')
            data = f['/data'][:]

but I don't know how the coordinate data organized, especially polygon.

thank you again. @craig-warren

**Comment by craig-warren** [comment]
@Arsenal0768 can you re-post your question in the Forum (Google Group) - http://www.gprmax.com/forum.shtml The forum is for more general questions, rather than bugs. Lets keep this thread just for solving the aforementioned issue with the ``#add_rough_surface`` command on Windows and Linux.

**Comment by craig-warren** [comment]
This bug should now be corrected (v.3.0.8). It was an out-of-bounds issue in the function ``build_voxels_from_array_mask``. Thanks for highlighting this @Arsenal0768

**Comment by Arsenal0768** [comment]
thank you very much!
