### ISSUE TITLE
Ground Response in B-scan from Uneven Surface Simulation is Even

### ISSUE THREAD

**Issue by ijxique** [gprMax/gprMax#77]
I have run the following simulation:

`
#title: gprMaxSim 
#num_threads: 12 
#domain: 1.00 1.00 0.70
#dx_dy_dz: 0.00500 0.00500 0.00500 
#time_step_stability_factor: 0.980 
#time_window: 1.564e-08 
#material: 4.0 0.01 1.0 0.0 ground 
#material: 16.0 0.01 1.0 0.0 target 

#waveform: ricker 1.00 900000000.00 wave_src 

#pml_cells: 10 

#python:
tmp = current_model_run-1; 
stepSize = 0.02
offset = 0.025000 
print( '#hertzian_dipole: z {} 0.500000 0.600000 wave_src'.format( 0.200000 + stepSize * tmp  ));
print( '#rx: {} 0.500000 0.600000'.format( (0.200000 +  offset) + stepSize * tmp ) );
#end_python:

#fractal_box: 0.0 0.0 0.0 1.00 1.00 0.50 1.5 1 1 1 1 ground my_soil_box 1
#add_surface_roughness: 0 0 0.5 1.00 1.00 0.50 1.5 1 1 0.4 0.55 my_soil_box 1
#box: 0.45 0.45 0.20 0.55 0.55 0.30 target

#geometry_view: 0 0 0 1.00 1.00 0.70 0.00500 0.00500 0.00500 heterogeneous_soil n
`

It is supposed to produce a single B-scan with an uneven ground response, but after combining all the A-scans together the B-scan continues to have an even ground response. Does gprMax realign the A-scans to make the B-scan or am I messing up somewhere? I have attached images of the geometry and B-scan. Any help will be greatly appreciated. 

![target_geo5](https://cloud.githubusercontent.com/assets/22499433/18915537/5b686a5a-855f-11e6-822e-d649bc09ea64.png)

![matlab_record_28-sep-2016_00002](https://cloud.githubusercontent.com/assets/22499433/18915548/637d2d0c-855f-11e6-8a92-c64209faa49c.png)

**Comment by craig-warren** [comment]
Moved to the Forum (Google Group) at [http://www.gprmax.com/forum.shtml?place=msg%2Fgprmax%2F37NtHkFvh5s%2FTe33-dXNAAAJ](http://www.gprmax.com/forum.shtml?place=msg%2Fgprmax%2F37NtHkFvh5s%2FTe33-dXNAAAJ)
