### ISSUE TITLE
warning message

### ISSUE THREAD

**Issue by GHozzi** [gprMax/gprMax#80]
Hi GprMax,

 I have simulated this example:

-------------------------- Media_file -------------------------------------
#material: 3 0 1 0 dry_sand
#material: 2.25 1.2e-3 1 0 polyethylene
---------------------------- Domain -------------------------------------
#domain: 2.000 2.000 1.000
#dx_dy_dz: 0.01 0.01 0.01
#time_window: 12e-9 
----------------- Geometry of the problem defined here ----------------
#box: 0.0 0.0 0.0 2.00 2.00 0.85 dry_sand
----------- pipe = pec cylinders with air cylinders inside -----------------
#cylinder: 0.0 1.00 0.53 2.00 1.00 0.53 0.10 polyethylene
#cylinder: 0.0 1.00 0.53 2.00 1.00 0.53 0.09 free_space
-----------------------------Source of TX--------------------------------
#waveform: gaussian  1.0 1e9 my_gaussian 
#hertzian_dipole: x 1.00 0.10 0.86 my_gaussian 
#rx: 1.05 0.10 0.86
#src_steps: 0.0  0.05  0.0
#rx_steps: 0.0  0.05  0.0
-----------------------------------------------------------------------

But, when I try to simulate this example I get some warning (see Fig), Does anyone know how to fix this error.

Many thanks in advance for your assistance.

![sans titre](https://cloud.githubusercontent.com/assets/16916511/20091847/3708f9f8-a595-11e6-80f4-2143220dcca0.png)

**Comment by craig-warren** [comment]
This is not a bug, it is an informative message about the potential effects of numerical dispersion. This is something you should be aware of when using FDTD. For a very brief explanation see the docs http://docs.gprmax.com/en/latest/gprmodelling.html
