### ISSUE TITLE
rx_array bug

### ISSUE THREAD

**Issue by rjdelf** [gprMax/gprMax#81]
I'm running a model in 2D where I want an output at every 1m along the top surface. 
I tried running with the rx_array command however received an error when the simulation started after loading in the geometry objects file. Input file and returned error are attached. Running locally on windows.
I used a short python command as a quick fix to generate all receivers but wasn't sure if this is my input or a bug.

Cheers,
Richard

[wide_model_array.txt](https://github.com/gprMax/gprMax/files/603563/wide_model_array.txt)
[error.txt](https://github.com/gprMax/gprMax/files/603558/error.txt)

**Comment by craig-warren** [comment]
Hi Richard,

I think the error is in the way you are specifying the ``#rx_array``. To get a line of receivers in the x-direction, the y and z coordinates should be the same. Try ``#rx_array: 1 95 0 149 95 0 1 0 0`` which defines a line from 1 to 149m with a receiver every 1m.

Cheers,
Craig

**Comment by rjdelf** [comment]
Hi Craig,

Thanks for that, working no problem now. My bad!

Cheers,

Richard

**Comment by craig-warren** [comment]
No probs.
