### ISSUE TITLE
Geometric Model

### ISSUE THREAD

**Issue by GHozzi** [gprMax/gprMax#85]
Hi,

I would like to know, please, whether I could do a geometric model of crack using GprMax.  As shown in Figure below.
Thank you in advance for your answer. 

![crack](https://cloud.githubusercontent.com/assets/16916511/21004647/c0ad0772-bd31-11e6-8d49-9858262e7118.jpg)

**Comment by craig-warren** [comment]
This is not an issue with the code. Please post general questions about usage in the Forum (Google Group) at http://www.gprmax.com/forum.shtml
