### ISSUE TITLE
error message when stimualting the gprMax examples

### ISSUE THREAD

**Issue by starrynightcsu** [gprMax/gprMax#86]
Hello, masters!

I read your paper in Computer Physics Communications and learn about the new version of gprMax. After reading use guide, I found many amazing improvements in gprMax 3. I could't wait to install it, but after installing some errors happaned. Actually I fellow the install video which you published in youbube step by step and pass the test order in the end of the video. However, when running the examples offered from gprMax, it reminds me that ***"Attribute error:'str' object has no attribute 'endwith'*** and i capture the screen in the bottom which can show more details.

I have reinstalled for several times and same problme occured again and again. I also tried to install in different computers, wind7 64 and win7 32 and it showed same errors . Could your give some advices for solving this problem ?  

![q3 od45rwh7 y skreb7 8](https://cloud.githubusercontent.com/assets/21352357/21035894/3be4c404-bdfd-11e6-87e6-18ea788309f4.png)

**Comment by craig-warren** [comment]
Thanks for pointing this out. I think it is related to a recent update that attempts to detect the machine and CPU that gprMax is running on. It worked on my development MacOS machine, but clearly there is a problem on Windows. I'll check it on my Windows VMs today.

**Comment by craig-warren** [comment]
Fixed. Please do a `git pull` to pick up the latest change (https://github.com/gprMax/gprMax/commit/ac402b81516ec9375b4cb57896efbcdbf12cf885)
