### ISSUE TITLE
threadspercore not defined

### ISSUE THREAD

**Issue by craig-warren** [gprMax/gprMax#98]
`threadspercore` is a variable in the `utilities.py` module used in the `get_host_info()` function. When trying to detect the host information on certain Linux systems it is not being defined.

**Comment by meirgershenson** [comment]
Any update to authors about paper acceptance?

**Comment by gbstravassos** [comment]
Hi,
 I'm having problems with the gprMax. I proceed the installation step-by-step just like described by the user guide without any problems, but when I try to run a test model the following error message is showed by terminal: "UnboundLocalError: local variable 'threadspercore' referenced before assignment". I tried to look for similar things on google but I didn't find anything. I'm using the Ubuntu 16.04 and the processor is the Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz. Do you have any ideia of what is happening and how to fix this problem?  

Thanks,
Guilherme

**Comment by craig-warren** [comment]
@gbstravassos This should now be fixed. Pull the latest code from the master branch, i.e. navigate to the top-level gprMax directory and run `git pull`
