### ISSUE TITLE
Paraview crashing will large number of materials

### ISSUE THREAD

**Issue by craig-warren** [gprMax/gprMax#99]
Paraview (5.2 and 5.3) on Mac OS locks up my machine when using the `gprMax_info` macro to threshold and render materials. This seems to happen with models that contain >~50 materials. Is this a problem with the macro?

**Comment by Mark-Dunscomb** [comment]
I've had a similar issue with the macro but am not convinced it's related to the number of materials.  Rather, the size of the *.vti file may be the issue.  Paraview (v.5.4.0) crashed while running the gprMax_info.py macro on a geometry *.vti file of a large model space with 25 materials. Running it on a geometry file encapsulating a 2D slice (one cell thick) of the same model space worked fine - same number of materials.  Difference: the first file is ~9.5E+08 cells and 5.5 GB whereas the second is ~3.9E+06 cells and 11.4 MB.  Neither exceeded the memory capacity of my computer.  The crash occurs before listing the first material in the pipeline.  If I were to guess, I'd say that the macro crashes in the materials search (lines 61 to 73 in gprMax_info.py).

**Comment by craig-warren** [comment]
@Mark-Dunscomb Thanks for the info. So, I don't think it relates to the initial reading of the file (lines 41-42), as this method should read the file line-by-line, so the whole file is not stored in memory. It might be Paraview struggling to do a Threshold filter for such a large file size - which is what happens in lines 61-73. If you get a chance, can you try opening the file that caused the crash, don't run the macro, but try to create Threshold filter manually for a value of 0 (i.e. pec), and then a value of 1 (free_space). See if that also causes a crash.

**Comment by Mark-Dunscomb** [comment]
@craig-warren You're correct, that worked.  So I'm not very familiar with vti's or Paraview... Are the materials indexed as shown by gprMax at the start of a model run?  ..and what is a simple method to interrogate the file to list the materials and their index?
Thanks!

**Comment by craig-warren** [comment]
@Mark-Dunscomb The materials are indexed according to the table that is printed when gprMax runs. 0 is always pec, 1 is free space, and the rest depend on the model. By default, a vti file (or vtp) file just contains arrays of the material indices. We write an extra piece of XML on the end of the file that associates an index with a material name. This is then read when doing the thresholding in Paraview.

So, just to check, when you did a manual threshold of any of the material values, Paraview did not crash?

**Comment by Mark-Dunscomb** [comment]
@craig-warren Yes, a manual threshold filter separated each of the materials one by one.  It took pretty substantial computing power but it worked without errors.  In this case, the vti is 1.76 GB.  Performing the filter took around 30-45 min for each material, roughly 50 GB of RAM, and had my CPUs maxed.  The state also reopened without incident.  

Thanks for the helpful info on material indexing. 
Cheers

**Comment by craig-warren** [comment]
Wow! That is a lot of resource!

Perhaps there is some lack of memory cleanup when the thresholding is being done in a loop in the macro. I'll try and look into this when I get some time.

**Comment by Mark-Dunscomb** [comment]
@craig-warren  My thoughts as well.  The state requires ~ 25 GB, which isn't small but it is a relatively large model.  My point is that the processing takes roughly twice that amount of RAM.

**Comment by Mark-Dunscomb** [comment]
@craig-warren Ok, well that was interesting.  I was curious to confirm the time/RAM, etc. so ran the filter again.  Number of cells ~ 5e8.  vti size = 2.9 GB.  Time - 1 - 2 min per material depending on the extent of the material.  RAM used during processing = 40 - 50 GB.   No idea why it took so long the first time I attempted it.

**Comment by craig-warren** [comment]
Have not seen this in recent versions of Paraview so closing.
